%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: m
%% Source: /net/isildur/ldisk/daily_build/20_prebuild_master-opu_o.2017-06-20_20/otp_src_20/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(M_HRL).
-define(M_HRL, true).


-record(m_NotAnInteger, {'OE_ID'="IDL:m/NotAnInteger:1.0"}).


-endif.


