%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime
%% Source: /net/isildur/ldisk/daily_build/20_prebuild_master-opu_o.2017-06-20_20/otp_src_20/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_HRL).
-define(COSTIME_HRL, true).


-record('CosTime_TimeUnavailable', {'OE_ID'="IDL:omg.org/CosTime/TimeUnavailable:1.0"}).


-endif.


