/*
 *  Warning: Do not edit this file.
 *  Auto-generated by 'beam_makeops'.
 */

#ifndef __OPCODES_H__
#define __OPCODES_H__

#define BEAM_FORMAT_NUMBER 0
#define MAX_GENERIC_OPCODE 158
#define NUM_GENERIC_OPS 352
#define NUM_SPECIFIC_OPS 387
#define SCRATCH_X_REG 1023

#if !defined(ARCH_64)
  #error "64-bit architecture assumed, but ARCH_64 not defined"
#endif
#define BEAM_WIDE_MASK 0xFFFFUL
#define BEAM_LOOSE_MASK 0xFFFFUL
#define BEAM_TIGHT_MASK 0xFFFFUL
#define BEAM_WIDE_SHIFT 32
#define BEAM_LOOSE_SHIFT 16
#define BEAM_TIGHT_SHIFT 16

/*
 * The following operand types for generic instructions
 * occur in beam files.
 */

#define TAG_u 0
#define TAG_i 1
#define TAG_a 2
#define TAG_x 3
#define TAG_y 4
#define TAG_f 5
#define TAG_h 6
#define TAG_z 7

/*
 * The following operand types are only used in the loader.
 */

#define TAG_n 8
#define TAG_p 9
#define TAG_r 10
#define TAG_v 11
#define TAG_l 12
#define TAG_q 13
#define TAG_o 14

#define BEAM_NUM_TAGS 15

#define TOP_call_end 0
#define TOP_commit 1
#define TOP_end 2
#define TOP_fail 3
#define TOP_is_bif 4
#define TOP_is_func 5
#define TOP_is_not_bif 6
#define TOP_is_same_var 7
#define TOP_is_type 8
#define TOP_is_type_eq 9
#define TOP_keep 10
#define TOP_new_instr 11
#define TOP_next_arg 12
#define TOP_next_instr 13
#define TOP_pred 14
#define TOP_rename 15
#define TOP_rest_args 16
#define TOP_set_var_next_arg 17
#define TOP_store_rest_args 18
#define TOP_store_type 19
#define TOP_store_val 20
#define TOP_store_var_next_arg 21
#define TOP_try_me_else 22
#define TOP_try_me_else_fail 23
#define NUM_TOPS 24

#define TE_MAX_VARS 8

extern char tag_to_letter[];
extern Uint op_transform[];

#define op_allocate_tt 0
#define op_allocate_heap_tIt 1
#define op_allocate_heap_zero_tIt 2
#define op_allocate_init_tIy 3
#define op_allocate_zero_tt 4
#define op_apply_I 5
#define op_apply_bif 6
#define op_apply_last_IP 7
#define op_badarg_j 8
#define op_badmatch_x 9
#define op_bif1_fbsd 10
#define op_bif1_body_bsd 11
#define op_bs_add_jssId 12
#define op_bs_context_to_binary_x 13
#define op_bs_init_writable 14
#define op_bs_put_string_II 15
#define op_bs_put_utf16_jIs 16
#define op_bs_test_tail_imm2_fxI 17
#define op_bs_test_unit_fxI 18
#define op_bs_test_unit8_fx 19
#define op_bs_test_zero_tail2_fx 20
#define op_call_bif_e 21
#define op_call_error_handler 22
#define op_call_nif 23
#define op_case_end_x 24
#define op_catch_yf 25
#define op_catch_end_y 26
#define op_continue_exit 27
#define op_deallocate_I 28
#define op_deallocate_return_Q 29
#define op_error_action_code 30
#define op_fclearerror 31
#define op_fconv_dl 32
#define op_fmove_ql 33
#define op_fmove_ld 34
#define op_fmove_dl 35
#define op_get_list_rry 36
#define op_get_list_rxr 37
#define op_get_list_rxx 38
#define op_get_list_rxy 39
#define op_get_list_ryr 40
#define op_get_list_xrx 41
#define op_get_list_xxx 42
#define op_get_list_xxy 43
#define op_get_list_xyx 44
#define op_get_list_xyy 45
#define op_get_list_yxx 46
#define op_get_list_yxy 47
#define op_get_list_yyx 48
#define op_get_list_yyy 49
#define op_hipe_call_count 50
#define op_hipe_trap_call 51
#define op_hipe_trap_call_closure 52
#define op_hipe_trap_resume 53
#define op_hipe_trap_return 54
#define op_hipe_trap_throw 55
#define op_i_apply 56
#define op_i_apply_fun 57
#define op_i_apply_fun_last_P 58
#define op_i_apply_fun_only 59
#define op_i_apply_last_P 60
#define op_i_apply_only 61
#define op_i_band_jIxcd 62
#define op_i_band_jIssd 63
#define op_i_bif2_fbssd 64
#define op_i_bif2_body_bssd 65
#define op_i_bor_jIssd 66
#define op_i_bs_append_jIIIsd 67
#define op_i_bs_get_binary2_fxIsId 68
#define op_i_bs_get_binary_all2_fxIId 69
#define op_i_bs_get_binary_all_reuse_xfI 70
#define op_i_bs_get_binary_imm2_fxIIId 71
#define op_i_bs_get_float2_fxIsId 72
#define op_i_bs_get_integer_fIIssd 73
#define op_i_bs_get_integer_16_xfd 74
#define op_i_bs_get_integer_32_xfId 75
#define op_i_bs_get_integer_8_xfd 76
#define op_i_bs_get_integer_imm_xIIfId 77
#define op_i_bs_get_integer_small_imm_xIfId 78
#define op_i_bs_get_utf16_xfId 79
#define op_i_bs_get_utf8_xfd 80
#define op_i_bs_init_IId 81
#define op_i_bs_init_bits_IId 82
#define op_i_bs_init_bits_fail_xjId 83
#define op_i_bs_init_bits_fail_yjId 84
#define op_i_bs_init_bits_fail_heap_sIjId 85
#define op_i_bs_init_bits_heap_IIId 86
#define op_i_bs_init_fail_xjId 87
#define op_i_bs_init_fail_yjId 88
#define op_i_bs_init_fail_heap_sIjId 89
#define op_i_bs_init_heap_IIId 90
#define op_i_bs_init_heap_bin_IId 91
#define op_i_bs_init_heap_bin_heap_IIId 92
#define op_i_bs_match_string_xfII 93
#define op_i_bs_private_append_jIssd 94
#define op_i_bs_put_utf8_js 95
#define op_i_bs_restore2_xI 96
#define op_i_bs_save2_xI 97
#define op_i_bs_skip_bits2_fxxI 98
#define op_i_bs_skip_bits2_fxyI 99
#define op_i_bs_skip_bits_all2_fxI 100
#define op_i_bs_skip_bits_imm2_fxI 101
#define op_i_bs_start_match2_xfIId 102
#define op_i_bs_start_match2_yfIId 103
#define op_i_bs_utf16_size_sd 104
#define op_i_bs_utf8_size_sd 105
#define op_i_bs_validate_unicode_js 106
#define op_i_bs_validate_unicode_retract_jss 107
#define op_i_bsl_jIssd 108
#define op_i_bsr_jIssd 109
#define op_i_bxor_jIssd 110
#define op_i_call_f 111
#define op_i_call_ext_e 112
#define op_i_call_ext_last_eP 113
#define op_i_call_ext_only_e 114
#define op_i_call_fun_I 115
#define op_i_call_fun_last_IP 116
#define op_i_call_last_fP 117
#define op_i_call_only_f 118
#define op_i_debug_breakpoint 119
#define op_i_element_jxsd 120
#define op_i_element_jysd 121
#define op_i_fadd_lll 122
#define op_i_fast_element_jxId 123
#define op_i_fast_element_jyId 124
#define op_i_fcheckerror 125
#define op_i_fdiv_lll 126
#define op_i_fmul_lll 127
#define op_i_fnegate_ll 128
#define op_i_fsub_lll 129
#define op_i_func_info_IaaI 130
#define op_i_gc_bif1_jIsId 131
#define op_i_gc_bif2_jIIssd 132
#define op_i_gc_bif3_jIIssd 133
#define op_i_generic_breakpoint 134
#define op_i_get_sd 135
#define op_i_get_hash_cId 136
#define op_i_get_map_element_fxxx 137
#define op_i_get_map_element_fxxy 138
#define op_i_get_map_element_fyxx 139
#define op_i_get_map_element_fyxy 140
#define op_i_get_map_element_hash_fxcIx 141
#define op_i_get_map_element_hash_fxcIy 142
#define op_i_get_map_element_hash_fycIx 143
#define op_i_get_map_element_hash_fycIy 144
#define op_i_get_map_elements_fsI 145
#define op_i_get_tuple_element_xPx 146
#define op_i_get_tuple_element_xPy 147
#define op_i_get_tuple_element_yPx 148
#define op_i_get_tuple_element_yPy 149
#define op_i_get_tuple_element2_xPx 150
#define op_i_get_tuple_element2y_xPyy 151
#define op_i_get_tuple_element3_xPx 152
#define op_i_hibernate 153
#define op_i_increment_rIId 154
#define op_i_increment_xIId 155
#define op_i_increment_yIId 156
#define op_i_int_bnot_jsId 157
#define op_i_int_div_jIssd 158
#define op_i_is_eq_exact_immed_frc 159
#define op_i_is_eq_exact_immed_fxc 160
#define op_i_is_eq_exact_immed_fyc 161
#define op_i_is_eq_exact_literal_fxc 162
#define op_i_is_eq_exact_literal_fyc 163
#define op_i_is_ne_exact_immed_fxc 164
#define op_i_is_ne_exact_immed_fyc 165
#define op_i_is_ne_exact_literal_fxc 166
#define op_i_is_ne_exact_literal_fyc 167
#define op_i_jump_on_val_xfII 168
#define op_i_jump_on_val_yfII 169
#define op_i_jump_on_val_zero_xfI 170
#define op_i_jump_on_val_zero_yfI 171
#define op_i_loop_rec_f 172
#define op_i_m_div_jIssd 173
#define op_i_make_fun_It 174
#define op_i_minus_jIxxd 175
#define op_i_minus_jIssd 176
#define op_i_move_call_cf 177
#define op_i_move_call_ext_ce 178
#define op_i_move_call_ext_last_ePc 179
#define op_i_move_call_ext_only_ec 180
#define op_i_move_call_last_fPc 181
#define op_i_move_call_only_fc 182
#define op_i_new_bs_put_binary_jsIs 183
#define op_i_new_bs_put_binary_all_jsI 184
#define op_i_new_bs_put_binary_imm_jIs 185
#define op_i_new_bs_put_float_jsIs 186
#define op_i_new_bs_put_float_imm_jIIs 187
#define op_i_new_bs_put_integer_jsIs 188
#define op_i_new_bs_put_integer_imm_jIIs 189
#define op_i_perf_counter 190
#define op_i_plus_jIxxd 191
#define op_i_plus_jIxyd 192
#define op_i_plus_jIssd 193
#define op_i_put_tuple_xI 194
#define op_i_put_tuple_yI 195
#define op_i_raise 196
#define op_i_recv_set 197
#define op_i_rem_jIxxd 198
#define op_i_rem_jIssd 199
#define op_i_return_time_trace 200
#define op_i_return_to_trace 201
#define op_i_select_tuple_arity_xfI 202
#define op_i_select_tuple_arity_yfI 203
#define op_i_select_tuple_arity2_xfAAff 204
#define op_i_select_tuple_arity2_yfAAff 205
#define op_i_select_val2_xfccff 206
#define op_i_select_val2_yfccff 207
#define op_i_select_val_bins_xfI 208
#define op_i_select_val_bins_yfI 209
#define op_i_select_val_lins_xfI 210
#define op_i_select_val_lins_yfI 211
#define op_i_times_jIssd 212
#define op_i_trim_I 213
#define op_i_wait_error 214
#define op_i_wait_error_locked 215
#define op_i_wait_timeout_fI 216
#define op_i_wait_timeout_fs 217
#define op_i_wait_timeout_locked_fI 218
#define op_i_wait_timeout_locked_fs 219
#define op_i_yield 220
#define op_if_end 221
#define op_init_y 222
#define op_init2_yy 223
#define op_init3_yyy 224
#define op_int_code_end 225
#define op_is_atom_fx 226
#define op_is_atom_fy 227
#define op_is_binary_fx 228
#define op_is_binary_fy 229
#define op_is_bitstring_fx 230
#define op_is_bitstring_fy 231
#define op_is_boolean_fx 232
#define op_is_boolean_fy 233
#define op_is_eq_fss 234
#define op_is_eq_exact_fxx 235
#define op_is_eq_exact_fxy 236
#define op_is_eq_exact_fss 237
#define op_is_float_fx 238
#define op_is_float_fy 239
#define op_is_function_fx 240
#define op_is_function_fy 241
#define op_is_function2_fss 242
#define op_is_ge_fxx 243
#define op_is_ge_fxc 244
#define op_is_ge_fcx 245
#define op_is_ge_fss 246
#define op_is_integer_fx 247
#define op_is_integer_fy 248
#define op_is_integer_allocate_fxII 249
#define op_is_list_fx 250
#define op_is_list_fy 251
#define op_is_lt_fxx 252
#define op_is_lt_fxc 253
#define op_is_lt_fcx 254
#define op_is_lt_fss 255
#define op_is_map_fx 256
#define op_is_map_fy 257
#define op_is_ne_fss 258
#define op_is_ne_exact_fss 259
#define op_is_nil_fx 260
#define op_is_nil_fy 261
#define op_is_non_empty_list_test_heap_fIt 262
#define op_is_nonempty_list_fx 263
#define op_is_nonempty_list_fy 264
#define op_is_nonempty_list_allocate_frIt 265
#define op_is_nonempty_list_allocate_fxIt 266
#define op_is_nonempty_list_get_list_frxx 267
#define op_is_nonempty_list_get_list_fxxx 268
#define op_is_number_fx 269
#define op_is_number_fy 270
#define op_is_pid_fx 271
#define op_is_pid_fy 272
#define op_is_port_fx 273
#define op_is_port_fy 274
#define op_is_reference_fx 275
#define op_is_reference_fy 276
#define op_is_tuple_fr 277
#define op_is_tuple_fx 278
#define op_is_tuple_fy 279
#define op_is_tuple_of_arity_frA 280
#define op_is_tuple_of_arity_fxA 281
#define op_is_tuple_of_arity_fyA 282
#define op_jump_f 283
#define op_label_L 284
#define op_line_I 285
#define op_loop_rec_end_f 286
#define op_move_nx 287
#define op_move_rx 288
#define op_move_ry 289
#define op_move_xr 290
#define op_move_xx 291
#define op_move_xy 292
#define op_move_yr 293
#define op_move_yx 294
#define op_move_yy 295
#define op_move_cr 296
#define op_move_cx 297
#define op_move2_par_xxxx 298
#define op_move2_par_xxxy 299
#define op_move2_par_xxyx 300
#define op_move2_par_xyxy 301
#define op_move2_par_yxxx 302
#define op_move2_par_yxxy 303
#define op_move2_par_yxyx 304
#define op_move3_xxxxxx 305
#define op_move3_xyxyxy 306
#define op_move3_yxyxyx 307
#define op_move_call_xf 308
#define op_move_call_yf 309
#define op_move_call_last_xfQ 310
#define op_move_call_last_yfQ 311
#define op_move_call_only_xf 312
#define op_move_deallocate_return_nQ 313
#define op_move_deallocate_return_xQ 314
#define op_move_deallocate_return_yQ 315
#define op_move_deallocate_return_cQ 316
#define op_move_dup_xxx 317
#define op_move_dup_xxy 318
#define op_move_dup_yxx 319
#define op_move_dup_yxy 320
#define op_move_jump_fn 321
#define op_move_jump_fx 322
#define op_move_jump_fy 323
#define op_move_jump_fc 324
#define op_move_return_n 325
#define op_move_return_x 326
#define op_move_return_c 327
#define op_move_shift_xxx 328
#define op_move_shift_xxy 329
#define op_move_shift_xyx 330
#define op_move_shift_yxx 331
#define op_move_window3_xxxy 332
#define op_move_window4_xxxxy 333
#define op_move_window5_xxxxxy 334
#define op_move_x1_c 335
#define op_move_x2_c 336
#define op_new_map_dII 337
#define op_node_x 338
#define op_node_y 339
#define op_normal_exit 340
#define op_on_load 341
#define op_put_list_rnr 342
#define op_put_list_rnx 343
#define op_put_list_rxr 344
#define op_put_list_rxx 345
#define op_put_list_xnx 346
#define op_put_list_xrr 347
#define op_put_list_xxr 348
#define op_put_list_xxx 349
#define op_put_list_xyx 350
#define op_put_list_ynx 351
#define op_put_list_yrr 352
#define op_put_list_yxx 353
#define op_put_list_yyx 354
#define op_put_list_xcx 355
#define op_put_list_xcy 356
#define op_put_list_ycx 357
#define op_put_list_cxx 358
#define op_put_list_cyx 359
#define op_put_list_ssd 360
#define op_recv_mark_f 361
#define op_remove_message 362
#define op_return 363
#define op_return_trace 364
#define op_self_x 365
#define op_self_y 366
#define op_send 367
#define op_set_tuple_element_sdP 368
#define op_swap_xx 369
#define op_swap_xy 370
#define op_swap_temp_xxx 371
#define op_swap_temp_xyx 372
#define op_system_limit_j 373
#define op_test_arity_fxA 374
#define op_test_arity_fyA 375
#define op_test_heap_It 376
#define op_test_heap_1_put_list_Iy 377
#define op_timeout 378
#define op_timeout_locked 379
#define op_try_case_end_s 380
#define op_try_end_y 381
#define op_update_map_assoc_jsdII 382
#define op_update_map_exact_jsdII 383
#define op_wait_f 384
#define op_wait_locked_f 385
#define op_wait_unlocked_f 386

#define NUMBER_OF_OPCODES 387
#define op_count_allocate_tt 387
#define op_count_allocate_heap_tIt 388
#define op_count_allocate_heap_zero_tIt 389
#define op_count_allocate_init_tIy 390
#define op_count_allocate_zero_tt 391
#define op_count_apply_I 392
#define op_count_apply_bif 393
#define op_count_apply_last_IP 394
#define op_count_badarg_j 395
#define op_count_badmatch_x 396
#define op_count_bif1_fbsd 397
#define op_count_bif1_body_bsd 398
#define op_count_bs_add_jssId 399
#define op_count_bs_context_to_binary_x 400
#define op_count_bs_init_writable 401
#define op_count_bs_put_string_II 402
#define op_count_bs_put_utf16_jIs 403
#define op_count_bs_test_tail_imm2_fxI 404
#define op_count_bs_test_unit_fxI 405
#define op_count_bs_test_unit8_fx 406
#define op_count_bs_test_zero_tail2_fx 407
#define op_count_call_bif_e 408
#define op_count_call_error_handler 409
#define op_count_call_nif 410
#define op_count_case_end_x 411
#define op_count_catch_yf 412
#define op_count_catch_end_y 413
#define op_count_continue_exit 414
#define op_count_deallocate_I 415
#define op_count_deallocate_return_Q 416
#define op_count_error_action_code 417
#define op_count_fclearerror 418
#define op_count_fconv_dl 419
#define op_count_fmove_ql 420
#define op_count_fmove_ld 421
#define op_count_fmove_dl 422
#define op_count_get_list_rry 423
#define op_count_get_list_rxr 424
#define op_count_get_list_rxx 425
#define op_count_get_list_rxy 426
#define op_count_get_list_ryr 427
#define op_count_get_list_xrx 428
#define op_count_get_list_xxx 429
#define op_count_get_list_xxy 430
#define op_count_get_list_xyx 431
#define op_count_get_list_xyy 432
#define op_count_get_list_yxx 433
#define op_count_get_list_yxy 434
#define op_count_get_list_yyx 435
#define op_count_get_list_yyy 436
#define op_count_hipe_call_count 437
#define op_count_hipe_trap_call 438
#define op_count_hipe_trap_call_closure 439
#define op_count_hipe_trap_resume 440
#define op_count_hipe_trap_return 441
#define op_count_hipe_trap_throw 442
#define op_count_i_apply 443
#define op_count_i_apply_fun 444
#define op_count_i_apply_fun_last_P 445
#define op_count_i_apply_fun_only 446
#define op_count_i_apply_last_P 447
#define op_count_i_apply_only 448
#define op_count_i_band_jIxcd 449
#define op_count_i_band_jIssd 450
#define op_count_i_bif2_fbssd 451
#define op_count_i_bif2_body_bssd 452
#define op_count_i_bor_jIssd 453
#define op_count_i_bs_append_jIIIsd 454
#define op_count_i_bs_get_binary2_fxIsId 455
#define op_count_i_bs_get_binary_all2_fxIId 456
#define op_count_i_bs_get_binary_all_reuse_xfI 457
#define op_count_i_bs_get_binary_imm2_fxIIId 458
#define op_count_i_bs_get_float2_fxIsId 459
#define op_count_i_bs_get_integer_fIIssd 460
#define op_count_i_bs_get_integer_16_xfd 461
#define op_count_i_bs_get_integer_32_xfId 462
#define op_count_i_bs_get_integer_8_xfd 463
#define op_count_i_bs_get_integer_imm_xIIfId 464
#define op_count_i_bs_get_integer_small_imm_xIfId 465
#define op_count_i_bs_get_utf16_xfId 466
#define op_count_i_bs_get_utf8_xfd 467
#define op_count_i_bs_init_IId 468
#define op_count_i_bs_init_bits_IId 469
#define op_count_i_bs_init_bits_fail_xjId 470
#define op_count_i_bs_init_bits_fail_yjId 471
#define op_count_i_bs_init_bits_fail_heap_sIjId 472
#define op_count_i_bs_init_bits_heap_IIId 473
#define op_count_i_bs_init_fail_xjId 474
#define op_count_i_bs_init_fail_yjId 475
#define op_count_i_bs_init_fail_heap_sIjId 476
#define op_count_i_bs_init_heap_IIId 477
#define op_count_i_bs_init_heap_bin_IId 478
#define op_count_i_bs_init_heap_bin_heap_IIId 479
#define op_count_i_bs_match_string_xfII 480
#define op_count_i_bs_private_append_jIssd 481
#define op_count_i_bs_put_utf8_js 482
#define op_count_i_bs_restore2_xI 483
#define op_count_i_bs_save2_xI 484
#define op_count_i_bs_skip_bits2_fxxI 485
#define op_count_i_bs_skip_bits2_fxyI 486
#define op_count_i_bs_skip_bits_all2_fxI 487
#define op_count_i_bs_skip_bits_imm2_fxI 488
#define op_count_i_bs_start_match2_xfIId 489
#define op_count_i_bs_start_match2_yfIId 490
#define op_count_i_bs_utf16_size_sd 491
#define op_count_i_bs_utf8_size_sd 492
#define op_count_i_bs_validate_unicode_js 493
#define op_count_i_bs_validate_unicode_retract_jss 494
#define op_count_i_bsl_jIssd 495
#define op_count_i_bsr_jIssd 496
#define op_count_i_bxor_jIssd 497
#define op_count_i_call_f 498
#define op_count_i_call_ext_e 499
#define op_count_i_call_ext_last_eP 500
#define op_count_i_call_ext_only_e 501
#define op_count_i_call_fun_I 502
#define op_count_i_call_fun_last_IP 503
#define op_count_i_call_last_fP 504
#define op_count_i_call_only_f 505
#define op_count_i_debug_breakpoint 506
#define op_count_i_element_jxsd 507
#define op_count_i_element_jysd 508
#define op_count_i_fadd_lll 509
#define op_count_i_fast_element_jxId 510
#define op_count_i_fast_element_jyId 511
#define op_count_i_fcheckerror 512
#define op_count_i_fdiv_lll 513
#define op_count_i_fmul_lll 514
#define op_count_i_fnegate_ll 515
#define op_count_i_fsub_lll 516
#define op_count_i_func_info_IaaI 517
#define op_count_i_gc_bif1_jIsId 518
#define op_count_i_gc_bif2_jIIssd 519
#define op_count_i_gc_bif3_jIIssd 520
#define op_count_i_generic_breakpoint 521
#define op_count_i_get_sd 522
#define op_count_i_get_hash_cId 523
#define op_count_i_get_map_element_fxxx 524
#define op_count_i_get_map_element_fxxy 525
#define op_count_i_get_map_element_fyxx 526
#define op_count_i_get_map_element_fyxy 527
#define op_count_i_get_map_element_hash_fxcIx 528
#define op_count_i_get_map_element_hash_fxcIy 529
#define op_count_i_get_map_element_hash_fycIx 530
#define op_count_i_get_map_element_hash_fycIy 531
#define op_count_i_get_map_elements_fsI 532
#define op_count_i_get_tuple_element_xPx 533
#define op_count_i_get_tuple_element_xPy 534
#define op_count_i_get_tuple_element_yPx 535
#define op_count_i_get_tuple_element_yPy 536
#define op_count_i_get_tuple_element2_xPx 537
#define op_count_i_get_tuple_element2y_xPyy 538
#define op_count_i_get_tuple_element3_xPx 539
#define op_count_i_hibernate 540
#define op_count_i_increment_rIId 541
#define op_count_i_increment_xIId 542
#define op_count_i_increment_yIId 543
#define op_count_i_int_bnot_jsId 544
#define op_count_i_int_div_jIssd 545
#define op_count_i_is_eq_exact_immed_frc 546
#define op_count_i_is_eq_exact_immed_fxc 547
#define op_count_i_is_eq_exact_immed_fyc 548
#define op_count_i_is_eq_exact_literal_fxc 549
#define op_count_i_is_eq_exact_literal_fyc 550
#define op_count_i_is_ne_exact_immed_fxc 551
#define op_count_i_is_ne_exact_immed_fyc 552
#define op_count_i_is_ne_exact_literal_fxc 553
#define op_count_i_is_ne_exact_literal_fyc 554
#define op_count_i_jump_on_val_xfII 555
#define op_count_i_jump_on_val_yfII 556
#define op_count_i_jump_on_val_zero_xfI 557
#define op_count_i_jump_on_val_zero_yfI 558
#define op_count_i_loop_rec_f 559
#define op_count_i_m_div_jIssd 560
#define op_count_i_make_fun_It 561
#define op_count_i_minus_jIxxd 562
#define op_count_i_minus_jIssd 563
#define op_count_i_move_call_cf 564
#define op_count_i_move_call_ext_ce 565
#define op_count_i_move_call_ext_last_ePc 566
#define op_count_i_move_call_ext_only_ec 567
#define op_count_i_move_call_last_fPc 568
#define op_count_i_move_call_only_fc 569
#define op_count_i_new_bs_put_binary_jsIs 570
#define op_count_i_new_bs_put_binary_all_jsI 571
#define op_count_i_new_bs_put_binary_imm_jIs 572
#define op_count_i_new_bs_put_float_jsIs 573
#define op_count_i_new_bs_put_float_imm_jIIs 574
#define op_count_i_new_bs_put_integer_jsIs 575
#define op_count_i_new_bs_put_integer_imm_jIIs 576
#define op_count_i_perf_counter 577
#define op_count_i_plus_jIxxd 578
#define op_count_i_plus_jIxyd 579
#define op_count_i_plus_jIssd 580
#define op_count_i_put_tuple_xI 581
#define op_count_i_put_tuple_yI 582
#define op_count_i_raise 583
#define op_count_i_recv_set 584
#define op_count_i_rem_jIxxd 585
#define op_count_i_rem_jIssd 586
#define op_count_i_return_time_trace 587
#define op_count_i_return_to_trace 588
#define op_count_i_select_tuple_arity_xfI 589
#define op_count_i_select_tuple_arity_yfI 590
#define op_count_i_select_tuple_arity2_xfAAff 591
#define op_count_i_select_tuple_arity2_yfAAff 592
#define op_count_i_select_val2_xfccff 593
#define op_count_i_select_val2_yfccff 594
#define op_count_i_select_val_bins_xfI 595
#define op_count_i_select_val_bins_yfI 596
#define op_count_i_select_val_lins_xfI 597
#define op_count_i_select_val_lins_yfI 598
#define op_count_i_times_jIssd 599
#define op_count_i_trim_I 600
#define op_count_i_wait_error 601
#define op_count_i_wait_error_locked 602
#define op_count_i_wait_timeout_fI 603
#define op_count_i_wait_timeout_fs 604
#define op_count_i_wait_timeout_locked_fI 605
#define op_count_i_wait_timeout_locked_fs 606
#define op_count_i_yield 607
#define op_count_if_end 608
#define op_count_init_y 609
#define op_count_init2_yy 610
#define op_count_init3_yyy 611
#define op_count_int_code_end 612
#define op_count_is_atom_fx 613
#define op_count_is_atom_fy 614
#define op_count_is_binary_fx 615
#define op_count_is_binary_fy 616
#define op_count_is_bitstring_fx 617
#define op_count_is_bitstring_fy 618
#define op_count_is_boolean_fx 619
#define op_count_is_boolean_fy 620
#define op_count_is_eq_fss 621
#define op_count_is_eq_exact_fxx 622
#define op_count_is_eq_exact_fxy 623
#define op_count_is_eq_exact_fss 624
#define op_count_is_float_fx 625
#define op_count_is_float_fy 626
#define op_count_is_function_fx 627
#define op_count_is_function_fy 628
#define op_count_is_function2_fss 629
#define op_count_is_ge_fxx 630
#define op_count_is_ge_fxc 631
#define op_count_is_ge_fcx 632
#define op_count_is_ge_fss 633
#define op_count_is_integer_fx 634
#define op_count_is_integer_fy 635
#define op_count_is_integer_allocate_fxII 636
#define op_count_is_list_fx 637
#define op_count_is_list_fy 638
#define op_count_is_lt_fxx 639
#define op_count_is_lt_fxc 640
#define op_count_is_lt_fcx 641
#define op_count_is_lt_fss 642
#define op_count_is_map_fx 643
#define op_count_is_map_fy 644
#define op_count_is_ne_fss 645
#define op_count_is_ne_exact_fss 646
#define op_count_is_nil_fx 647
#define op_count_is_nil_fy 648
#define op_count_is_non_empty_list_test_heap_fIt 649
#define op_count_is_nonempty_list_fx 650
#define op_count_is_nonempty_list_fy 651
#define op_count_is_nonempty_list_allocate_frIt 652
#define op_count_is_nonempty_list_allocate_fxIt 653
#define op_count_is_nonempty_list_get_list_frxx 654
#define op_count_is_nonempty_list_get_list_fxxx 655
#define op_count_is_number_fx 656
#define op_count_is_number_fy 657
#define op_count_is_pid_fx 658
#define op_count_is_pid_fy 659
#define op_count_is_port_fx 660
#define op_count_is_port_fy 661
#define op_count_is_reference_fx 662
#define op_count_is_reference_fy 663
#define op_count_is_tuple_fr 664
#define op_count_is_tuple_fx 665
#define op_count_is_tuple_fy 666
#define op_count_is_tuple_of_arity_frA 667
#define op_count_is_tuple_of_arity_fxA 668
#define op_count_is_tuple_of_arity_fyA 669
#define op_count_jump_f 670
#define op_count_label_L 671
#define op_count_line_I 672
#define op_count_loop_rec_end_f 673
#define op_count_move_nx 674
#define op_count_move_rx 675
#define op_count_move_ry 676
#define op_count_move_xr 677
#define op_count_move_xx 678
#define op_count_move_xy 679
#define op_count_move_yr 680
#define op_count_move_yx 681
#define op_count_move_yy 682
#define op_count_move_cr 683
#define op_count_move_cx 684
#define op_count_move2_par_xxxx 685
#define op_count_move2_par_xxxy 686
#define op_count_move2_par_xxyx 687
#define op_count_move2_par_xyxy 688
#define op_count_move2_par_yxxx 689
#define op_count_move2_par_yxxy 690
#define op_count_move2_par_yxyx 691
#define op_count_move3_xxxxxx 692
#define op_count_move3_xyxyxy 693
#define op_count_move3_yxyxyx 694
#define op_count_move_call_xf 695
#define op_count_move_call_yf 696
#define op_count_move_call_last_xfQ 697
#define op_count_move_call_last_yfQ 698
#define op_count_move_call_only_xf 699
#define op_count_move_deallocate_return_nQ 700
#define op_count_move_deallocate_return_xQ 701
#define op_count_move_deallocate_return_yQ 702
#define op_count_move_deallocate_return_cQ 703
#define op_count_move_dup_xxx 704
#define op_count_move_dup_xxy 705
#define op_count_move_dup_yxx 706
#define op_count_move_dup_yxy 707
#define op_count_move_jump_fn 708
#define op_count_move_jump_fx 709
#define op_count_move_jump_fy 710
#define op_count_move_jump_fc 711
#define op_count_move_return_n 712
#define op_count_move_return_x 713
#define op_count_move_return_c 714
#define op_count_move_shift_xxx 715
#define op_count_move_shift_xxy 716
#define op_count_move_shift_xyx 717
#define op_count_move_shift_yxx 718
#define op_count_move_window3_xxxy 719
#define op_count_move_window4_xxxxy 720
#define op_count_move_window5_xxxxxy 721
#define op_count_move_x1_c 722
#define op_count_move_x2_c 723
#define op_count_new_map_dII 724
#define op_count_node_x 725
#define op_count_node_y 726
#define op_count_normal_exit 727
#define op_count_on_load 728
#define op_count_put_list_rnr 729
#define op_count_put_list_rnx 730
#define op_count_put_list_rxr 731
#define op_count_put_list_rxx 732
#define op_count_put_list_xnx 733
#define op_count_put_list_xrr 734
#define op_count_put_list_xxr 735
#define op_count_put_list_xxx 736
#define op_count_put_list_xyx 737
#define op_count_put_list_ynx 738
#define op_count_put_list_yrr 739
#define op_count_put_list_yxx 740
#define op_count_put_list_yyx 741
#define op_count_put_list_xcx 742
#define op_count_put_list_xcy 743
#define op_count_put_list_ycx 744
#define op_count_put_list_cxx 745
#define op_count_put_list_cyx 746
#define op_count_put_list_ssd 747
#define op_count_recv_mark_f 748
#define op_count_remove_message 749
#define op_count_return 750
#define op_count_return_trace 751
#define op_count_self_x 752
#define op_count_self_y 753
#define op_count_send 754
#define op_count_set_tuple_element_sdP 755
#define op_count_swap_xx 756
#define op_count_swap_xy 757
#define op_count_swap_temp_xxx 758
#define op_count_swap_temp_xyx 759
#define op_count_system_limit_j 760
#define op_count_test_arity_fxA 761
#define op_count_test_arity_fyA 762
#define op_count_test_heap_It 763
#define op_count_test_heap_1_put_list_Iy 764
#define op_count_timeout 765
#define op_count_timeout_locked 766
#define op_count_try_case_end_s 767
#define op_count_try_end_y 768
#define op_count_update_map_assoc_jsdII 769
#define op_count_update_map_exact_jsdII 770
#define op_count_wait_f 771
#define op_count_wait_locked_f 772
#define op_count_wait_unlocked_f 773

#define DEFINE_OPCODES \
&&lb_allocate_tt, \
&&lb_allocate_heap_tIt, \
&&lb_allocate_heap_zero_tIt, \
&&lb_allocate_init_tIy, \
&&lb_allocate_zero_tt, \
&&lb_apply_I, \
&&lb_apply_bif, \
&&lb_apply_last_IP, \
&&lb_badarg_j, \
&&lb_badmatch_x, \
&&lb_bif1_fbsd, \
&&lb_bif1_body_bsd, \
&&lb_bs_add_jssId, \
&&lb_bs_context_to_binary_x, \
&&lb_bs_init_writable, \
&&lb_bs_put_string_II, \
&&lb_bs_put_utf16_jIs, \
&&lb_bs_test_tail_imm2_fxI, \
&&lb_bs_test_unit_fxI, \
&&lb_bs_test_unit8_fx, \
&&lb_bs_test_zero_tail2_fx, \
&&lb_call_bif_e, \
&&lb_call_error_handler, \
&&lb_call_nif, \
&&lb_case_end_x, \
&&lb_catch_yf, \
&&lb_catch_end_y, \
&&lb_continue_exit, \
&&lb_deallocate_I, \
&&lb_deallocate_return_Q, \
&&lb_error_action_code, \
&&lb_fclearerror, \
&&lb_fconv_dl, \
&&lb_fmove_ql, \
&&lb_fmove_ld, \
&&lb_fmove_dl, \
&&lb_get_list_rry, \
&&lb_get_list_rxr, \
&&lb_get_list_rxx, \
&&lb_get_list_rxy, \
&&lb_get_list_ryr, \
&&lb_get_list_xrx, \
&&lb_get_list_xxx, \
&&lb_get_list_xxy, \
&&lb_get_list_xyx, \
&&lb_get_list_xyy, \
&&lb_get_list_yxx, \
&&lb_get_list_yxy, \
&&lb_get_list_yyx, \
&&lb_get_list_yyy, \
&&lb_hipe_call_count, \
&&lb_hipe_trap_call, \
&&lb_hipe_trap_call_closure, \
&&lb_hipe_trap_resume, \
&&lb_hipe_trap_return, \
&&lb_hipe_trap_throw, \
&&lb_i_apply, \
&&lb_i_apply_fun, \
&&lb_i_apply_fun_last_P, \
&&lb_i_apply_fun_only, \
&&lb_i_apply_last_P, \
&&lb_i_apply_only, \
&&lb_i_band_jIxcd, \
&&lb_i_band_jIssd, \
&&lb_i_bif2_fbssd, \
&&lb_i_bif2_body_bssd, \
&&lb_i_bor_jIssd, \
&&lb_i_bs_append_jIIIsd, \
&&lb_i_bs_get_binary2_fxIsId, \
&&lb_i_bs_get_binary_all2_fxIId, \
&&lb_i_bs_get_binary_all_reuse_xfI, \
&&lb_i_bs_get_binary_imm2_fxIIId, \
&&lb_i_bs_get_float2_fxIsId, \
&&lb_i_bs_get_integer_fIIssd, \
&&lb_i_bs_get_integer_16_xfd, \
&&lb_i_bs_get_integer_32_xfId, \
&&lb_i_bs_get_integer_8_xfd, \
&&lb_i_bs_get_integer_imm_xIIfId, \
&&lb_i_bs_get_integer_small_imm_xIfId, \
&&lb_i_bs_get_utf16_xfId, \
&&lb_i_bs_get_utf8_xfd, \
&&lb_i_bs_init_IId, \
&&lb_i_bs_init_bits_IId, \
&&lb_i_bs_init_bits_fail_xjId, \
&&lb_i_bs_init_bits_fail_yjId, \
&&lb_i_bs_init_bits_fail_heap_sIjId, \
&&lb_i_bs_init_bits_heap_IIId, \
&&lb_i_bs_init_fail_xjId, \
&&lb_i_bs_init_fail_yjId, \
&&lb_i_bs_init_fail_heap_sIjId, \
&&lb_i_bs_init_heap_IIId, \
&&lb_i_bs_init_heap_bin_IId, \
&&lb_i_bs_init_heap_bin_heap_IIId, \
&&lb_i_bs_match_string_xfII, \
&&lb_i_bs_private_append_jIssd, \
&&lb_i_bs_put_utf8_js, \
&&lb_i_bs_restore2_xI, \
&&lb_i_bs_save2_xI, \
&&lb_i_bs_skip_bits2_fxxI, \
&&lb_i_bs_skip_bits2_fxyI, \
&&lb_i_bs_skip_bits_all2_fxI, \
&&lb_i_bs_skip_bits_imm2_fxI, \
&&lb_i_bs_start_match2_xfIId, \
&&lb_i_bs_start_match2_yfIId, \
&&lb_i_bs_utf16_size_sd, \
&&lb_i_bs_utf8_size_sd, \
&&lb_i_bs_validate_unicode_js, \
&&lb_i_bs_validate_unicode_retract_jss, \
&&lb_i_bsl_jIssd, \
&&lb_i_bsr_jIssd, \
&&lb_i_bxor_jIssd, \
&&lb_i_call_f, \
&&lb_i_call_ext_e, \
&&lb_i_call_ext_last_eP, \
&&lb_i_call_ext_only_e, \
&&lb_i_call_fun_I, \
&&lb_i_call_fun_last_IP, \
&&lb_i_call_last_fP, \
&&lb_i_call_only_f, \
&&lb_i_debug_breakpoint, \
&&lb_i_element_jxsd, \
&&lb_i_element_jysd, \
&&lb_i_fadd_lll, \
&&lb_i_fast_element_jxId, \
&&lb_i_fast_element_jyId, \
&&lb_i_fcheckerror, \
&&lb_i_fdiv_lll, \
&&lb_i_fmul_lll, \
&&lb_i_fnegate_ll, \
&&lb_i_fsub_lll, \
&&lb_i_func_info_IaaI, \
&&lb_i_gc_bif1_jIsId, \
&&lb_i_gc_bif2_jIIssd, \
&&lb_i_gc_bif3_jIIssd, \
&&lb_i_generic_breakpoint, \
&&lb_i_get_sd, \
&&lb_i_get_hash_cId, \
&&lb_i_get_map_element_fxxx, \
&&lb_i_get_map_element_fxxy, \
&&lb_i_get_map_element_fyxx, \
&&lb_i_get_map_element_fyxy, \
&&lb_i_get_map_element_hash_fxcIx, \
&&lb_i_get_map_element_hash_fxcIy, \
&&lb_i_get_map_element_hash_fycIx, \
&&lb_i_get_map_element_hash_fycIy, \
&&lb_i_get_map_elements_fsI, \
&&lb_i_get_tuple_element_xPx, \
&&lb_i_get_tuple_element_xPy, \
&&lb_i_get_tuple_element_yPx, \
&&lb_i_get_tuple_element_yPy, \
&&lb_i_get_tuple_element2_xPx, \
&&lb_i_get_tuple_element2y_xPyy, \
&&lb_i_get_tuple_element3_xPx, \
&&lb_i_hibernate, \
&&lb_i_increment_rIId, \
&&lb_i_increment_xIId, \
&&lb_i_increment_yIId, \
&&lb_i_int_bnot_jsId, \
&&lb_i_int_div_jIssd, \
&&lb_i_is_eq_exact_immed_frc, \
&&lb_i_is_eq_exact_immed_fxc, \
&&lb_i_is_eq_exact_immed_fyc, \
&&lb_i_is_eq_exact_literal_fxc, \
&&lb_i_is_eq_exact_literal_fyc, \
&&lb_i_is_ne_exact_immed_fxc, \
&&lb_i_is_ne_exact_immed_fyc, \
&&lb_i_is_ne_exact_literal_fxc, \
&&lb_i_is_ne_exact_literal_fyc, \
&&lb_i_jump_on_val_xfII, \
&&lb_i_jump_on_val_yfII, \
&&lb_i_jump_on_val_zero_xfI, \
&&lb_i_jump_on_val_zero_yfI, \
&&lb_i_loop_rec_f, \
&&lb_i_m_div_jIssd, \
&&lb_i_make_fun_It, \
&&lb_i_minus_jIxxd, \
&&lb_i_minus_jIssd, \
&&lb_i_move_call_cf, \
&&lb_i_move_call_ext_ce, \
&&lb_i_move_call_ext_last_ePc, \
&&lb_i_move_call_ext_only_ec, \
&&lb_i_move_call_last_fPc, \
&&lb_i_move_call_only_fc, \
&&lb_i_new_bs_put_binary_jsIs, \
&&lb_i_new_bs_put_binary_all_jsI, \
&&lb_i_new_bs_put_binary_imm_jIs, \
&&lb_i_new_bs_put_float_jsIs, \
&&lb_i_new_bs_put_float_imm_jIIs, \
&&lb_i_new_bs_put_integer_jsIs, \
&&lb_i_new_bs_put_integer_imm_jIIs, \
&&lb_i_perf_counter, \
&&lb_i_plus_jIxxd, \
&&lb_i_plus_jIxyd, \
&&lb_i_plus_jIssd, \
&&lb_i_put_tuple_xI, \
&&lb_i_put_tuple_yI, \
&&lb_i_raise, \
&&lb_i_recv_set, \
&&lb_i_rem_jIxxd, \
&&lb_i_rem_jIssd, \
&&lb_i_return_time_trace, \
&&lb_i_return_to_trace, \
&&lb_i_select_tuple_arity_xfI, \
&&lb_i_select_tuple_arity_yfI, \
&&lb_i_select_tuple_arity2_xfAAff, \
&&lb_i_select_tuple_arity2_yfAAff, \
&&lb_i_select_val2_xfccff, \
&&lb_i_select_val2_yfccff, \
&&lb_i_select_val_bins_xfI, \
&&lb_i_select_val_bins_yfI, \
&&lb_i_select_val_lins_xfI, \
&&lb_i_select_val_lins_yfI, \
&&lb_i_times_jIssd, \
&&lb_i_trim_I, \
&&lb_i_wait_error, \
&&lb_i_wait_error_locked, \
&&lb_i_wait_timeout_fI, \
&&lb_i_wait_timeout_fs, \
&&lb_i_wait_timeout_locked_fI, \
&&lb_i_wait_timeout_locked_fs, \
&&lb_i_yield, \
&&lb_if_end, \
&&lb_init_y, \
&&lb_init2_yy, \
&&lb_init3_yyy, \
&&lb_int_code_end, \
&&lb_is_atom_fx, \
&&lb_is_atom_fy, \
&&lb_is_binary_fx, \
&&lb_is_binary_fy, \
&&lb_is_bitstring_fx, \
&&lb_is_bitstring_fy, \
&&lb_is_boolean_fx, \
&&lb_is_boolean_fy, \
&&lb_is_eq_fss, \
&&lb_is_eq_exact_fxx, \
&&lb_is_eq_exact_fxy, \
&&lb_is_eq_exact_fss, \
&&lb_is_float_fx, \
&&lb_is_float_fy, \
&&lb_is_function_fx, \
&&lb_is_function_fy, \
&&lb_is_function2_fss, \
&&lb_is_ge_fxx, \
&&lb_is_ge_fxc, \
&&lb_is_ge_fcx, \
&&lb_is_ge_fss, \
&&lb_is_integer_fx, \
&&lb_is_integer_fy, \
&&lb_is_integer_allocate_fxII, \
&&lb_is_list_fx, \
&&lb_is_list_fy, \
&&lb_is_lt_fxx, \
&&lb_is_lt_fxc, \
&&lb_is_lt_fcx, \
&&lb_is_lt_fss, \
&&lb_is_map_fx, \
&&lb_is_map_fy, \
&&lb_is_ne_fss, \
&&lb_is_ne_exact_fss, \
&&lb_is_nil_fx, \
&&lb_is_nil_fy, \
&&lb_is_non_empty_list_test_heap_fIt, \
&&lb_is_nonempty_list_fx, \
&&lb_is_nonempty_list_fy, \
&&lb_is_nonempty_list_allocate_frIt, \
&&lb_is_nonempty_list_allocate_fxIt, \
&&lb_is_nonempty_list_get_list_frxx, \
&&lb_is_nonempty_list_get_list_fxxx, \
&&lb_is_number_fx, \
&&lb_is_number_fy, \
&&lb_is_pid_fx, \
&&lb_is_pid_fy, \
&&lb_is_port_fx, \
&&lb_is_port_fy, \
&&lb_is_reference_fx, \
&&lb_is_reference_fy, \
&&lb_is_tuple_fr, \
&&lb_is_tuple_fx, \
&&lb_is_tuple_fy, \
&&lb_is_tuple_of_arity_frA, \
&&lb_is_tuple_of_arity_fxA, \
&&lb_is_tuple_of_arity_fyA, \
&&lb_jump_f, \
&&lb_label_L, \
&&lb_line_I, \
&&lb_loop_rec_end_f, \
&&lb_move_nx, \
&&lb_move_rx, \
&&lb_move_ry, \
&&lb_move_xr, \
&&lb_move_xx, \
&&lb_move_xy, \
&&lb_move_yr, \
&&lb_move_yx, \
&&lb_move_yy, \
&&lb_move_cr, \
&&lb_move_cx, \
&&lb_move2_par_xxxx, \
&&lb_move2_par_xxxy, \
&&lb_move2_par_xxyx, \
&&lb_move2_par_xyxy, \
&&lb_move2_par_yxxx, \
&&lb_move2_par_yxxy, \
&&lb_move2_par_yxyx, \
&&lb_move3_xxxxxx, \
&&lb_move3_xyxyxy, \
&&lb_move3_yxyxyx, \
&&lb_move_call_xf, \
&&lb_move_call_yf, \
&&lb_move_call_last_xfQ, \
&&lb_move_call_last_yfQ, \
&&lb_move_call_only_xf, \
&&lb_move_deallocate_return_nQ, \
&&lb_move_deallocate_return_xQ, \
&&lb_move_deallocate_return_yQ, \
&&lb_move_deallocate_return_cQ, \
&&lb_move_dup_xxx, \
&&lb_move_dup_xxy, \
&&lb_move_dup_yxx, \
&&lb_move_dup_yxy, \
&&lb_move_jump_fn, \
&&lb_move_jump_fx, \
&&lb_move_jump_fy, \
&&lb_move_jump_fc, \
&&lb_move_return_n, \
&&lb_move_return_x, \
&&lb_move_return_c, \
&&lb_move_shift_xxx, \
&&lb_move_shift_xxy, \
&&lb_move_shift_xyx, \
&&lb_move_shift_yxx, \
&&lb_move_window3_xxxy, \
&&lb_move_window4_xxxxy, \
&&lb_move_window5_xxxxxy, \
&&lb_move_x1_c, \
&&lb_move_x2_c, \
&&lb_new_map_dII, \
&&lb_node_x, \
&&lb_node_y, \
&&lb_normal_exit, \
&&lb_on_load, \
&&lb_put_list_rnr, \
&&lb_put_list_rnx, \
&&lb_put_list_rxr, \
&&lb_put_list_rxx, \
&&lb_put_list_xnx, \
&&lb_put_list_xrr, \
&&lb_put_list_xxr, \
&&lb_put_list_xxx, \
&&lb_put_list_xyx, \
&&lb_put_list_ynx, \
&&lb_put_list_yrr, \
&&lb_put_list_yxx, \
&&lb_put_list_yyx, \
&&lb_put_list_xcx, \
&&lb_put_list_xcy, \
&&lb_put_list_ycx, \
&&lb_put_list_cxx, \
&&lb_put_list_cyx, \
&&lb_put_list_ssd, \
&&lb_recv_mark_f, \
&&lb_remove_message, \
&&lb_return, \
&&lb_return_trace, \
&&lb_self_x, \
&&lb_self_y, \
&&lb_send, \
&&lb_set_tuple_element_sdP, \
&&lb_swap_xx, \
&&lb_swap_xy, \
&&lb_swap_temp_xxx, \
&&lb_swap_temp_xyx, \
&&lb_system_limit_j, \
&&lb_test_arity_fxA, \
&&lb_test_arity_fyA, \
&&lb_test_heap_It, \
&&lb_test_heap_1_put_list_Iy, \
&&lb_timeout, \
&&lb_timeout_locked, \
&&lb_try_case_end_s, \
&&lb_try_end_y, \
&&lb_update_map_assoc_jsdII, \
&&lb_update_map_exact_jsdII, \
&&lb_wait_f, \
&&lb_wait_locked_f, \
&&lb_wait_unlocked_f,

#define DEFINE_COUNTING_OPCODES \
&&lb_count_allocate_tt, \
&&lb_count_allocate_heap_tIt, \
&&lb_count_allocate_heap_zero_tIt, \
&&lb_count_allocate_init_tIy, \
&&lb_count_allocate_zero_tt, \
&&lb_count_apply_I, \
&&lb_count_apply_bif, \
&&lb_count_apply_last_IP, \
&&lb_count_badarg_j, \
&&lb_count_badmatch_x, \
&&lb_count_bif1_fbsd, \
&&lb_count_bif1_body_bsd, \
&&lb_count_bs_add_jssId, \
&&lb_count_bs_context_to_binary_x, \
&&lb_count_bs_init_writable, \
&&lb_count_bs_put_string_II, \
&&lb_count_bs_put_utf16_jIs, \
&&lb_count_bs_test_tail_imm2_fxI, \
&&lb_count_bs_test_unit_fxI, \
&&lb_count_bs_test_unit8_fx, \
&&lb_count_bs_test_zero_tail2_fx, \
&&lb_count_call_bif_e, \
&&lb_count_call_error_handler, \
&&lb_count_call_nif, \
&&lb_count_case_end_x, \
&&lb_count_catch_yf, \
&&lb_count_catch_end_y, \
&&lb_count_continue_exit, \
&&lb_count_deallocate_I, \
&&lb_count_deallocate_return_Q, \
&&lb_count_error_action_code, \
&&lb_count_fclearerror, \
&&lb_count_fconv_dl, \
&&lb_count_fmove_ql, \
&&lb_count_fmove_ld, \
&&lb_count_fmove_dl, \
&&lb_count_get_list_rry, \
&&lb_count_get_list_rxr, \
&&lb_count_get_list_rxx, \
&&lb_count_get_list_rxy, \
&&lb_count_get_list_ryr, \
&&lb_count_get_list_xrx, \
&&lb_count_get_list_xxx, \
&&lb_count_get_list_xxy, \
&&lb_count_get_list_xyx, \
&&lb_count_get_list_xyy, \
&&lb_count_get_list_yxx, \
&&lb_count_get_list_yxy, \
&&lb_count_get_list_yyx, \
&&lb_count_get_list_yyy, \
&&lb_count_hipe_call_count, \
&&lb_count_hipe_trap_call, \
&&lb_count_hipe_trap_call_closure, \
&&lb_count_hipe_trap_resume, \
&&lb_count_hipe_trap_return, \
&&lb_count_hipe_trap_throw, \
&&lb_count_i_apply, \
&&lb_count_i_apply_fun, \
&&lb_count_i_apply_fun_last_P, \
&&lb_count_i_apply_fun_only, \
&&lb_count_i_apply_last_P, \
&&lb_count_i_apply_only, \
&&lb_count_i_band_jIxcd, \
&&lb_count_i_band_jIssd, \
&&lb_count_i_bif2_fbssd, \
&&lb_count_i_bif2_body_bssd, \
&&lb_count_i_bor_jIssd, \
&&lb_count_i_bs_append_jIIIsd, \
&&lb_count_i_bs_get_binary2_fxIsId, \
&&lb_count_i_bs_get_binary_all2_fxIId, \
&&lb_count_i_bs_get_binary_all_reuse_xfI, \
&&lb_count_i_bs_get_binary_imm2_fxIIId, \
&&lb_count_i_bs_get_float2_fxIsId, \
&&lb_count_i_bs_get_integer_fIIssd, \
&&lb_count_i_bs_get_integer_16_xfd, \
&&lb_count_i_bs_get_integer_32_xfId, \
&&lb_count_i_bs_get_integer_8_xfd, \
&&lb_count_i_bs_get_integer_imm_xIIfId, \
&&lb_count_i_bs_get_integer_small_imm_xIfId, \
&&lb_count_i_bs_get_utf16_xfId, \
&&lb_count_i_bs_get_utf8_xfd, \
&&lb_count_i_bs_init_IId, \
&&lb_count_i_bs_init_bits_IId, \
&&lb_count_i_bs_init_bits_fail_xjId, \
&&lb_count_i_bs_init_bits_fail_yjId, \
&&lb_count_i_bs_init_bits_fail_heap_sIjId, \
&&lb_count_i_bs_init_bits_heap_IIId, \
&&lb_count_i_bs_init_fail_xjId, \
&&lb_count_i_bs_init_fail_yjId, \
&&lb_count_i_bs_init_fail_heap_sIjId, \
&&lb_count_i_bs_init_heap_IIId, \
&&lb_count_i_bs_init_heap_bin_IId, \
&&lb_count_i_bs_init_heap_bin_heap_IIId, \
&&lb_count_i_bs_match_string_xfII, \
&&lb_count_i_bs_private_append_jIssd, \
&&lb_count_i_bs_put_utf8_js, \
&&lb_count_i_bs_restore2_xI, \
&&lb_count_i_bs_save2_xI, \
&&lb_count_i_bs_skip_bits2_fxxI, \
&&lb_count_i_bs_skip_bits2_fxyI, \
&&lb_count_i_bs_skip_bits_all2_fxI, \
&&lb_count_i_bs_skip_bits_imm2_fxI, \
&&lb_count_i_bs_start_match2_xfIId, \
&&lb_count_i_bs_start_match2_yfIId, \
&&lb_count_i_bs_utf16_size_sd, \
&&lb_count_i_bs_utf8_size_sd, \
&&lb_count_i_bs_validate_unicode_js, \
&&lb_count_i_bs_validate_unicode_retract_jss, \
&&lb_count_i_bsl_jIssd, \
&&lb_count_i_bsr_jIssd, \
&&lb_count_i_bxor_jIssd, \
&&lb_count_i_call_f, \
&&lb_count_i_call_ext_e, \
&&lb_count_i_call_ext_last_eP, \
&&lb_count_i_call_ext_only_e, \
&&lb_count_i_call_fun_I, \
&&lb_count_i_call_fun_last_IP, \
&&lb_count_i_call_last_fP, \
&&lb_count_i_call_only_f, \
&&lb_count_i_debug_breakpoint, \
&&lb_count_i_element_jxsd, \
&&lb_count_i_element_jysd, \
&&lb_count_i_fadd_lll, \
&&lb_count_i_fast_element_jxId, \
&&lb_count_i_fast_element_jyId, \
&&lb_count_i_fcheckerror, \
&&lb_count_i_fdiv_lll, \
&&lb_count_i_fmul_lll, \
&&lb_count_i_fnegate_ll, \
&&lb_count_i_fsub_lll, \
&&lb_count_i_func_info_IaaI, \
&&lb_count_i_gc_bif1_jIsId, \
&&lb_count_i_gc_bif2_jIIssd, \
&&lb_count_i_gc_bif3_jIIssd, \
&&lb_count_i_generic_breakpoint, \
&&lb_count_i_get_sd, \
&&lb_count_i_get_hash_cId, \
&&lb_count_i_get_map_element_fxxx, \
&&lb_count_i_get_map_element_fxxy, \
&&lb_count_i_get_map_element_fyxx, \
&&lb_count_i_get_map_element_fyxy, \
&&lb_count_i_get_map_element_hash_fxcIx, \
&&lb_count_i_get_map_element_hash_fxcIy, \
&&lb_count_i_get_map_element_hash_fycIx, \
&&lb_count_i_get_map_element_hash_fycIy, \
&&lb_count_i_get_map_elements_fsI, \
&&lb_count_i_get_tuple_element_xPx, \
&&lb_count_i_get_tuple_element_xPy, \
&&lb_count_i_get_tuple_element_yPx, \
&&lb_count_i_get_tuple_element_yPy, \
&&lb_count_i_get_tuple_element2_xPx, \
&&lb_count_i_get_tuple_element2y_xPyy, \
&&lb_count_i_get_tuple_element3_xPx, \
&&lb_count_i_hibernate, \
&&lb_count_i_increment_rIId, \
&&lb_count_i_increment_xIId, \
&&lb_count_i_increment_yIId, \
&&lb_count_i_int_bnot_jsId, \
&&lb_count_i_int_div_jIssd, \
&&lb_count_i_is_eq_exact_immed_frc, \
&&lb_count_i_is_eq_exact_immed_fxc, \
&&lb_count_i_is_eq_exact_immed_fyc, \
&&lb_count_i_is_eq_exact_literal_fxc, \
&&lb_count_i_is_eq_exact_literal_fyc, \
&&lb_count_i_is_ne_exact_immed_fxc, \
&&lb_count_i_is_ne_exact_immed_fyc, \
&&lb_count_i_is_ne_exact_literal_fxc, \
&&lb_count_i_is_ne_exact_literal_fyc, \
&&lb_count_i_jump_on_val_xfII, \
&&lb_count_i_jump_on_val_yfII, \
&&lb_count_i_jump_on_val_zero_xfI, \
&&lb_count_i_jump_on_val_zero_yfI, \
&&lb_count_i_loop_rec_f, \
&&lb_count_i_m_div_jIssd, \
&&lb_count_i_make_fun_It, \
&&lb_count_i_minus_jIxxd, \
&&lb_count_i_minus_jIssd, \
&&lb_count_i_move_call_cf, \
&&lb_count_i_move_call_ext_ce, \
&&lb_count_i_move_call_ext_last_ePc, \
&&lb_count_i_move_call_ext_only_ec, \
&&lb_count_i_move_call_last_fPc, \
&&lb_count_i_move_call_only_fc, \
&&lb_count_i_new_bs_put_binary_jsIs, \
&&lb_count_i_new_bs_put_binary_all_jsI, \
&&lb_count_i_new_bs_put_binary_imm_jIs, \
&&lb_count_i_new_bs_put_float_jsIs, \
&&lb_count_i_new_bs_put_float_imm_jIIs, \
&&lb_count_i_new_bs_put_integer_jsIs, \
&&lb_count_i_new_bs_put_integer_imm_jIIs, \
&&lb_count_i_perf_counter, \
&&lb_count_i_plus_jIxxd, \
&&lb_count_i_plus_jIxyd, \
&&lb_count_i_plus_jIssd, \
&&lb_count_i_put_tuple_xI, \
&&lb_count_i_put_tuple_yI, \
&&lb_count_i_raise, \
&&lb_count_i_recv_set, \
&&lb_count_i_rem_jIxxd, \
&&lb_count_i_rem_jIssd, \
&&lb_count_i_return_time_trace, \
&&lb_count_i_return_to_trace, \
&&lb_count_i_select_tuple_arity_xfI, \
&&lb_count_i_select_tuple_arity_yfI, \
&&lb_count_i_select_tuple_arity2_xfAAff, \
&&lb_count_i_select_tuple_arity2_yfAAff, \
&&lb_count_i_select_val2_xfccff, \
&&lb_count_i_select_val2_yfccff, \
&&lb_count_i_select_val_bins_xfI, \
&&lb_count_i_select_val_bins_yfI, \
&&lb_count_i_select_val_lins_xfI, \
&&lb_count_i_select_val_lins_yfI, \
&&lb_count_i_times_jIssd, \
&&lb_count_i_trim_I, \
&&lb_count_i_wait_error, \
&&lb_count_i_wait_error_locked, \
&&lb_count_i_wait_timeout_fI, \
&&lb_count_i_wait_timeout_fs, \
&&lb_count_i_wait_timeout_locked_fI, \
&&lb_count_i_wait_timeout_locked_fs, \
&&lb_count_i_yield, \
&&lb_count_if_end, \
&&lb_count_init_y, \
&&lb_count_init2_yy, \
&&lb_count_init3_yyy, \
&&lb_count_int_code_end, \
&&lb_count_is_atom_fx, \
&&lb_count_is_atom_fy, \
&&lb_count_is_binary_fx, \
&&lb_count_is_binary_fy, \
&&lb_count_is_bitstring_fx, \
&&lb_count_is_bitstring_fy, \
&&lb_count_is_boolean_fx, \
&&lb_count_is_boolean_fy, \
&&lb_count_is_eq_fss, \
&&lb_count_is_eq_exact_fxx, \
&&lb_count_is_eq_exact_fxy, \
&&lb_count_is_eq_exact_fss, \
&&lb_count_is_float_fx, \
&&lb_count_is_float_fy, \
&&lb_count_is_function_fx, \
&&lb_count_is_function_fy, \
&&lb_count_is_function2_fss, \
&&lb_count_is_ge_fxx, \
&&lb_count_is_ge_fxc, \
&&lb_count_is_ge_fcx, \
&&lb_count_is_ge_fss, \
&&lb_count_is_integer_fx, \
&&lb_count_is_integer_fy, \
&&lb_count_is_integer_allocate_fxII, \
&&lb_count_is_list_fx, \
&&lb_count_is_list_fy, \
&&lb_count_is_lt_fxx, \
&&lb_count_is_lt_fxc, \
&&lb_count_is_lt_fcx, \
&&lb_count_is_lt_fss, \
&&lb_count_is_map_fx, \
&&lb_count_is_map_fy, \
&&lb_count_is_ne_fss, \
&&lb_count_is_ne_exact_fss, \
&&lb_count_is_nil_fx, \
&&lb_count_is_nil_fy, \
&&lb_count_is_non_empty_list_test_heap_fIt, \
&&lb_count_is_nonempty_list_fx, \
&&lb_count_is_nonempty_list_fy, \
&&lb_count_is_nonempty_list_allocate_frIt, \
&&lb_count_is_nonempty_list_allocate_fxIt, \
&&lb_count_is_nonempty_list_get_list_frxx, \
&&lb_count_is_nonempty_list_get_list_fxxx, \
&&lb_count_is_number_fx, \
&&lb_count_is_number_fy, \
&&lb_count_is_pid_fx, \
&&lb_count_is_pid_fy, \
&&lb_count_is_port_fx, \
&&lb_count_is_port_fy, \
&&lb_count_is_reference_fx, \
&&lb_count_is_reference_fy, \
&&lb_count_is_tuple_fr, \
&&lb_count_is_tuple_fx, \
&&lb_count_is_tuple_fy, \
&&lb_count_is_tuple_of_arity_frA, \
&&lb_count_is_tuple_of_arity_fxA, \
&&lb_count_is_tuple_of_arity_fyA, \
&&lb_count_jump_f, \
&&lb_count_label_L, \
&&lb_count_line_I, \
&&lb_count_loop_rec_end_f, \
&&lb_count_move_nx, \
&&lb_count_move_rx, \
&&lb_count_move_ry, \
&&lb_count_move_xr, \
&&lb_count_move_xx, \
&&lb_count_move_xy, \
&&lb_count_move_yr, \
&&lb_count_move_yx, \
&&lb_count_move_yy, \
&&lb_count_move_cr, \
&&lb_count_move_cx, \
&&lb_count_move2_par_xxxx, \
&&lb_count_move2_par_xxxy, \
&&lb_count_move2_par_xxyx, \
&&lb_count_move2_par_xyxy, \
&&lb_count_move2_par_yxxx, \
&&lb_count_move2_par_yxxy, \
&&lb_count_move2_par_yxyx, \
&&lb_count_move3_xxxxxx, \
&&lb_count_move3_xyxyxy, \
&&lb_count_move3_yxyxyx, \
&&lb_count_move_call_xf, \
&&lb_count_move_call_yf, \
&&lb_count_move_call_last_xfQ, \
&&lb_count_move_call_last_yfQ, \
&&lb_count_move_call_only_xf, \
&&lb_count_move_deallocate_return_nQ, \
&&lb_count_move_deallocate_return_xQ, \
&&lb_count_move_deallocate_return_yQ, \
&&lb_count_move_deallocate_return_cQ, \
&&lb_count_move_dup_xxx, \
&&lb_count_move_dup_xxy, \
&&lb_count_move_dup_yxx, \
&&lb_count_move_dup_yxy, \
&&lb_count_move_jump_fn, \
&&lb_count_move_jump_fx, \
&&lb_count_move_jump_fy, \
&&lb_count_move_jump_fc, \
&&lb_count_move_return_n, \
&&lb_count_move_return_x, \
&&lb_count_move_return_c, \
&&lb_count_move_shift_xxx, \
&&lb_count_move_shift_xxy, \
&&lb_count_move_shift_xyx, \
&&lb_count_move_shift_yxx, \
&&lb_count_move_window3_xxxy, \
&&lb_count_move_window4_xxxxy, \
&&lb_count_move_window5_xxxxxy, \
&&lb_count_move_x1_c, \
&&lb_count_move_x2_c, \
&&lb_count_new_map_dII, \
&&lb_count_node_x, \
&&lb_count_node_y, \
&&lb_count_normal_exit, \
&&lb_count_on_load, \
&&lb_count_put_list_rnr, \
&&lb_count_put_list_rnx, \
&&lb_count_put_list_rxr, \
&&lb_count_put_list_rxx, \
&&lb_count_put_list_xnx, \
&&lb_count_put_list_xrr, \
&&lb_count_put_list_xxr, \
&&lb_count_put_list_xxx, \
&&lb_count_put_list_xyx, \
&&lb_count_put_list_ynx, \
&&lb_count_put_list_yrr, \
&&lb_count_put_list_yxx, \
&&lb_count_put_list_yyx, \
&&lb_count_put_list_xcx, \
&&lb_count_put_list_xcy, \
&&lb_count_put_list_ycx, \
&&lb_count_put_list_cxx, \
&&lb_count_put_list_cyx, \
&&lb_count_put_list_ssd, \
&&lb_count_recv_mark_f, \
&&lb_count_remove_message, \
&&lb_count_return, \
&&lb_count_return_trace, \
&&lb_count_self_x, \
&&lb_count_self_y, \
&&lb_count_send, \
&&lb_count_set_tuple_element_sdP, \
&&lb_count_swap_xx, \
&&lb_count_swap_xy, \
&&lb_count_swap_temp_xxx, \
&&lb_count_swap_temp_xyx, \
&&lb_count_system_limit_j, \
&&lb_count_test_arity_fxA, \
&&lb_count_test_arity_fyA, \
&&lb_count_test_heap_It, \
&&lb_count_test_heap_1_put_list_Iy, \
&&lb_count_timeout, \
&&lb_count_timeout_locked, \
&&lb_count_try_case_end_s, \
&&lb_count_try_end_y, \
&&lb_count_update_map_assoc_jsdII, \
&&lb_count_update_map_exact_jsdII, \
&&lb_count_wait_f, \
&&lb_count_wait_locked_f, \
&&lb_count_wait_unlocked_f,

#define DEFINE_COUNTING_LABELS \
CountCase(allocate_tt): opc[0].count++; goto lb_allocate_tt; \
CountCase(allocate_heap_tIt): opc[1].count++; goto lb_allocate_heap_tIt; \
CountCase(allocate_heap_zero_tIt): opc[2].count++; goto lb_allocate_heap_zero_tIt; \
CountCase(allocate_init_tIy): opc[3].count++; goto lb_allocate_init_tIy; \
CountCase(allocate_zero_tt): opc[4].count++; goto lb_allocate_zero_tt; \
CountCase(apply_I): opc[5].count++; goto lb_apply_I; \
CountCase(apply_bif): opc[6].count++; goto lb_apply_bif; \
CountCase(apply_last_IP): opc[7].count++; goto lb_apply_last_IP; \
CountCase(badarg_j): opc[8].count++; goto lb_badarg_j; \
CountCase(badmatch_x): opc[9].count++; goto lb_badmatch_x; \
CountCase(bif1_fbsd): opc[10].count++; goto lb_bif1_fbsd; \
CountCase(bif1_body_bsd): opc[11].count++; goto lb_bif1_body_bsd; \
CountCase(bs_add_jssId): opc[12].count++; goto lb_bs_add_jssId; \
CountCase(bs_context_to_binary_x): opc[13].count++; goto lb_bs_context_to_binary_x; \
CountCase(bs_init_writable): opc[14].count++; goto lb_bs_init_writable; \
CountCase(bs_put_string_II): opc[15].count++; goto lb_bs_put_string_II; \
CountCase(bs_put_utf16_jIs): opc[16].count++; goto lb_bs_put_utf16_jIs; \
CountCase(bs_test_tail_imm2_fxI): opc[17].count++; goto lb_bs_test_tail_imm2_fxI; \
CountCase(bs_test_unit_fxI): opc[18].count++; goto lb_bs_test_unit_fxI; \
CountCase(bs_test_unit8_fx): opc[19].count++; goto lb_bs_test_unit8_fx; \
CountCase(bs_test_zero_tail2_fx): opc[20].count++; goto lb_bs_test_zero_tail2_fx; \
CountCase(call_bif_e): opc[21].count++; goto lb_call_bif_e; \
CountCase(call_error_handler): opc[22].count++; goto lb_call_error_handler; \
CountCase(call_nif): opc[23].count++; goto lb_call_nif; \
CountCase(case_end_x): opc[24].count++; goto lb_case_end_x; \
CountCase(catch_yf): opc[25].count++; goto lb_catch_yf; \
CountCase(catch_end_y): opc[26].count++; goto lb_catch_end_y; \
CountCase(continue_exit): opc[27].count++; goto lb_continue_exit; \
CountCase(deallocate_I): opc[28].count++; goto lb_deallocate_I; \
CountCase(deallocate_return_Q): opc[29].count++; goto lb_deallocate_return_Q; \
CountCase(error_action_code): opc[30].count++; goto lb_error_action_code; \
CountCase(fclearerror): opc[31].count++; goto lb_fclearerror; \
CountCase(fconv_dl): opc[32].count++; goto lb_fconv_dl; \
CountCase(fmove_ql): opc[33].count++; goto lb_fmove_ql; \
CountCase(fmove_ld): opc[34].count++; goto lb_fmove_ld; \
CountCase(fmove_dl): opc[35].count++; goto lb_fmove_dl; \
CountCase(get_list_rry): opc[36].count++; goto lb_get_list_rry; \
CountCase(get_list_rxr): opc[37].count++; goto lb_get_list_rxr; \
CountCase(get_list_rxx): opc[38].count++; goto lb_get_list_rxx; \
CountCase(get_list_rxy): opc[39].count++; goto lb_get_list_rxy; \
CountCase(get_list_ryr): opc[40].count++; goto lb_get_list_ryr; \
CountCase(get_list_xrx): opc[41].count++; goto lb_get_list_xrx; \
CountCase(get_list_xxx): opc[42].count++; goto lb_get_list_xxx; \
CountCase(get_list_xxy): opc[43].count++; goto lb_get_list_xxy; \
CountCase(get_list_xyx): opc[44].count++; goto lb_get_list_xyx; \
CountCase(get_list_xyy): opc[45].count++; goto lb_get_list_xyy; \
CountCase(get_list_yxx): opc[46].count++; goto lb_get_list_yxx; \
CountCase(get_list_yxy): opc[47].count++; goto lb_get_list_yxy; \
CountCase(get_list_yyx): opc[48].count++; goto lb_get_list_yyx; \
CountCase(get_list_yyy): opc[49].count++; goto lb_get_list_yyy; \
CountCase(hipe_call_count): opc[50].count++; goto lb_hipe_call_count; \
CountCase(hipe_trap_call): opc[51].count++; goto lb_hipe_trap_call; \
CountCase(hipe_trap_call_closure): opc[52].count++; goto lb_hipe_trap_call_closure; \
CountCase(hipe_trap_resume): opc[53].count++; goto lb_hipe_trap_resume; \
CountCase(hipe_trap_return): opc[54].count++; goto lb_hipe_trap_return; \
CountCase(hipe_trap_throw): opc[55].count++; goto lb_hipe_trap_throw; \
CountCase(i_apply): opc[56].count++; goto lb_i_apply; \
CountCase(i_apply_fun): opc[57].count++; goto lb_i_apply_fun; \
CountCase(i_apply_fun_last_P): opc[58].count++; goto lb_i_apply_fun_last_P; \
CountCase(i_apply_fun_only): opc[59].count++; goto lb_i_apply_fun_only; \
CountCase(i_apply_last_P): opc[60].count++; goto lb_i_apply_last_P; \
CountCase(i_apply_only): opc[61].count++; goto lb_i_apply_only; \
CountCase(i_band_jIxcd): opc[62].count++; goto lb_i_band_jIxcd; \
CountCase(i_band_jIssd): opc[63].count++; goto lb_i_band_jIssd; \
CountCase(i_bif2_fbssd): opc[64].count++; goto lb_i_bif2_fbssd; \
CountCase(i_bif2_body_bssd): opc[65].count++; goto lb_i_bif2_body_bssd; \
CountCase(i_bor_jIssd): opc[66].count++; goto lb_i_bor_jIssd; \
CountCase(i_bs_append_jIIIsd): opc[67].count++; goto lb_i_bs_append_jIIIsd; \
CountCase(i_bs_get_binary2_fxIsId): opc[68].count++; goto lb_i_bs_get_binary2_fxIsId; \
CountCase(i_bs_get_binary_all2_fxIId): opc[69].count++; goto lb_i_bs_get_binary_all2_fxIId; \
CountCase(i_bs_get_binary_all_reuse_xfI): opc[70].count++; goto lb_i_bs_get_binary_all_reuse_xfI; \
CountCase(i_bs_get_binary_imm2_fxIIId): opc[71].count++; goto lb_i_bs_get_binary_imm2_fxIIId; \
CountCase(i_bs_get_float2_fxIsId): opc[72].count++; goto lb_i_bs_get_float2_fxIsId; \
CountCase(i_bs_get_integer_fIIssd): opc[73].count++; goto lb_i_bs_get_integer_fIIssd; \
CountCase(i_bs_get_integer_16_xfd): opc[74].count++; goto lb_i_bs_get_integer_16_xfd; \
CountCase(i_bs_get_integer_32_xfId): opc[75].count++; goto lb_i_bs_get_integer_32_xfId; \
CountCase(i_bs_get_integer_8_xfd): opc[76].count++; goto lb_i_bs_get_integer_8_xfd; \
CountCase(i_bs_get_integer_imm_xIIfId): opc[77].count++; goto lb_i_bs_get_integer_imm_xIIfId; \
CountCase(i_bs_get_integer_small_imm_xIfId): opc[78].count++; goto lb_i_bs_get_integer_small_imm_xIfId; \
CountCase(i_bs_get_utf16_xfId): opc[79].count++; goto lb_i_bs_get_utf16_xfId; \
CountCase(i_bs_get_utf8_xfd): opc[80].count++; goto lb_i_bs_get_utf8_xfd; \
CountCase(i_bs_init_IId): opc[81].count++; goto lb_i_bs_init_IId; \
CountCase(i_bs_init_bits_IId): opc[82].count++; goto lb_i_bs_init_bits_IId; \
CountCase(i_bs_init_bits_fail_xjId): opc[83].count++; goto lb_i_bs_init_bits_fail_xjId; \
CountCase(i_bs_init_bits_fail_yjId): opc[84].count++; goto lb_i_bs_init_bits_fail_yjId; \
CountCase(i_bs_init_bits_fail_heap_sIjId): opc[85].count++; goto lb_i_bs_init_bits_fail_heap_sIjId; \
CountCase(i_bs_init_bits_heap_IIId): opc[86].count++; goto lb_i_bs_init_bits_heap_IIId; \
CountCase(i_bs_init_fail_xjId): opc[87].count++; goto lb_i_bs_init_fail_xjId; \
CountCase(i_bs_init_fail_yjId): opc[88].count++; goto lb_i_bs_init_fail_yjId; \
CountCase(i_bs_init_fail_heap_sIjId): opc[89].count++; goto lb_i_bs_init_fail_heap_sIjId; \
CountCase(i_bs_init_heap_IIId): opc[90].count++; goto lb_i_bs_init_heap_IIId; \
CountCase(i_bs_init_heap_bin_IId): opc[91].count++; goto lb_i_bs_init_heap_bin_IId; \
CountCase(i_bs_init_heap_bin_heap_IIId): opc[92].count++; goto lb_i_bs_init_heap_bin_heap_IIId; \
CountCase(i_bs_match_string_xfII): opc[93].count++; goto lb_i_bs_match_string_xfII; \
CountCase(i_bs_private_append_jIssd): opc[94].count++; goto lb_i_bs_private_append_jIssd; \
CountCase(i_bs_put_utf8_js): opc[95].count++; goto lb_i_bs_put_utf8_js; \
CountCase(i_bs_restore2_xI): opc[96].count++; goto lb_i_bs_restore2_xI; \
CountCase(i_bs_save2_xI): opc[97].count++; goto lb_i_bs_save2_xI; \
CountCase(i_bs_skip_bits2_fxxI): opc[98].count++; goto lb_i_bs_skip_bits2_fxxI; \
CountCase(i_bs_skip_bits2_fxyI): opc[99].count++; goto lb_i_bs_skip_bits2_fxyI; \
CountCase(i_bs_skip_bits_all2_fxI): opc[100].count++; goto lb_i_bs_skip_bits_all2_fxI; \
CountCase(i_bs_skip_bits_imm2_fxI): opc[101].count++; goto lb_i_bs_skip_bits_imm2_fxI; \
CountCase(i_bs_start_match2_xfIId): opc[102].count++; goto lb_i_bs_start_match2_xfIId; \
CountCase(i_bs_start_match2_yfIId): opc[103].count++; goto lb_i_bs_start_match2_yfIId; \
CountCase(i_bs_utf16_size_sd): opc[104].count++; goto lb_i_bs_utf16_size_sd; \
CountCase(i_bs_utf8_size_sd): opc[105].count++; goto lb_i_bs_utf8_size_sd; \
CountCase(i_bs_validate_unicode_js): opc[106].count++; goto lb_i_bs_validate_unicode_js; \
CountCase(i_bs_validate_unicode_retract_jss): opc[107].count++; goto lb_i_bs_validate_unicode_retract_jss; \
CountCase(i_bsl_jIssd): opc[108].count++; goto lb_i_bsl_jIssd; \
CountCase(i_bsr_jIssd): opc[109].count++; goto lb_i_bsr_jIssd; \
CountCase(i_bxor_jIssd): opc[110].count++; goto lb_i_bxor_jIssd; \
CountCase(i_call_f): opc[111].count++; goto lb_i_call_f; \
CountCase(i_call_ext_e): opc[112].count++; goto lb_i_call_ext_e; \
CountCase(i_call_ext_last_eP): opc[113].count++; goto lb_i_call_ext_last_eP; \
CountCase(i_call_ext_only_e): opc[114].count++; goto lb_i_call_ext_only_e; \
CountCase(i_call_fun_I): opc[115].count++; goto lb_i_call_fun_I; \
CountCase(i_call_fun_last_IP): opc[116].count++; goto lb_i_call_fun_last_IP; \
CountCase(i_call_last_fP): opc[117].count++; goto lb_i_call_last_fP; \
CountCase(i_call_only_f): opc[118].count++; goto lb_i_call_only_f; \
CountCase(i_debug_breakpoint): opc[119].count++; goto lb_i_debug_breakpoint; \
CountCase(i_element_jxsd): opc[120].count++; goto lb_i_element_jxsd; \
CountCase(i_element_jysd): opc[121].count++; goto lb_i_element_jysd; \
CountCase(i_fadd_lll): opc[122].count++; goto lb_i_fadd_lll; \
CountCase(i_fast_element_jxId): opc[123].count++; goto lb_i_fast_element_jxId; \
CountCase(i_fast_element_jyId): opc[124].count++; goto lb_i_fast_element_jyId; \
CountCase(i_fcheckerror): opc[125].count++; goto lb_i_fcheckerror; \
CountCase(i_fdiv_lll): opc[126].count++; goto lb_i_fdiv_lll; \
CountCase(i_fmul_lll): opc[127].count++; goto lb_i_fmul_lll; \
CountCase(i_fnegate_ll): opc[128].count++; goto lb_i_fnegate_ll; \
CountCase(i_fsub_lll): opc[129].count++; goto lb_i_fsub_lll; \
CountCase(i_func_info_IaaI): opc[130].count++; goto lb_i_func_info_IaaI; \
CountCase(i_gc_bif1_jIsId): opc[131].count++; goto lb_i_gc_bif1_jIsId; \
CountCase(i_gc_bif2_jIIssd): opc[132].count++; goto lb_i_gc_bif2_jIIssd; \
CountCase(i_gc_bif3_jIIssd): opc[133].count++; goto lb_i_gc_bif3_jIIssd; \
CountCase(i_generic_breakpoint): opc[134].count++; goto lb_i_generic_breakpoint; \
CountCase(i_get_sd): opc[135].count++; goto lb_i_get_sd; \
CountCase(i_get_hash_cId): opc[136].count++; goto lb_i_get_hash_cId; \
CountCase(i_get_map_element_fxxx): opc[137].count++; goto lb_i_get_map_element_fxxx; \
CountCase(i_get_map_element_fxxy): opc[138].count++; goto lb_i_get_map_element_fxxy; \
CountCase(i_get_map_element_fyxx): opc[139].count++; goto lb_i_get_map_element_fyxx; \
CountCase(i_get_map_element_fyxy): opc[140].count++; goto lb_i_get_map_element_fyxy; \
CountCase(i_get_map_element_hash_fxcIx): opc[141].count++; goto lb_i_get_map_element_hash_fxcIx; \
CountCase(i_get_map_element_hash_fxcIy): opc[142].count++; goto lb_i_get_map_element_hash_fxcIy; \
CountCase(i_get_map_element_hash_fycIx): opc[143].count++; goto lb_i_get_map_element_hash_fycIx; \
CountCase(i_get_map_element_hash_fycIy): opc[144].count++; goto lb_i_get_map_element_hash_fycIy; \
CountCase(i_get_map_elements_fsI): opc[145].count++; goto lb_i_get_map_elements_fsI; \
CountCase(i_get_tuple_element_xPx): opc[146].count++; goto lb_i_get_tuple_element_xPx; \
CountCase(i_get_tuple_element_xPy): opc[147].count++; goto lb_i_get_tuple_element_xPy; \
CountCase(i_get_tuple_element_yPx): opc[148].count++; goto lb_i_get_tuple_element_yPx; \
CountCase(i_get_tuple_element_yPy): opc[149].count++; goto lb_i_get_tuple_element_yPy; \
CountCase(i_get_tuple_element2_xPx): opc[150].count++; goto lb_i_get_tuple_element2_xPx; \
CountCase(i_get_tuple_element2y_xPyy): opc[151].count++; goto lb_i_get_tuple_element2y_xPyy; \
CountCase(i_get_tuple_element3_xPx): opc[152].count++; goto lb_i_get_tuple_element3_xPx; \
CountCase(i_hibernate): opc[153].count++; goto lb_i_hibernate; \
CountCase(i_increment_rIId): opc[154].count++; goto lb_i_increment_rIId; \
CountCase(i_increment_xIId): opc[155].count++; goto lb_i_increment_xIId; \
CountCase(i_increment_yIId): opc[156].count++; goto lb_i_increment_yIId; \
CountCase(i_int_bnot_jsId): opc[157].count++; goto lb_i_int_bnot_jsId; \
CountCase(i_int_div_jIssd): opc[158].count++; goto lb_i_int_div_jIssd; \
CountCase(i_is_eq_exact_immed_frc): opc[159].count++; goto lb_i_is_eq_exact_immed_frc; \
CountCase(i_is_eq_exact_immed_fxc): opc[160].count++; goto lb_i_is_eq_exact_immed_fxc; \
CountCase(i_is_eq_exact_immed_fyc): opc[161].count++; goto lb_i_is_eq_exact_immed_fyc; \
CountCase(i_is_eq_exact_literal_fxc): opc[162].count++; goto lb_i_is_eq_exact_literal_fxc; \
CountCase(i_is_eq_exact_literal_fyc): opc[163].count++; goto lb_i_is_eq_exact_literal_fyc; \
CountCase(i_is_ne_exact_immed_fxc): opc[164].count++; goto lb_i_is_ne_exact_immed_fxc; \
CountCase(i_is_ne_exact_immed_fyc): opc[165].count++; goto lb_i_is_ne_exact_immed_fyc; \
CountCase(i_is_ne_exact_literal_fxc): opc[166].count++; goto lb_i_is_ne_exact_literal_fxc; \
CountCase(i_is_ne_exact_literal_fyc): opc[167].count++; goto lb_i_is_ne_exact_literal_fyc; \
CountCase(i_jump_on_val_xfII): opc[168].count++; goto lb_i_jump_on_val_xfII; \
CountCase(i_jump_on_val_yfII): opc[169].count++; goto lb_i_jump_on_val_yfII; \
CountCase(i_jump_on_val_zero_xfI): opc[170].count++; goto lb_i_jump_on_val_zero_xfI; \
CountCase(i_jump_on_val_zero_yfI): opc[171].count++; goto lb_i_jump_on_val_zero_yfI; \
CountCase(i_loop_rec_f): opc[172].count++; goto lb_i_loop_rec_f; \
CountCase(i_m_div_jIssd): opc[173].count++; goto lb_i_m_div_jIssd; \
CountCase(i_make_fun_It): opc[174].count++; goto lb_i_make_fun_It; \
CountCase(i_minus_jIxxd): opc[175].count++; goto lb_i_minus_jIxxd; \
CountCase(i_minus_jIssd): opc[176].count++; goto lb_i_minus_jIssd; \
CountCase(i_move_call_cf): opc[177].count++; goto lb_i_move_call_cf; \
CountCase(i_move_call_ext_ce): opc[178].count++; goto lb_i_move_call_ext_ce; \
CountCase(i_move_call_ext_last_ePc): opc[179].count++; goto lb_i_move_call_ext_last_ePc; \
CountCase(i_move_call_ext_only_ec): opc[180].count++; goto lb_i_move_call_ext_only_ec; \
CountCase(i_move_call_last_fPc): opc[181].count++; goto lb_i_move_call_last_fPc; \
CountCase(i_move_call_only_fc): opc[182].count++; goto lb_i_move_call_only_fc; \
CountCase(i_new_bs_put_binary_jsIs): opc[183].count++; goto lb_i_new_bs_put_binary_jsIs; \
CountCase(i_new_bs_put_binary_all_jsI): opc[184].count++; goto lb_i_new_bs_put_binary_all_jsI; \
CountCase(i_new_bs_put_binary_imm_jIs): opc[185].count++; goto lb_i_new_bs_put_binary_imm_jIs; \
CountCase(i_new_bs_put_float_jsIs): opc[186].count++; goto lb_i_new_bs_put_float_jsIs; \
CountCase(i_new_bs_put_float_imm_jIIs): opc[187].count++; goto lb_i_new_bs_put_float_imm_jIIs; \
CountCase(i_new_bs_put_integer_jsIs): opc[188].count++; goto lb_i_new_bs_put_integer_jsIs; \
CountCase(i_new_bs_put_integer_imm_jIIs): opc[189].count++; goto lb_i_new_bs_put_integer_imm_jIIs; \
CountCase(i_perf_counter): opc[190].count++; goto lb_i_perf_counter; \
CountCase(i_plus_jIxxd): opc[191].count++; goto lb_i_plus_jIxxd; \
CountCase(i_plus_jIxyd): opc[192].count++; goto lb_i_plus_jIxyd; \
CountCase(i_plus_jIssd): opc[193].count++; goto lb_i_plus_jIssd; \
CountCase(i_put_tuple_xI): opc[194].count++; goto lb_i_put_tuple_xI; \
CountCase(i_put_tuple_yI): opc[195].count++; goto lb_i_put_tuple_yI; \
CountCase(i_raise): opc[196].count++; goto lb_i_raise; \
CountCase(i_recv_set): opc[197].count++; goto lb_i_recv_set; \
CountCase(i_rem_jIxxd): opc[198].count++; goto lb_i_rem_jIxxd; \
CountCase(i_rem_jIssd): opc[199].count++; goto lb_i_rem_jIssd; \
CountCase(i_return_time_trace): opc[200].count++; goto lb_i_return_time_trace; \
CountCase(i_return_to_trace): opc[201].count++; goto lb_i_return_to_trace; \
CountCase(i_select_tuple_arity_xfI): opc[202].count++; goto lb_i_select_tuple_arity_xfI; \
CountCase(i_select_tuple_arity_yfI): opc[203].count++; goto lb_i_select_tuple_arity_yfI; \
CountCase(i_select_tuple_arity2_xfAAff): opc[204].count++; goto lb_i_select_tuple_arity2_xfAAff; \
CountCase(i_select_tuple_arity2_yfAAff): opc[205].count++; goto lb_i_select_tuple_arity2_yfAAff; \
CountCase(i_select_val2_xfccff): opc[206].count++; goto lb_i_select_val2_xfccff; \
CountCase(i_select_val2_yfccff): opc[207].count++; goto lb_i_select_val2_yfccff; \
CountCase(i_select_val_bins_xfI): opc[208].count++; goto lb_i_select_val_bins_xfI; \
CountCase(i_select_val_bins_yfI): opc[209].count++; goto lb_i_select_val_bins_yfI; \
CountCase(i_select_val_lins_xfI): opc[210].count++; goto lb_i_select_val_lins_xfI; \
CountCase(i_select_val_lins_yfI): opc[211].count++; goto lb_i_select_val_lins_yfI; \
CountCase(i_times_jIssd): opc[212].count++; goto lb_i_times_jIssd; \
CountCase(i_trim_I): opc[213].count++; goto lb_i_trim_I; \
CountCase(i_wait_error): opc[214].count++; goto lb_i_wait_error; \
CountCase(i_wait_error_locked): opc[215].count++; goto lb_i_wait_error_locked; \
CountCase(i_wait_timeout_fI): opc[216].count++; goto lb_i_wait_timeout_fI; \
CountCase(i_wait_timeout_fs): opc[217].count++; goto lb_i_wait_timeout_fs; \
CountCase(i_wait_timeout_locked_fI): opc[218].count++; goto lb_i_wait_timeout_locked_fI; \
CountCase(i_wait_timeout_locked_fs): opc[219].count++; goto lb_i_wait_timeout_locked_fs; \
CountCase(i_yield): opc[220].count++; goto lb_i_yield; \
CountCase(if_end): opc[221].count++; goto lb_if_end; \
CountCase(init_y): opc[222].count++; goto lb_init_y; \
CountCase(init2_yy): opc[223].count++; goto lb_init2_yy; \
CountCase(init3_yyy): opc[224].count++; goto lb_init3_yyy; \
CountCase(int_code_end): opc[225].count++; goto lb_int_code_end; \
CountCase(is_atom_fx): opc[226].count++; goto lb_is_atom_fx; \
CountCase(is_atom_fy): opc[227].count++; goto lb_is_atom_fy; \
CountCase(is_binary_fx): opc[228].count++; goto lb_is_binary_fx; \
CountCase(is_binary_fy): opc[229].count++; goto lb_is_binary_fy; \
CountCase(is_bitstring_fx): opc[230].count++; goto lb_is_bitstring_fx; \
CountCase(is_bitstring_fy): opc[231].count++; goto lb_is_bitstring_fy; \
CountCase(is_boolean_fx): opc[232].count++; goto lb_is_boolean_fx; \
CountCase(is_boolean_fy): opc[233].count++; goto lb_is_boolean_fy; \
CountCase(is_eq_fss): opc[234].count++; goto lb_is_eq_fss; \
CountCase(is_eq_exact_fxx): opc[235].count++; goto lb_is_eq_exact_fxx; \
CountCase(is_eq_exact_fxy): opc[236].count++; goto lb_is_eq_exact_fxy; \
CountCase(is_eq_exact_fss): opc[237].count++; goto lb_is_eq_exact_fss; \
CountCase(is_float_fx): opc[238].count++; goto lb_is_float_fx; \
CountCase(is_float_fy): opc[239].count++; goto lb_is_float_fy; \
CountCase(is_function_fx): opc[240].count++; goto lb_is_function_fx; \
CountCase(is_function_fy): opc[241].count++; goto lb_is_function_fy; \
CountCase(is_function2_fss): opc[242].count++; goto lb_is_function2_fss; \
CountCase(is_ge_fxx): opc[243].count++; goto lb_is_ge_fxx; \
CountCase(is_ge_fxc): opc[244].count++; goto lb_is_ge_fxc; \
CountCase(is_ge_fcx): opc[245].count++; goto lb_is_ge_fcx; \
CountCase(is_ge_fss): opc[246].count++; goto lb_is_ge_fss; \
CountCase(is_integer_fx): opc[247].count++; goto lb_is_integer_fx; \
CountCase(is_integer_fy): opc[248].count++; goto lb_is_integer_fy; \
CountCase(is_integer_allocate_fxII): opc[249].count++; goto lb_is_integer_allocate_fxII; \
CountCase(is_list_fx): opc[250].count++; goto lb_is_list_fx; \
CountCase(is_list_fy): opc[251].count++; goto lb_is_list_fy; \
CountCase(is_lt_fxx): opc[252].count++; goto lb_is_lt_fxx; \
CountCase(is_lt_fxc): opc[253].count++; goto lb_is_lt_fxc; \
CountCase(is_lt_fcx): opc[254].count++; goto lb_is_lt_fcx; \
CountCase(is_lt_fss): opc[255].count++; goto lb_is_lt_fss; \
CountCase(is_map_fx): opc[256].count++; goto lb_is_map_fx; \
CountCase(is_map_fy): opc[257].count++; goto lb_is_map_fy; \
CountCase(is_ne_fss): opc[258].count++; goto lb_is_ne_fss; \
CountCase(is_ne_exact_fss): opc[259].count++; goto lb_is_ne_exact_fss; \
CountCase(is_nil_fx): opc[260].count++; goto lb_is_nil_fx; \
CountCase(is_nil_fy): opc[261].count++; goto lb_is_nil_fy; \
CountCase(is_non_empty_list_test_heap_fIt): opc[262].count++; goto lb_is_non_empty_list_test_heap_fIt; \
CountCase(is_nonempty_list_fx): opc[263].count++; goto lb_is_nonempty_list_fx; \
CountCase(is_nonempty_list_fy): opc[264].count++; goto lb_is_nonempty_list_fy; \
CountCase(is_nonempty_list_allocate_frIt): opc[265].count++; goto lb_is_nonempty_list_allocate_frIt; \
CountCase(is_nonempty_list_allocate_fxIt): opc[266].count++; goto lb_is_nonempty_list_allocate_fxIt; \
CountCase(is_nonempty_list_get_list_frxx): opc[267].count++; goto lb_is_nonempty_list_get_list_frxx; \
CountCase(is_nonempty_list_get_list_fxxx): opc[268].count++; goto lb_is_nonempty_list_get_list_fxxx; \
CountCase(is_number_fx): opc[269].count++; goto lb_is_number_fx; \
CountCase(is_number_fy): opc[270].count++; goto lb_is_number_fy; \
CountCase(is_pid_fx): opc[271].count++; goto lb_is_pid_fx; \
CountCase(is_pid_fy): opc[272].count++; goto lb_is_pid_fy; \
CountCase(is_port_fx): opc[273].count++; goto lb_is_port_fx; \
CountCase(is_port_fy): opc[274].count++; goto lb_is_port_fy; \
CountCase(is_reference_fx): opc[275].count++; goto lb_is_reference_fx; \
CountCase(is_reference_fy): opc[276].count++; goto lb_is_reference_fy; \
CountCase(is_tuple_fr): opc[277].count++; goto lb_is_tuple_fr; \
CountCase(is_tuple_fx): opc[278].count++; goto lb_is_tuple_fx; \
CountCase(is_tuple_fy): opc[279].count++; goto lb_is_tuple_fy; \
CountCase(is_tuple_of_arity_frA): opc[280].count++; goto lb_is_tuple_of_arity_frA; \
CountCase(is_tuple_of_arity_fxA): opc[281].count++; goto lb_is_tuple_of_arity_fxA; \
CountCase(is_tuple_of_arity_fyA): opc[282].count++; goto lb_is_tuple_of_arity_fyA; \
CountCase(jump_f): opc[283].count++; goto lb_jump_f; \
CountCase(label_L): opc[284].count++; goto lb_label_L; \
CountCase(line_I): opc[285].count++; goto lb_line_I; \
CountCase(loop_rec_end_f): opc[286].count++; goto lb_loop_rec_end_f; \
CountCase(move_nx): opc[287].count++; goto lb_move_nx; \
CountCase(move_rx): opc[288].count++; goto lb_move_rx; \
CountCase(move_ry): opc[289].count++; goto lb_move_ry; \
CountCase(move_xr): opc[290].count++; goto lb_move_xr; \
CountCase(move_xx): opc[291].count++; goto lb_move_xx; \
CountCase(move_xy): opc[292].count++; goto lb_move_xy; \
CountCase(move_yr): opc[293].count++; goto lb_move_yr; \
CountCase(move_yx): opc[294].count++; goto lb_move_yx; \
CountCase(move_yy): opc[295].count++; goto lb_move_yy; \
CountCase(move_cr): opc[296].count++; goto lb_move_cr; \
CountCase(move_cx): opc[297].count++; goto lb_move_cx; \
CountCase(move2_par_xxxx): opc[298].count++; goto lb_move2_par_xxxx; \
CountCase(move2_par_xxxy): opc[299].count++; goto lb_move2_par_xxxy; \
CountCase(move2_par_xxyx): opc[300].count++; goto lb_move2_par_xxyx; \
CountCase(move2_par_xyxy): opc[301].count++; goto lb_move2_par_xyxy; \
CountCase(move2_par_yxxx): opc[302].count++; goto lb_move2_par_yxxx; \
CountCase(move2_par_yxxy): opc[303].count++; goto lb_move2_par_yxxy; \
CountCase(move2_par_yxyx): opc[304].count++; goto lb_move2_par_yxyx; \
CountCase(move3_xxxxxx): opc[305].count++; goto lb_move3_xxxxxx; \
CountCase(move3_xyxyxy): opc[306].count++; goto lb_move3_xyxyxy; \
CountCase(move3_yxyxyx): opc[307].count++; goto lb_move3_yxyxyx; \
CountCase(move_call_xf): opc[308].count++; goto lb_move_call_xf; \
CountCase(move_call_yf): opc[309].count++; goto lb_move_call_yf; \
CountCase(move_call_last_xfQ): opc[310].count++; goto lb_move_call_last_xfQ; \
CountCase(move_call_last_yfQ): opc[311].count++; goto lb_move_call_last_yfQ; \
CountCase(move_call_only_xf): opc[312].count++; goto lb_move_call_only_xf; \
CountCase(move_deallocate_return_nQ): opc[313].count++; goto lb_move_deallocate_return_nQ; \
CountCase(move_deallocate_return_xQ): opc[314].count++; goto lb_move_deallocate_return_xQ; \
CountCase(move_deallocate_return_yQ): opc[315].count++; goto lb_move_deallocate_return_yQ; \
CountCase(move_deallocate_return_cQ): opc[316].count++; goto lb_move_deallocate_return_cQ; \
CountCase(move_dup_xxx): opc[317].count++; goto lb_move_dup_xxx; \
CountCase(move_dup_xxy): opc[318].count++; goto lb_move_dup_xxy; \
CountCase(move_dup_yxx): opc[319].count++; goto lb_move_dup_yxx; \
CountCase(move_dup_yxy): opc[320].count++; goto lb_move_dup_yxy; \
CountCase(move_jump_fn): opc[321].count++; goto lb_move_jump_fn; \
CountCase(move_jump_fx): opc[322].count++; goto lb_move_jump_fx; \
CountCase(move_jump_fy): opc[323].count++; goto lb_move_jump_fy; \
CountCase(move_jump_fc): opc[324].count++; goto lb_move_jump_fc; \
CountCase(move_return_n): opc[325].count++; goto lb_move_return_n; \
CountCase(move_return_x): opc[326].count++; goto lb_move_return_x; \
CountCase(move_return_c): opc[327].count++; goto lb_move_return_c; \
CountCase(move_shift_xxx): opc[328].count++; goto lb_move_shift_xxx; \
CountCase(move_shift_xxy): opc[329].count++; goto lb_move_shift_xxy; \
CountCase(move_shift_xyx): opc[330].count++; goto lb_move_shift_xyx; \
CountCase(move_shift_yxx): opc[331].count++; goto lb_move_shift_yxx; \
CountCase(move_window3_xxxy): opc[332].count++; goto lb_move_window3_xxxy; \
CountCase(move_window4_xxxxy): opc[333].count++; goto lb_move_window4_xxxxy; \
CountCase(move_window5_xxxxxy): opc[334].count++; goto lb_move_window5_xxxxxy; \
CountCase(move_x1_c): opc[335].count++; goto lb_move_x1_c; \
CountCase(move_x2_c): opc[336].count++; goto lb_move_x2_c; \
CountCase(new_map_dII): opc[337].count++; goto lb_new_map_dII; \
CountCase(node_x): opc[338].count++; goto lb_node_x; \
CountCase(node_y): opc[339].count++; goto lb_node_y; \
CountCase(normal_exit): opc[340].count++; goto lb_normal_exit; \
CountCase(on_load): opc[341].count++; goto lb_on_load; \
CountCase(put_list_rnr): opc[342].count++; goto lb_put_list_rnr; \
CountCase(put_list_rnx): opc[343].count++; goto lb_put_list_rnx; \
CountCase(put_list_rxr): opc[344].count++; goto lb_put_list_rxr; \
CountCase(put_list_rxx): opc[345].count++; goto lb_put_list_rxx; \
CountCase(put_list_xnx): opc[346].count++; goto lb_put_list_xnx; \
CountCase(put_list_xrr): opc[347].count++; goto lb_put_list_xrr; \
CountCase(put_list_xxr): opc[348].count++; goto lb_put_list_xxr; \
CountCase(put_list_xxx): opc[349].count++; goto lb_put_list_xxx; \
CountCase(put_list_xyx): opc[350].count++; goto lb_put_list_xyx; \
CountCase(put_list_ynx): opc[351].count++; goto lb_put_list_ynx; \
CountCase(put_list_yrr): opc[352].count++; goto lb_put_list_yrr; \
CountCase(put_list_yxx): opc[353].count++; goto lb_put_list_yxx; \
CountCase(put_list_yyx): opc[354].count++; goto lb_put_list_yyx; \
CountCase(put_list_xcx): opc[355].count++; goto lb_put_list_xcx; \
CountCase(put_list_xcy): opc[356].count++; goto lb_put_list_xcy; \
CountCase(put_list_ycx): opc[357].count++; goto lb_put_list_ycx; \
CountCase(put_list_cxx): opc[358].count++; goto lb_put_list_cxx; \
CountCase(put_list_cyx): opc[359].count++; goto lb_put_list_cyx; \
CountCase(put_list_ssd): opc[360].count++; goto lb_put_list_ssd; \
CountCase(recv_mark_f): opc[361].count++; goto lb_recv_mark_f; \
CountCase(remove_message): opc[362].count++; goto lb_remove_message; \
CountCase(return): opc[363].count++; goto lb_return; \
CountCase(return_trace): opc[364].count++; goto lb_return_trace; \
CountCase(self_x): opc[365].count++; goto lb_self_x; \
CountCase(self_y): opc[366].count++; goto lb_self_y; \
CountCase(send): opc[367].count++; goto lb_send; \
CountCase(set_tuple_element_sdP): opc[368].count++; goto lb_set_tuple_element_sdP; \
CountCase(swap_xx): opc[369].count++; goto lb_swap_xx; \
CountCase(swap_xy): opc[370].count++; goto lb_swap_xy; \
CountCase(swap_temp_xxx): opc[371].count++; goto lb_swap_temp_xxx; \
CountCase(swap_temp_xyx): opc[372].count++; goto lb_swap_temp_xyx; \
CountCase(system_limit_j): opc[373].count++; goto lb_system_limit_j; \
CountCase(test_arity_fxA): opc[374].count++; goto lb_test_arity_fxA; \
CountCase(test_arity_fyA): opc[375].count++; goto lb_test_arity_fyA; \
CountCase(test_heap_It): opc[376].count++; goto lb_test_heap_It; \
CountCase(test_heap_1_put_list_Iy): opc[377].count++; goto lb_test_heap_1_put_list_Iy; \
CountCase(timeout): opc[378].count++; goto lb_timeout; \
CountCase(timeout_locked): opc[379].count++; goto lb_timeout_locked; \
CountCase(try_case_end_s): opc[380].count++; goto lb_try_case_end_s; \
CountCase(try_end_y): opc[381].count++; goto lb_try_end_y; \
CountCase(update_map_assoc_jsdII): opc[382].count++; goto lb_update_map_assoc_jsdII; \
CountCase(update_map_exact_jsdII): opc[383].count++; goto lb_update_map_exact_jsdII; \
CountCase(wait_f): opc[384].count++; goto lb_wait_f; \
CountCase(wait_locked_f): opc[385].count++; goto lb_wait_locked_f; \
CountCase(wait_unlocked_f): opc[386].count++; goto lb_wait_unlocked_f;

#define genop_label_1 1
#define genop_func_info_3 2
#define genop_int_code_end_0 3
#define genop_call_2 4
#define genop_call_last_3 5
#define genop_call_only_2 6
#define genop_call_ext_2 7
#define genop_call_ext_last_3 8
#define genop_bif0_2 9
#define genop_bif1_4 10
#define genop_bif2_5 11
#define genop_allocate_2 12
#define genop_allocate_heap_3 13
#define genop_allocate_zero_2 14
#define genop_allocate_heap_zero_3 15
#define genop_test_heap_2 16
#define genop_init_1 17
#define genop_deallocate_1 18
#define genop_return_0 19
#define genop_send_0 20
#define genop_remove_message_0 21
#define genop_timeout_0 22
#define genop_loop_rec_2 23
#define genop_loop_rec_end_1 24
#define genop_wait_1 25
#define genop_wait_timeout_2 26
#define genop_m_plus_4 27
#define genop_m_minus_4 28
#define genop_m_times_4 29
#define genop_m_div_4 30
#define genop_int_div_4 31
#define genop_int_rem_4 32
#define genop_int_band_4 33
#define genop_int_bor_4 34
#define genop_int_bxor_4 35
#define genop_int_bsl_4 36
#define genop_int_bsr_4 37
#define genop_int_bnot_3 38
#define genop_is_lt_3 39
#define genop_is_ge_3 40
#define genop_is_eq_3 41
#define genop_is_ne_3 42
#define genop_is_eq_exact_3 43
#define genop_is_ne_exact_3 44
#define genop_is_integer_2 45
#define genop_is_float_2 46
#define genop_is_number_2 47
#define genop_is_atom_2 48
#define genop_is_pid_2 49
#define genop_is_reference_2 50
#define genop_is_port_2 51
#define genop_is_nil_2 52
#define genop_is_binary_2 53
#define genop_is_constant_2 54
#define genop_is_list_2 55
#define genop_is_nonempty_list_2 56
#define genop_is_tuple_2 57
#define genop_test_arity_3 58
#define genop_select_val_3 59
#define genop_select_tuple_arity_3 60
#define genop_jump_1 61
#define genop_catch_2 62
#define genop_catch_end_1 63
#define genop_move_2 64
#define genop_get_list_3 65
#define genop_get_tuple_element_3 66
#define genop_set_tuple_element_3 67
#define genop_put_string_3 68
#define genop_put_list_3 69
#define genop_put_tuple_2 70
#define genop_put_1 71
#define genop_badmatch_1 72
#define genop_if_end_0 73
#define genop_case_end_1 74
#define genop_call_fun_1 75
#define genop_make_fun_3 76
#define genop_is_function_2 77
#define genop_call_ext_only_2 78
#define genop_bs_start_match_2 79
#define genop_bs_get_integer_5 80
#define genop_bs_get_float_5 81
#define genop_bs_get_binary_5 82
#define genop_bs_skip_bits_4 83
#define genop_bs_test_tail_2 84
#define genop_bs_save_1 85
#define genop_bs_restore_1 86
#define genop_bs_init_2 87
#define genop_bs_final_2 88
#define genop_bs_put_integer_5 89
#define genop_bs_put_binary_5 90
#define genop_bs_put_float_5 91
#define genop_bs_put_string_2 92
#define genop_bs_need_buf_1 93
#define genop_fclearerror_0 94
#define genop_fcheckerror_1 95
#define genop_fmove_2 96
#define genop_fconv_2 97
#define genop_fadd_4 98
#define genop_fsub_4 99
#define genop_fmul_4 100
#define genop_fdiv_4 101
#define genop_fnegate_3 102
#define genop_make_fun2_1 103
#define genop_try_2 104
#define genop_try_end_1 105
#define genop_try_case_1 106
#define genop_try_case_end_1 107
#define genop_raise_2 108
#define genop_bs_init2_6 109
#define genop_bs_bits_to_bytes_3 110
#define genop_bs_add_5 111
#define genop_apply_1 112
#define genop_apply_last_2 113
#define genop_is_boolean_2 114
#define genop_is_function2_3 115
#define genop_bs_start_match2_5 116
#define genop_bs_get_integer2_7 117
#define genop_bs_get_float2_7 118
#define genop_bs_get_binary2_7 119
#define genop_bs_skip_bits2_5 120
#define genop_bs_test_tail2_3 121
#define genop_bs_save2_2 122
#define genop_bs_restore2_2 123
#define genop_gc_bif1_5 124
#define genop_gc_bif2_6 125
#define genop_bs_final2_2 126
#define genop_bs_bits_to_bytes2_2 127
#define genop_put_literal_2 128
#define genop_is_bitstr_2 129
#define genop_bs_context_to_binary_1 130
#define genop_bs_test_unit_3 131
#define genop_bs_match_string_4 132
#define genop_bs_init_writable_0 133
#define genop_bs_append_8 134
#define genop_bs_private_append_6 135
#define genop_trim_2 136
#define genop_bs_init_bits_6 137
#define genop_bs_get_utf8_5 138
#define genop_bs_skip_utf8_4 139
#define genop_bs_get_utf16_5 140
#define genop_bs_skip_utf16_4 141
#define genop_bs_get_utf32_5 142
#define genop_bs_skip_utf32_4 143
#define genop_bs_utf8_size_3 144
#define genop_bs_put_utf8_3 145
#define genop_bs_utf16_size_3 146
#define genop_bs_put_utf16_3 147
#define genop_bs_put_utf32_3 148
#define genop_on_load_0 149
#define genop_recv_mark_1 150
#define genop_recv_set_1 151
#define genop_gc_bif3_7 152
#define genop_line_1 153
#define genop_put_map_assoc_5 154
#define genop_put_map_exact_5 155
#define genop_is_map_2 156
#define genop_has_map_fields_3 157
#define genop_get_map_elements_3 158
#define genop_too_old_compiler_0 159
#define genop_i_func_info_4 160
#define genop_i_generic_breakpoint_0 161
#define genop_i_debug_breakpoint_0 162
#define genop_i_return_time_trace_0 163
#define genop_i_return_to_trace_0 164
#define genop_i_yield_0 165
#define genop_i_trim_1 166
#define genop_init2_2 167
#define genop_init3_3 168
#define genop_i_select_val_bins_3 169
#define genop_i_select_val_lins_3 170
#define genop_i_select_val2_6 171
#define genop_i_select_tuple_arity_3 172
#define genop_i_select_tuple_arity2_6 173
#define genop_i_jump_on_val_zero_3 174
#define genop_i_jump_on_val_4 175
#define genop_i_get_tuple_element_3 176
#define genop_i_get_tuple_element2_3 177
#define genop_i_get_tuple_element2y_4 178
#define genop_i_get_tuple_element3_3 179
#define genop_i_raise_0 180
#define genop_badarg_1 181
#define genop_system_limit_1 182
#define genop_move_jump_2 183
#define genop_move_window_5 184
#define genop_move_window_6 185
#define genop_move_window3_4 186
#define genop_move_window4_5 187
#define genop_move_window5_6 188
#define genop_swap_temp_3 189
#define genop_swap_2 190
#define genop_move_x1_1 191
#define genop_move_x2_1 192
#define genop_move_shift_3 193
#define genop_move_dup_3 194
#define genop_move2_par_4 195
#define genop_move3_6 196
#define genop_timeout_locked_0 197
#define genop_i_loop_rec_1 198
#define genop_wait_locked_1 199
#define genop_wait_unlocked_1 200
#define genop_i_wait_timeout_2 201
#define genop_i_wait_timeout_locked_2 202
#define genop_i_wait_error_0 203
#define genop_i_wait_error_locked_0 204
#define genop_i_is_eq_exact_immed_3 205
#define genop_i_is_eq_exact_literal_3 206
#define genop_i_is_ne_exact_immed_3 207
#define genop_i_is_ne_exact_literal_3 208
#define genop_i_put_tuple_2 209
#define genop_normal_exit_0 210
#define genop_continue_exit_0 211
#define genop_apply_bif_0 212
#define genop_call_nif_0 213
#define genop_call_error_handler_0 214
#define genop_error_action_code_0 215
#define genop_return_trace_0 216
#define genop_move_return_1 217
#define genop_move_deallocate_return_2 218
#define genop_deallocate_return_1 219
#define genop_test_heap_1_put_list_2 220
#define genop_is_tuple_of_arity_3 221
#define genop_is_integer_allocate_4 222
#define genop_is_nonempty_list_allocate_4 223
#define genop_is_non_empty_list_test_heap_3 224
#define genop_is_nonempty_list_get_list_4 225
#define genop_is_bitstring_2 226
#define genop_allocate_init_3 227
#define genop_i_apply_0 228
#define genop_i_apply_last_1 229
#define genop_i_apply_only_0 230
#define genop_i_apply_fun_0 231
#define genop_i_apply_fun_last_1 232
#define genop_i_apply_fun_only_0 233
#define genop_i_hibernate_0 234
#define genop_i_perf_counter_0 235
#define genop_call_bif_1 236
#define genop_i_get_hash_3 237
#define genop_i_get_2 238
#define genop_self_1 239
#define genop_node_1 240
#define genop_i_fast_element_4 241
#define genop_i_element_4 242
#define genop_bif1_body_3 243
#define genop_i_bif2_5 244
#define genop_i_bif2_body_4 245
#define genop_i_move_call_2 246
#define genop_move_call_2 247
#define genop_i_move_call_last_3 248
#define genop_move_call_last_3 249
#define genop_i_move_call_only_2 250
#define genop_move_call_only_2 251
#define genop_i_call_1 252
#define genop_i_call_last_2 253
#define genop_i_call_only_1 254
#define genop_i_call_ext_1 255
#define genop_i_call_ext_last_2 256
#define genop_i_call_ext_only_1 257
#define genop_i_move_call_ext_2 258
#define genop_i_move_call_ext_last_3 259
#define genop_i_move_call_ext_only_2 260
#define genop_i_call_fun_1 261
#define genop_i_call_fun_last_2 262
#define genop_i_make_fun_2 263
#define genop_i_bs_start_match2_5 264
#define genop_i_bs_save2_2 265
#define genop_i_bs_restore2_2 266
#define genop_i_bs_match_string_4 267
#define genop_i_bs_get_integer_small_imm_5 268
#define genop_i_bs_get_integer_imm_6 269
#define genop_i_bs_get_integer_6 270
#define genop_i_bs_get_integer_8_3 271
#define genop_i_bs_get_integer_16_3 272
#define genop_i_bs_get_integer_32_4 273
#define genop_i_bs_get_binary_imm2_6 274
#define genop_i_bs_get_binary2_6 275
#define genop_i_bs_get_binary_all2_5 276
#define genop_i_bs_get_binary_all_reuse_3 277
#define genop_i_bs_get_float2_6 278
#define genop_i_bs_skip_bits_imm2_3 279
#define genop_i_bs_skip_bits2_4 280
#define genop_i_bs_skip_bits_all2_3 281
#define genop_bs_test_zero_tail2_2 282
#define genop_bs_test_tail_imm2_3 283
#define genop_bs_test_unit8_2 284
#define genop_i_bs_get_utf8_3 285
#define genop_i_bs_get_utf16_4 286
#define genop_i_bs_validate_unicode_retract_3 287
#define genop_i_bs_init_fail_4 288
#define genop_i_bs_init_fail_heap_5 289
#define genop_i_bs_init_3 290
#define genop_i_bs_init_heap_bin_3 291
#define genop_i_bs_init_heap_4 292
#define genop_i_bs_init_heap_bin_heap_4 293
#define genop_i_bs_init_bits_fail_4 294
#define genop_i_bs_init_bits_fail_heap_5 295
#define genop_i_bs_init_bits_3 296
#define genop_i_bs_init_bits_heap_4 297
#define genop_i_bs_append_6 298
#define genop_i_bs_private_append_5 299
#define genop_i_new_bs_put_integer_4 300
#define genop_i_new_bs_put_integer_imm_4 301
#define genop_i_bs_utf8_size_2 302
#define genop_i_bs_utf16_size_2 303
#define genop_i_bs_put_utf8_2 304
#define genop_i_bs_validate_unicode_2 305
#define genop_i_new_bs_put_float_4 306
#define genop_i_new_bs_put_float_imm_4 307
#define genop_i_new_bs_put_binary_4 308
#define genop_i_new_bs_put_binary_imm_3 309
#define genop_i_new_bs_put_binary_all_3 310
#define genop_i_fadd_3 311
#define genop_i_fsub_3 312
#define genop_i_fmul_3 313
#define genop_i_fdiv_3 314
#define genop_i_fnegate_2 315
#define genop_i_fcheckerror_0 316
#define genop_sorted_put_map_assoc_5 317
#define genop_sorted_put_map_exact_5 318
#define genop_new_map_3 319
#define genop_update_map_assoc_5 320
#define genop_update_map_exact_5 321
#define genop_i_get_map_elements_3 322
#define genop_i_get_map_element_hash_5 323
#define genop_i_get_map_element_4 324
#define genop_gen_plus_5 325
#define genop_gen_minus_5 326
#define genop_i_increment_4 327
#define genop_i_plus_5 328
#define genop_i_minus_5 329
#define genop_i_times_5 330
#define genop_i_m_div_5 331
#define genop_i_int_div_5 332
#define genop_i_rem_5 333
#define genop_i_bsl_5 334
#define genop_i_bsr_5 335
#define genop_i_band_5 336
#define genop_i_bor_5 337
#define genop_i_bxor_5 338
#define genop_i_int_bnot_4 339
#define genop_i_gc_bif1_5 340
#define genop_i_gc_bif2_6 341
#define genop_ii_gc_bif3_7 342
#define genop_i_gc_bif3_6 343
#define genop_unsupported_guard_bif_3 344
#define genop_i_recv_set_0 345
#define genop_hipe_trap_call_0 346
#define genop_hipe_trap_call_closure_0 347
#define genop_hipe_trap_return_0 348
#define genop_hipe_trap_throw_0 349
#define genop_hipe_trap_resume_0 350
#define genop_hipe_call_count_0 351
#endif
