/*
 *  Warning: Do not edit this file.  It was automatically
 *  generated by 'make_tables' on Wed Jul 12 20:16:17 2017.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif /* HAVE_CONFIG_H */
#include "erl_process.h"
#include "erl_nfunc_sched.h"
#include "erl_bif_table.h"
#include "erl_atom_table.h"

Eterm schedule_dirty_cpu_erts_debug_dirty_cpu_2(Process *c_p, Eterm *regs, BeamInstr *I)
{
    return erts_reschedule_bif(c_p, regs, I, erts_debug_dirty_cpu_2, ERTS_SCHED_DIRTY_CPU);
}

Eterm schedule_dirty_io_erts_debug_dirty_io_2(Process *c_p, Eterm *regs, BeamInstr *I)
{
    return erts_reschedule_bif(c_p, regs, I, erts_debug_dirty_io_2, ERTS_SCHED_DIRTY_IO);
}

