/*
 *  Warning: Do not edit this file.  It was automatically
 *  generated by 'make_tables' on Wed Jul 12 20:16:17 2017.
 */

#ifndef __ERL_BIF_TABLE_H__
#define __ERL_BIF_TABLE_H__
typedef void *BifFunction;

typedef struct bif_entry {
    Eterm module;
    Eterm name;
    int arity;
    BifFunction f;
    BifFunction traced;
    BifFunction impl;
} BifEntry;

typedef struct erts_gc_bif {
    BifFunction bif;
    BifFunction gc_bif;
    int exp_ix;
} ErtsGcBif;

typedef struct erts_u_bif {
    BifFunction bif;
    int exp_ix;
} ErtsUBif;

extern BifEntry bif_table[];
extern Export* bif_export[];
extern const ErtsGcBif erts_gc_bifs[];
extern const ErtsUBif erts_u_bifs[];

#define BIF_SIZE 506

#define BIF_abs_1 0
#define BIF_adler32_1 1
#define BIF_adler32_2 2
#define BIF_adler32_combine_3 3
#define BIF_apply_3 4
#define BIF_atom_to_list_1 5
#define BIF_binary_to_list_1 6
#define BIF_binary_to_list_3 7
#define BIF_binary_to_term_1 8
#define BIF_crc32_1 9
#define BIF_crc32_2 10
#define BIF_crc32_combine_3 11
#define BIF_date_0 12
#define BIF_delete_module_1 13
#define BIF_display_1 14
#define BIF_display_string_1 15
#define BIF_display_nl_0 16
#define BIF_element_2 17
#define BIF_erase_0 18
#define BIF_erase_1 19
#define BIF_exit_1 20
#define BIF_exit_2 21
#define BIF_external_size_1 22
#define BIF_external_size_2 23
#define BIF_float_1 24
#define BIF_float_to_list_1 25
#define BIF_float_to_list_2 26
#define BIF_fun_info_2 27
#define BIF_erts_internal_garbage_collect_1 28
#define BIF_get_0 29
#define BIF_get_1 30
#define BIF_get_keys_1 31
#define BIF_group_leader_0 32
#define BIF_group_leader_2 33
#define BIF_halt_2 34
#define BIF_phash_2 35
#define BIF_phash2_1 36
#define BIF_phash2_2 37
#define BIF_hd_1 38
#define BIF_integer_to_list_1 39
#define BIF_is_alive_0 40
#define BIF_length_1 41
#define BIF_link_1 42
#define BIF_list_to_atom_1 43
#define BIF_list_to_binary_1 44
#define BIF_list_to_float_1 45
#define BIF_list_to_integer_1 46
#define BIF_list_to_pid_1 47
#define BIF_list_to_port_1 48
#define BIF_list_to_ref_1 49
#define BIF_list_to_tuple_1 50
#define BIF_loaded_0 51
#define BIF_localtime_0 52
#define BIF_localtime_to_universaltime_2 53
#define BIF_make_ref_0 54
#define BIF_unique_integer_0 55
#define BIF_unique_integer_1 56
#define BIF_md5_1 57
#define BIF_md5_init_0 58
#define BIF_md5_update_2 59
#define BIF_md5_final_1 60
#define BIF_module_loaded_1 61
#define BIF_function_exported_3 62
#define BIF_monitor_node_2 63
#define BIF_monitor_node_3 64
#define BIF_node_1 65
#define BIF_node_0 66
#define BIF_nodes_1 67
#define BIF_now_0 68
#define BIF_monotonic_time_0 69
#define BIF_monotonic_time_1 70
#define BIF_system_time_0 71
#define BIF_system_time_1 72
#define BIF_time_offset_0 73
#define BIF_time_offset_1 74
#define BIF_timestamp_0 75
#define BIF_erts_internal_open_port_2 76
#define BIF_pid_to_list_1 77
#define BIF_ports_0 78
#define BIF_pre_loaded_0 79
#define BIF_process_flag_2 80
#define BIF_process_flag_3 81
#define BIF_process_info_1 82
#define BIF_process_info_2 83
#define BIF_processes_0 84
#define BIF_put_2 85
#define BIF_register_2 86
#define BIF_registered_0 87
#define BIF_round_1 88
#define BIF_self_0 89
#define BIF_setelement_3 90
#define BIF_size_1 91
#define BIF_spawn_3 92
#define BIF_spawn_link_3 93
#define BIF_split_binary_2 94
#define BIF_statistics_1 95
#define BIF_term_to_binary_1 96
#define BIF_term_to_binary_2 97
#define BIF_throw_1 98
#define BIF_time_0 99
#define BIF_tl_1 100
#define BIF_trunc_1 101
#define BIF_tuple_to_list_1 102
#define BIF_universaltime_0 103
#define BIF_universaltime_to_localtime_1 104
#define BIF_unlink_1 105
#define BIF_unregister_1 106
#define BIF_whereis_1 107
#define BIF_spawn_opt_1 108
#define BIF_setnode_2 109
#define BIF_setnode_3 110
#define BIF_dist_exit_3 111
#define BIF_erts_internal_port_info_1 112
#define BIF_erts_internal_port_info_2 113
#define BIF_erts_internal_port_call_3 114
#define BIF_erts_internal_port_command_3 115
#define BIF_erts_internal_port_control_3 116
#define BIF_erts_internal_port_close_1 117
#define BIF_erts_internal_port_connect_2 118
#define BIF_erts_internal_request_system_task_3 119
#define BIF_erts_internal_request_system_task_4 120
#define BIF_erts_internal_check_process_code_1 121
#define BIF_erts_internal_map_to_tuple_keys_1 122
#define BIF_erts_internal_term_type_1 123
#define BIF_erts_internal_map_hashmap_children_1 124
#define BIF_erts_internal_time_unit_0 125
#define BIF_erts_internal_perf_counter_unit_0 126
#define BIF_erts_internal_is_system_process_1 127
#define BIF_erts_internal_system_check_1 128
#define BIF_erts_internal_release_literal_area_switch_0 129
#define BIF_port_set_data_2 130
#define BIF_port_get_data_1 131
#define BIF_erts_internal_trace_pattern_3 132
#define BIF_erts_internal_trace_3 133
#define BIF_trace_info_2 134
#define BIF_trace_delivered_1 135
#define BIF_seq_trace_2 136
#define BIF_seq_trace_info_1 137
#define BIF_seq_trace_print_1 138
#define BIF_seq_trace_print_2 139
#define BIF_suspend_process_2 140
#define BIF_resume_process_1 141
#define BIF_process_display_2 142
#define BIF_bump_reductions_1 143
#define BIF_math_cos_1 144
#define BIF_math_cosh_1 145
#define BIF_math_sin_1 146
#define BIF_math_sinh_1 147
#define BIF_math_tan_1 148
#define BIF_math_tanh_1 149
#define BIF_math_acos_1 150
#define BIF_math_acosh_1 151
#define BIF_math_asin_1 152
#define BIF_math_asinh_1 153
#define BIF_math_atan_1 154
#define BIF_math_atanh_1 155
#define BIF_math_erf_1 156
#define BIF_math_erfc_1 157
#define BIF_math_exp_1 158
#define BIF_math_log_1 159
#define BIF_math_log2_1 160
#define BIF_math_log10_1 161
#define BIF_math_sqrt_1 162
#define BIF_math_atan2_2 163
#define BIF_math_pow_2 164
#define BIF_start_timer_3 165
#define BIF_start_timer_4 166
#define BIF_send_after_3 167
#define BIF_send_after_4 168
#define BIF_cancel_timer_1 169
#define BIF_cancel_timer_2 170
#define BIF_read_timer_1 171
#define BIF_read_timer_2 172
#define BIF_make_tuple_2 173
#define BIF_append_element_2 174
#define BIF_make_tuple_3 175
#define BIF_system_flag_2 176
#define BIF_system_info_1 177
#define BIF_system_monitor_0 178
#define BIF_system_monitor_1 179
#define BIF_system_monitor_2 180
#define BIF_system_profile_2 181
#define BIF_system_profile_0 182
#define BIF_ref_to_list_1 183
#define BIF_port_to_list_1 184
#define BIF_fun_to_list_1 185
#define BIF_monitor_2 186
#define BIF_demonitor_1 187
#define BIF_demonitor_2 188
#define BIF_is_process_alive_1 189
#define BIF_error_1 190
#define BIF_error_2 191
#define BIF_raise_3 192
#define BIF_get_stacktrace_0 193
#define BIF_is_builtin_3 194
#define BIF_and_2 195
#define BIF_or_2 196
#define BIF_xor_2 197
#define BIF_not_1 198
#define BIF_sgt_2 199
#define BIF_sge_2 200
#define BIF_slt_2 201
#define BIF_sle_2 202
#define BIF_seq_2 203
#define BIF_seqeq_2 204
#define BIF_sneq_2 205
#define BIF_sneqeq_2 206
#define BIF_splus_2 207
#define BIF_sminus_2 208
#define BIF_stimes_2 209
#define BIF_div_2 210
#define BIF_intdiv_2 211
#define BIF_rem_2 212
#define BIF_bor_2 213
#define BIF_band_2 214
#define BIF_bxor_2 215
#define BIF_bsl_2 216
#define BIF_bsr_2 217
#define BIF_bnot_1 218
#define BIF_sminus_1 219
#define BIF_splus_1 220
#define BIF_ebif_bang_2 221
#define BIF_send_2 222
#define BIF_send_3 223
#define BIF_ebif_plusplus_2 224
#define BIF_append_2 225
#define BIF_ebif_minusminus_2 226
#define BIF_subtract_2 227
#define BIF_is_atom_1 228
#define BIF_is_list_1 229
#define BIF_is_tuple_1 230
#define BIF_is_float_1 231
#define BIF_is_integer_1 232
#define BIF_is_number_1 233
#define BIF_is_pid_1 234
#define BIF_is_port_1 235
#define BIF_is_reference_1 236
#define BIF_is_binary_1 237
#define BIF_is_function_1 238
#define BIF_is_function_2 239
#define BIF_is_record_2 240
#define BIF_is_record_3 241
#define BIF_match_spec_test_3 242
#define BIF_ets_internal_request_all_0 243
#define BIF_ets_new_2 244
#define BIF_ets_delete_1 245
#define BIF_ets_delete_2 246
#define BIF_ets_delete_all_objects_1 247
#define BIF_ets_delete_object_2 248
#define BIF_ets_first_1 249
#define BIF_ets_is_compiled_ms_1 250
#define BIF_ets_lookup_2 251
#define BIF_ets_lookup_element_3 252
#define BIF_ets_info_1 253
#define BIF_ets_info_2 254
#define BIF_ets_last_1 255
#define BIF_ets_match_1 256
#define BIF_ets_match_2 257
#define BIF_ets_match_3 258
#define BIF_ets_match_object_1 259
#define BIF_ets_match_object_2 260
#define BIF_ets_match_object_3 261
#define BIF_ets_member_2 262
#define BIF_ets_next_2 263
#define BIF_ets_prev_2 264
#define BIF_ets_insert_2 265
#define BIF_ets_insert_new_2 266
#define BIF_ets_rename_2 267
#define BIF_ets_safe_fixtable_2 268
#define BIF_ets_slot_2 269
#define BIF_ets_update_counter_3 270
#define BIF_ets_select_1 271
#define BIF_ets_select_2 272
#define BIF_ets_select_3 273
#define BIF_ets_select_count_2 274
#define BIF_ets_select_reverse_1 275
#define BIF_ets_select_reverse_2 276
#define BIF_ets_select_reverse_3 277
#define BIF_ets_select_delete_2 278
#define BIF_ets_select_replace_2 279
#define BIF_ets_match_spec_compile_1 280
#define BIF_ets_match_spec_run_r_3 281
#define BIF_os_putenv_2 282
#define BIF_os_getenv_0 283
#define BIF_os_getenv_1 284
#define BIF_os_getpid_0 285
#define BIF_os_timestamp_0 286
#define BIF_os_system_time_0 287
#define BIF_os_system_time_1 288
#define BIF_os_perf_counter_0 289
#define BIF_erl_ddll_try_load_3 290
#define BIF_erl_ddll_try_unload_2 291
#define BIF_erl_ddll_loaded_drivers_0 292
#define BIF_erl_ddll_info_2 293
#define BIF_erl_ddll_format_error_int_1 294
#define BIF_erl_ddll_monitor_2 295
#define BIF_erl_ddll_demonitor_1 296
#define BIF_re_version_0 297
#define BIF_re_compile_1 298
#define BIF_re_compile_2 299
#define BIF_re_run_2 300
#define BIF_re_run_3 301
#define BIF_lists_member_2 302
#define BIF_lists_reverse_2 303
#define BIF_lists_keymember_3 304
#define BIF_lists_keysearch_3 305
#define BIF_lists_keyfind_3 306
#define BIF_erts_debug_disassemble_1 307
#define BIF_erts_debug_breakpoint_2 308
#define BIF_erts_debug_same_2 309
#define BIF_erts_debug_flat_size_1 310
#define BIF_erts_debug_get_internal_state_1 311
#define BIF_erts_debug_set_internal_state_2 312
#define BIF_erts_debug_display_1 313
#define BIF_erts_debug_dist_ext_to_term_2 314
#define BIF_erts_debug_instructions_0 315
#define BIF_erts_debug_dirty_cpu_2 316
#define BIF_erts_debug_dirty_io_2 317
#define BIF_erts_debug_dirty_3 318
#define BIF_erts_debug_dump_monitors_1 319
#define BIF_erts_debug_dump_links_1 320
#define BIF_erts_debug_lock_counters_1 321
#define BIF_code_get_chunk_2 322
#define BIF_code_module_md5_1 323
#define BIF_code_make_stub_module_3 324
#define BIF_code_is_module_native_1 325
#define BIF_hibernate_3 326
#define BIF_error_logger_warning_map_0 327
#define BIF_get_module_info_1 328
#define BIF_get_module_info_2 329
#define BIF_is_boolean_1 330
#define BIF_string_list_to_integer_1 331
#define BIF_string_list_to_float_1 332
#define BIF_make_fun_3 333
#define BIF_iolist_size_1 334
#define BIF_iolist_to_binary_1 335
#define BIF_list_to_existing_atom_1 336
#define BIF_is_bitstring_1 337
#define BIF_tuple_size_1 338
#define BIF_byte_size_1 339
#define BIF_bit_size_1 340
#define BIF_list_to_bitstring_1 341
#define BIF_bitstring_to_list_1 342
#define BIF_ets_update_element_3 343
#define BIF_decode_packet_3 344
#define BIF_unicode_characters_to_binary_2 345
#define BIF_unicode_characters_to_list_2 346
#define BIF_unicode_bin_is_7bit_1 347
#define BIF_atom_to_binary_2 348
#define BIF_binary_to_atom_2 349
#define BIF_binary_to_existing_atom_2 350
#define BIF_net_kernel_dflag_unicode_io_1 351
#define BIF_ets_give_away_3 352
#define BIF_ets_setopts_2 353
#define BIF_load_nif_2 354
#define BIF_call_on_load_function_1 355
#define BIF_finish_after_on_load_2 356
#define BIF_binary_to_term_2 357
#define BIF_binary_part_2 358
#define BIF_binary_part_3 359
#define BIF_binary_compile_pattern_1 360
#define BIF_binary_match_2 361
#define BIF_binary_match_3 362
#define BIF_binary_matches_2 363
#define BIF_binary_matches_3 364
#define BIF_binary_longest_common_prefix_1 365
#define BIF_binary_longest_common_suffix_1 366
#define BIF_binary_first_1 367
#define BIF_binary_last_1 368
#define BIF_binary_at_2 369
#define BIF_binary_binary_part_2 370
#define BIF_binary_binary_part_3 371
#define BIF_binary_bin_to_list_1 372
#define BIF_binary_bin_to_list_2 373
#define BIF_binary_bin_to_list_3 374
#define BIF_binary_list_to_bin_1 375
#define BIF_binary_copy_1 376
#define BIF_binary_copy_2 377
#define BIF_binary_referenced_byte_size_1 378
#define BIF_binary_encode_unsigned_1 379
#define BIF_binary_encode_unsigned_2 380
#define BIF_binary_decode_unsigned_1 381
#define BIF_binary_decode_unsigned_2 382
#define BIF_nif_error_1 383
#define BIF_nif_error_2 384
#define BIF_prim_file_internal_name2native_1 385
#define BIF_prim_file_internal_native2name_1 386
#define BIF_prim_file_internal_normalize_utf8_1 387
#define BIF_prim_file_is_translatable_1 388
#define BIF_file_native_name_encoding_0 389
#define BIF_check_old_code_1 390
#define BIF_universaltime_to_posixtime_1 391
#define BIF_posixtime_to_universaltime_1 392
#define BIF_dt_put_tag_1 393
#define BIF_dt_get_tag_0 394
#define BIF_dt_get_tag_data_0 395
#define BIF_dt_spread_tag_1 396
#define BIF_dt_restore_tag_1 397
#define BIF_dt_prepend_vm_tag_data_1 398
#define BIF_dt_append_vm_tag_data_1 399
#define BIF_prepare_loading_2 400
#define BIF_finish_loading_1 401
#define BIF_insert_element_3 402
#define BIF_delete_element_2 403
#define BIF_binary_to_integer_1 404
#define BIF_binary_to_integer_2 405
#define BIF_integer_to_binary_1 406
#define BIF_list_to_integer_2 407
#define BIF_float_to_binary_1 408
#define BIF_float_to_binary_2 409
#define BIF_binary_to_float_1 410
#define BIF_io_printable_range_0 411
#define BIF_os_unsetenv_1 412
#define BIF_re_inspect_2 413
#define BIF_is_map_1 414
#define BIF_map_size_1 415
#define BIF_maps_to_list_1 416
#define BIF_maps_find_2 417
#define BIF_maps_get_2 418
#define BIF_maps_from_list_1 419
#define BIF_maps_is_key_2 420
#define BIF_maps_keys_1 421
#define BIF_maps_merge_2 422
#define BIF_maps_new_0 423
#define BIF_maps_put_3 424
#define BIF_maps_remove_2 425
#define BIF_maps_update_3 426
#define BIF_maps_values_1 427
#define BIF_erts_internal_cmp_term_2 428
#define BIF_ets_take_2 429
#define BIF_fun_info_mfa_1 430
#define BIF_get_keys_0 431
#define BIF_ets_update_counter_4 432
#define BIF_erts_debug_map_info_1 433
#define BIF_erts_internal_is_process_executing_dirty_1 434
#define BIF_erts_internal_check_dirty_process_code_2 435
#define BIF_erts_internal_purge_module_2 436
#define BIF_binary_split_2 437
#define BIF_binary_split_3 438
#define BIF_erts_debug_size_shared_1 439
#define BIF_erts_debug_copy_shared_1 440
#define BIF_has_prepared_code_on_load_1 441
#define BIF_maps_take_2 442
#define BIF_floor_1 443
#define BIF_ceil_1 444
#define BIF_math_floor_1 445
#define BIF_math_ceil_1 446
#define BIF_math_fmod_2 447
#define BIF_os_set_signal_2 448
#define BIF_erts_internal_maps_to_list_2 449
#define BIF_hipe_bifs_write_u8_2 450
#define BIF_hipe_bifs_write_u32_2 451
#define BIF_hipe_bifs_bytearray_2 452
#define BIF_hipe_bifs_bytearray_sub_2 453
#define BIF_hipe_bifs_bytearray_update_3 454
#define BIF_hipe_bifs_bitarray_2 455
#define BIF_hipe_bifs_bitarray_sub_2 456
#define BIF_hipe_bifs_bitarray_update_3 457
#define BIF_hipe_bifs_array_2 458
#define BIF_hipe_bifs_array_length_1 459
#define BIF_hipe_bifs_array_sub_2 460
#define BIF_hipe_bifs_array_update_3 461
#define BIF_hipe_bifs_ref_1 462
#define BIF_hipe_bifs_ref_get_1 463
#define BIF_hipe_bifs_ref_set_2 464
#define BIF_hipe_bifs_enter_code_3 465
#define BIF_hipe_bifs_alloc_data_3 466
#define BIF_hipe_bifs_constants_size_0 467
#define BIF_hipe_bifs_merge_term_1 468
#define BIF_hipe_bifs_fun_to_address_1 469
#define BIF_hipe_bifs_commit_patch_load_1 470
#define BIF_hipe_bifs_set_native_address_3 471
#define BIF_hipe_bifs_set_funinfo_native_address_3 472
#define BIF_hipe_bifs_enter_sdesc_2 473
#define BIF_hipe_bifs_bif_address_3 474
#define BIF_hipe_bifs_primop_address_1 475
#define BIF_hipe_bifs_atom_to_word_1 476
#define BIF_hipe_bifs_term_to_word_1 477
#define BIF_hipe_bifs_get_fe_2 478
#define BIF_hipe_bifs_set_native_address_in_fe_2 479
#define BIF_hipe_bifs_find_na_or_make_stub_1 480
#define BIF_hipe_bifs_check_crc_1 481
#define BIF_hipe_bifs_system_crc_0 482
#define BIF_hipe_bifs_get_rts_param_1 483
#define BIF_hipe_bifs_patch_insn_3 484
#define BIF_hipe_bifs_patch_call_3 485
#define BIF_hipe_bifs_add_ref_2 486
#define BIF_hipe_bifs_alloc_loader_state_1 487
#define BIF_hipe_bifs_call_count_on_1 488
#define BIF_hipe_bifs_call_count_off_1 489
#define BIF_hipe_bifs_call_count_get_1 490
#define BIF_hipe_bifs_call_count_clear_1 491
#define BIF_hipe_bifs_trap_count_get_0 492
#define BIF_hipe_bifs_trap_count_clear_0 493
#define BIF_hipe_bifs_show_estack_1 494
#define BIF_hipe_bifs_show_heap_1 495
#define BIF_hipe_bifs_show_nstack_1 496
#define BIF_hipe_bifs_nstack_used_size_0 497
#define BIF_hipe_bifs_show_pcb_1 498
#define BIF_hipe_bifs_show_term_1 499
#define BIF_hipe_bifs_in_native_0 500
#define BIF_hipe_bifs_modeswitch_debug_on_0 501
#define BIF_hipe_bifs_modeswitch_debug_off_0 502
#define BIF_hipe_bifs_debug_native_called_2 503
#define BIF_hipe_bifs_llvm_fix_pinned_regs_0 504
#define BIF_hipe_bifs_write_u64_2 505

Eterm abs_1(Process*, Eterm*, UWord*);
Eterm wrap_abs_1(Process*, Eterm*, UWord*);
Eterm erts_gc_abs_1(Process* p, Eterm* reg, Uint live);

Eterm adler32_1(Process*, Eterm*, UWord*);
Eterm wrap_adler32_1(Process*, Eterm*, UWord*);

Eterm adler32_2(Process*, Eterm*, UWord*);
Eterm wrap_adler32_2(Process*, Eterm*, UWord*);

Eterm adler32_combine_3(Process*, Eterm*, UWord*);
Eterm wrap_adler32_combine_3(Process*, Eterm*, UWord*);

Eterm apply_3(Process*, Eterm*, UWord*);
Eterm wrap_apply_3(Process*, Eterm*, UWord*);

Eterm atom_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_atom_to_list_1(Process*, Eterm*, UWord*);

Eterm binary_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_to_list_1(Process*, Eterm*, UWord*);

Eterm binary_to_list_3(Process*, Eterm*, UWord*);
Eterm wrap_binary_to_list_3(Process*, Eterm*, UWord*);

Eterm binary_to_term_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_to_term_1(Process*, Eterm*, UWord*);

Eterm crc32_1(Process*, Eterm*, UWord*);
Eterm wrap_crc32_1(Process*, Eterm*, UWord*);

Eterm crc32_2(Process*, Eterm*, UWord*);
Eterm wrap_crc32_2(Process*, Eterm*, UWord*);

Eterm crc32_combine_3(Process*, Eterm*, UWord*);
Eterm wrap_crc32_combine_3(Process*, Eterm*, UWord*);

Eterm date_0(Process*, Eterm*, UWord*);
Eterm wrap_date_0(Process*, Eterm*, UWord*);

Eterm delete_module_1(Process*, Eterm*, UWord*);
Eterm wrap_delete_module_1(Process*, Eterm*, UWord*);

Eterm display_1(Process*, Eterm*, UWord*);
Eterm wrap_display_1(Process*, Eterm*, UWord*);

Eterm display_string_1(Process*, Eterm*, UWord*);
Eterm wrap_display_string_1(Process*, Eterm*, UWord*);

Eterm display_nl_0(Process*, Eterm*, UWord*);
Eterm wrap_display_nl_0(Process*, Eterm*, UWord*);

Eterm element_2(Process*, Eterm*, UWord*);
Eterm wrap_element_2(Process*, Eterm*, UWord*);

Eterm erase_0(Process*, Eterm*, UWord*);
Eterm wrap_erase_0(Process*, Eterm*, UWord*);

Eterm erase_1(Process*, Eterm*, UWord*);
Eterm wrap_erase_1(Process*, Eterm*, UWord*);

Eterm exit_1(Process*, Eterm*, UWord*);
Eterm wrap_exit_1(Process*, Eterm*, UWord*);

Eterm exit_2(Process*, Eterm*, UWord*);
Eterm wrap_exit_2(Process*, Eterm*, UWord*);

Eterm external_size_1(Process*, Eterm*, UWord*);
Eterm wrap_external_size_1(Process*, Eterm*, UWord*);

Eterm external_size_2(Process*, Eterm*, UWord*);
Eterm wrap_external_size_2(Process*, Eterm*, UWord*);

Eterm float_1(Process*, Eterm*, UWord*);
Eterm wrap_float_1(Process*, Eterm*, UWord*);
Eterm erts_gc_float_1(Process* p, Eterm* reg, Uint live);

Eterm float_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_float_to_list_1(Process*, Eterm*, UWord*);

Eterm float_to_list_2(Process*, Eterm*, UWord*);
Eterm wrap_float_to_list_2(Process*, Eterm*, UWord*);

Eterm fun_info_2(Process*, Eterm*, UWord*);
Eterm wrap_fun_info_2(Process*, Eterm*, UWord*);

Eterm erts_internal_garbage_collect_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_garbage_collect_1(Process*, Eterm*, UWord*);

Eterm get_0(Process*, Eterm*, UWord*);
Eterm wrap_get_0(Process*, Eterm*, UWord*);

Eterm get_1(Process*, Eterm*, UWord*);
Eterm wrap_get_1(Process*, Eterm*, UWord*);

Eterm get_keys_1(Process*, Eterm*, UWord*);
Eterm wrap_get_keys_1(Process*, Eterm*, UWord*);

Eterm group_leader_0(Process*, Eterm*, UWord*);
Eterm wrap_group_leader_0(Process*, Eterm*, UWord*);

Eterm group_leader_2(Process*, Eterm*, UWord*);
Eterm wrap_group_leader_2(Process*, Eterm*, UWord*);

Eterm halt_2(Process*, Eterm*, UWord*);
Eterm wrap_halt_2(Process*, Eterm*, UWord*);

Eterm phash_2(Process*, Eterm*, UWord*);
Eterm wrap_phash_2(Process*, Eterm*, UWord*);

Eterm phash2_1(Process*, Eterm*, UWord*);
Eterm wrap_phash2_1(Process*, Eterm*, UWord*);

Eterm phash2_2(Process*, Eterm*, UWord*);
Eterm wrap_phash2_2(Process*, Eterm*, UWord*);

Eterm hd_1(Process*, Eterm*, UWord*);
Eterm wrap_hd_1(Process*, Eterm*, UWord*);

Eterm integer_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_integer_to_list_1(Process*, Eterm*, UWord*);

Eterm is_alive_0(Process*, Eterm*, UWord*);
Eterm wrap_is_alive_0(Process*, Eterm*, UWord*);

Eterm length_1(Process*, Eterm*, UWord*);
Eterm wrap_length_1(Process*, Eterm*, UWord*);
Eterm erts_gc_length_1(Process* p, Eterm* reg, Uint live);

Eterm link_1(Process*, Eterm*, UWord*);
Eterm wrap_link_1(Process*, Eterm*, UWord*);

Eterm list_to_atom_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_atom_1(Process*, Eterm*, UWord*);

Eterm list_to_binary_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_binary_1(Process*, Eterm*, UWord*);

Eterm list_to_float_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_float_1(Process*, Eterm*, UWord*);

Eterm list_to_integer_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_integer_1(Process*, Eterm*, UWord*);

Eterm list_to_pid_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_pid_1(Process*, Eterm*, UWord*);

Eterm list_to_port_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_port_1(Process*, Eterm*, UWord*);

Eterm list_to_ref_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_ref_1(Process*, Eterm*, UWord*);

Eterm list_to_tuple_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_tuple_1(Process*, Eterm*, UWord*);

Eterm loaded_0(Process*, Eterm*, UWord*);
Eterm wrap_loaded_0(Process*, Eterm*, UWord*);

Eterm localtime_0(Process*, Eterm*, UWord*);
Eterm wrap_localtime_0(Process*, Eterm*, UWord*);

Eterm localtime_to_universaltime_2(Process*, Eterm*, UWord*);
Eterm wrap_localtime_to_universaltime_2(Process*, Eterm*, UWord*);

Eterm make_ref_0(Process*, Eterm*, UWord*);
Eterm wrap_make_ref_0(Process*, Eterm*, UWord*);

Eterm unique_integer_0(Process*, Eterm*, UWord*);
Eterm wrap_unique_integer_0(Process*, Eterm*, UWord*);

Eterm unique_integer_1(Process*, Eterm*, UWord*);
Eterm wrap_unique_integer_1(Process*, Eterm*, UWord*);

Eterm md5_1(Process*, Eterm*, UWord*);
Eterm wrap_md5_1(Process*, Eterm*, UWord*);

Eterm md5_init_0(Process*, Eterm*, UWord*);
Eterm wrap_md5_init_0(Process*, Eterm*, UWord*);

Eterm md5_update_2(Process*, Eterm*, UWord*);
Eterm wrap_md5_update_2(Process*, Eterm*, UWord*);

Eterm md5_final_1(Process*, Eterm*, UWord*);
Eterm wrap_md5_final_1(Process*, Eterm*, UWord*);

Eterm module_loaded_1(Process*, Eterm*, UWord*);
Eterm wrap_module_loaded_1(Process*, Eterm*, UWord*);

Eterm function_exported_3(Process*, Eterm*, UWord*);
Eterm wrap_function_exported_3(Process*, Eterm*, UWord*);

Eterm monitor_node_2(Process*, Eterm*, UWord*);
Eterm wrap_monitor_node_2(Process*, Eterm*, UWord*);

Eterm monitor_node_3(Process*, Eterm*, UWord*);
Eterm wrap_monitor_node_3(Process*, Eterm*, UWord*);

Eterm node_1(Process*, Eterm*, UWord*);
Eterm wrap_node_1(Process*, Eterm*, UWord*);

Eterm node_0(Process*, Eterm*, UWord*);
Eterm wrap_node_0(Process*, Eterm*, UWord*);

Eterm nodes_1(Process*, Eterm*, UWord*);
Eterm wrap_nodes_1(Process*, Eterm*, UWord*);

Eterm now_0(Process*, Eterm*, UWord*);
Eterm wrap_now_0(Process*, Eterm*, UWord*);

Eterm monotonic_time_0(Process*, Eterm*, UWord*);
Eterm wrap_monotonic_time_0(Process*, Eterm*, UWord*);

Eterm monotonic_time_1(Process*, Eterm*, UWord*);
Eterm wrap_monotonic_time_1(Process*, Eterm*, UWord*);

Eterm system_time_0(Process*, Eterm*, UWord*);
Eterm wrap_system_time_0(Process*, Eterm*, UWord*);

Eterm system_time_1(Process*, Eterm*, UWord*);
Eterm wrap_system_time_1(Process*, Eterm*, UWord*);

Eterm time_offset_0(Process*, Eterm*, UWord*);
Eterm wrap_time_offset_0(Process*, Eterm*, UWord*);

Eterm time_offset_1(Process*, Eterm*, UWord*);
Eterm wrap_time_offset_1(Process*, Eterm*, UWord*);

Eterm timestamp_0(Process*, Eterm*, UWord*);
Eterm wrap_timestamp_0(Process*, Eterm*, UWord*);

Eterm erts_internal_open_port_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_open_port_2(Process*, Eterm*, UWord*);

Eterm pid_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_pid_to_list_1(Process*, Eterm*, UWord*);

Eterm ports_0(Process*, Eterm*, UWord*);
Eterm wrap_ports_0(Process*, Eterm*, UWord*);

Eterm pre_loaded_0(Process*, Eterm*, UWord*);
Eterm wrap_pre_loaded_0(Process*, Eterm*, UWord*);

Eterm process_flag_2(Process*, Eterm*, UWord*);
Eterm wrap_process_flag_2(Process*, Eterm*, UWord*);

Eterm process_flag_3(Process*, Eterm*, UWord*);
Eterm wrap_process_flag_3(Process*, Eterm*, UWord*);

Eterm process_info_1(Process*, Eterm*, UWord*);
Eterm wrap_process_info_1(Process*, Eterm*, UWord*);

Eterm process_info_2(Process*, Eterm*, UWord*);
Eterm wrap_process_info_2(Process*, Eterm*, UWord*);

Eterm processes_0(Process*, Eterm*, UWord*);
Eterm wrap_processes_0(Process*, Eterm*, UWord*);

Eterm put_2(Process*, Eterm*, UWord*);
Eterm wrap_put_2(Process*, Eterm*, UWord*);

Eterm register_2(Process*, Eterm*, UWord*);
Eterm wrap_register_2(Process*, Eterm*, UWord*);

Eterm registered_0(Process*, Eterm*, UWord*);
Eterm wrap_registered_0(Process*, Eterm*, UWord*);

Eterm round_1(Process*, Eterm*, UWord*);
Eterm wrap_round_1(Process*, Eterm*, UWord*);
Eterm erts_gc_round_1(Process* p, Eterm* reg, Uint live);

Eterm self_0(Process*, Eterm*, UWord*);
Eterm wrap_self_0(Process*, Eterm*, UWord*);

Eterm setelement_3(Process*, Eterm*, UWord*);
Eterm wrap_setelement_3(Process*, Eterm*, UWord*);

Eterm size_1(Process*, Eterm*, UWord*);
Eterm wrap_size_1(Process*, Eterm*, UWord*);
Eterm erts_gc_size_1(Process* p, Eterm* reg, Uint live);

Eterm spawn_3(Process*, Eterm*, UWord*);
Eterm wrap_spawn_3(Process*, Eterm*, UWord*);

Eterm spawn_link_3(Process*, Eterm*, UWord*);
Eterm wrap_spawn_link_3(Process*, Eterm*, UWord*);

Eterm split_binary_2(Process*, Eterm*, UWord*);
Eterm wrap_split_binary_2(Process*, Eterm*, UWord*);

Eterm statistics_1(Process*, Eterm*, UWord*);
Eterm wrap_statistics_1(Process*, Eterm*, UWord*);

Eterm term_to_binary_1(Process*, Eterm*, UWord*);
Eterm wrap_term_to_binary_1(Process*, Eterm*, UWord*);

Eterm term_to_binary_2(Process*, Eterm*, UWord*);
Eterm wrap_term_to_binary_2(Process*, Eterm*, UWord*);

Eterm throw_1(Process*, Eterm*, UWord*);
Eterm wrap_throw_1(Process*, Eterm*, UWord*);

Eterm time_0(Process*, Eterm*, UWord*);
Eterm wrap_time_0(Process*, Eterm*, UWord*);

Eterm tl_1(Process*, Eterm*, UWord*);
Eterm wrap_tl_1(Process*, Eterm*, UWord*);

Eterm trunc_1(Process*, Eterm*, UWord*);
Eterm wrap_trunc_1(Process*, Eterm*, UWord*);
Eterm erts_gc_trunc_1(Process* p, Eterm* reg, Uint live);

Eterm tuple_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_tuple_to_list_1(Process*, Eterm*, UWord*);

Eterm universaltime_0(Process*, Eterm*, UWord*);
Eterm wrap_universaltime_0(Process*, Eterm*, UWord*);

Eterm universaltime_to_localtime_1(Process*, Eterm*, UWord*);
Eterm wrap_universaltime_to_localtime_1(Process*, Eterm*, UWord*);

Eterm unlink_1(Process*, Eterm*, UWord*);
Eterm wrap_unlink_1(Process*, Eterm*, UWord*);

Eterm unregister_1(Process*, Eterm*, UWord*);
Eterm wrap_unregister_1(Process*, Eterm*, UWord*);

Eterm whereis_1(Process*, Eterm*, UWord*);
Eterm wrap_whereis_1(Process*, Eterm*, UWord*);

Eterm spawn_opt_1(Process*, Eterm*, UWord*);
Eterm wrap_spawn_opt_1(Process*, Eterm*, UWord*);

Eterm setnode_2(Process*, Eterm*, UWord*);
Eterm wrap_setnode_2(Process*, Eterm*, UWord*);

Eterm setnode_3(Process*, Eterm*, UWord*);
Eterm wrap_setnode_3(Process*, Eterm*, UWord*);

Eterm dist_exit_3(Process*, Eterm*, UWord*);
Eterm wrap_dist_exit_3(Process*, Eterm*, UWord*);

Eterm erts_internal_port_info_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_port_info_1(Process*, Eterm*, UWord*);

Eterm erts_internal_port_info_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_port_info_2(Process*, Eterm*, UWord*);

Eterm erts_internal_port_call_3(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_port_call_3(Process*, Eterm*, UWord*);

Eterm erts_internal_port_command_3(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_port_command_3(Process*, Eterm*, UWord*);

Eterm erts_internal_port_control_3(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_port_control_3(Process*, Eterm*, UWord*);

Eterm erts_internal_port_close_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_port_close_1(Process*, Eterm*, UWord*);

Eterm erts_internal_port_connect_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_port_connect_2(Process*, Eterm*, UWord*);

Eterm erts_internal_request_system_task_3(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_request_system_task_3(Process*, Eterm*, UWord*);

Eterm erts_internal_request_system_task_4(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_request_system_task_4(Process*, Eterm*, UWord*);

Eterm erts_internal_check_process_code_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_check_process_code_1(Process*, Eterm*, UWord*);

Eterm erts_internal_map_to_tuple_keys_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_map_to_tuple_keys_1(Process*, Eterm*, UWord*);

Eterm erts_internal_term_type_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_term_type_1(Process*, Eterm*, UWord*);

Eterm erts_internal_map_hashmap_children_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_map_hashmap_children_1(Process*, Eterm*, UWord*);

Eterm erts_internal_time_unit_0(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_time_unit_0(Process*, Eterm*, UWord*);

Eterm erts_internal_perf_counter_unit_0(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_perf_counter_unit_0(Process*, Eterm*, UWord*);

Eterm erts_internal_is_system_process_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_is_system_process_1(Process*, Eterm*, UWord*);

Eterm erts_internal_system_check_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_system_check_1(Process*, Eterm*, UWord*);

Eterm erts_internal_release_literal_area_switch_0(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_release_literal_area_switch_0(Process*, Eterm*, UWord*);

Eterm port_set_data_2(Process*, Eterm*, UWord*);
Eterm wrap_port_set_data_2(Process*, Eterm*, UWord*);

Eterm port_get_data_1(Process*, Eterm*, UWord*);
Eterm wrap_port_get_data_1(Process*, Eterm*, UWord*);

Eterm erts_internal_trace_pattern_3(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_trace_pattern_3(Process*, Eterm*, UWord*);

Eterm erts_internal_trace_3(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_trace_3(Process*, Eterm*, UWord*);

Eterm trace_info_2(Process*, Eterm*, UWord*);
Eterm wrap_trace_info_2(Process*, Eterm*, UWord*);

Eterm trace_delivered_1(Process*, Eterm*, UWord*);
Eterm wrap_trace_delivered_1(Process*, Eterm*, UWord*);

Eterm seq_trace_2(Process*, Eterm*, UWord*);
Eterm wrap_seq_trace_2(Process*, Eterm*, UWord*);

Eterm seq_trace_info_1(Process*, Eterm*, UWord*);
Eterm wrap_seq_trace_info_1(Process*, Eterm*, UWord*);

Eterm seq_trace_print_1(Process*, Eterm*, UWord*);
Eterm wrap_seq_trace_print_1(Process*, Eterm*, UWord*);

Eterm seq_trace_print_2(Process*, Eterm*, UWord*);
Eterm wrap_seq_trace_print_2(Process*, Eterm*, UWord*);

Eterm suspend_process_2(Process*, Eterm*, UWord*);
Eterm wrap_suspend_process_2(Process*, Eterm*, UWord*);

Eterm resume_process_1(Process*, Eterm*, UWord*);
Eterm wrap_resume_process_1(Process*, Eterm*, UWord*);

Eterm process_display_2(Process*, Eterm*, UWord*);
Eterm wrap_process_display_2(Process*, Eterm*, UWord*);

Eterm bump_reductions_1(Process*, Eterm*, UWord*);
Eterm wrap_bump_reductions_1(Process*, Eterm*, UWord*);

Eterm math_cos_1(Process*, Eterm*, UWord*);
Eterm wrap_math_cos_1(Process*, Eterm*, UWord*);

Eterm math_cosh_1(Process*, Eterm*, UWord*);
Eterm wrap_math_cosh_1(Process*, Eterm*, UWord*);

Eterm math_sin_1(Process*, Eterm*, UWord*);
Eterm wrap_math_sin_1(Process*, Eterm*, UWord*);

Eterm math_sinh_1(Process*, Eterm*, UWord*);
Eterm wrap_math_sinh_1(Process*, Eterm*, UWord*);

Eterm math_tan_1(Process*, Eterm*, UWord*);
Eterm wrap_math_tan_1(Process*, Eterm*, UWord*);

Eterm math_tanh_1(Process*, Eterm*, UWord*);
Eterm wrap_math_tanh_1(Process*, Eterm*, UWord*);

Eterm math_acos_1(Process*, Eterm*, UWord*);
Eterm wrap_math_acos_1(Process*, Eterm*, UWord*);

Eterm math_acosh_1(Process*, Eterm*, UWord*);
Eterm wrap_math_acosh_1(Process*, Eterm*, UWord*);

Eterm math_asin_1(Process*, Eterm*, UWord*);
Eterm wrap_math_asin_1(Process*, Eterm*, UWord*);

Eterm math_asinh_1(Process*, Eterm*, UWord*);
Eterm wrap_math_asinh_1(Process*, Eterm*, UWord*);

Eterm math_atan_1(Process*, Eterm*, UWord*);
Eterm wrap_math_atan_1(Process*, Eterm*, UWord*);

Eterm math_atanh_1(Process*, Eterm*, UWord*);
Eterm wrap_math_atanh_1(Process*, Eterm*, UWord*);

Eterm math_erf_1(Process*, Eterm*, UWord*);
Eterm wrap_math_erf_1(Process*, Eterm*, UWord*);

Eterm math_erfc_1(Process*, Eterm*, UWord*);
Eterm wrap_math_erfc_1(Process*, Eterm*, UWord*);

Eterm math_exp_1(Process*, Eterm*, UWord*);
Eterm wrap_math_exp_1(Process*, Eterm*, UWord*);

Eterm math_log_1(Process*, Eterm*, UWord*);
Eterm wrap_math_log_1(Process*, Eterm*, UWord*);

Eterm math_log2_1(Process*, Eterm*, UWord*);
Eterm wrap_math_log2_1(Process*, Eterm*, UWord*);

Eterm math_log10_1(Process*, Eterm*, UWord*);
Eterm wrap_math_log10_1(Process*, Eterm*, UWord*);

Eterm math_sqrt_1(Process*, Eterm*, UWord*);
Eterm wrap_math_sqrt_1(Process*, Eterm*, UWord*);

Eterm math_atan2_2(Process*, Eterm*, UWord*);
Eterm wrap_math_atan2_2(Process*, Eterm*, UWord*);

Eterm math_pow_2(Process*, Eterm*, UWord*);
Eterm wrap_math_pow_2(Process*, Eterm*, UWord*);

Eterm start_timer_3(Process*, Eterm*, UWord*);
Eterm wrap_start_timer_3(Process*, Eterm*, UWord*);

Eterm start_timer_4(Process*, Eterm*, UWord*);
Eterm wrap_start_timer_4(Process*, Eterm*, UWord*);

Eterm send_after_3(Process*, Eterm*, UWord*);
Eterm wrap_send_after_3(Process*, Eterm*, UWord*);

Eterm send_after_4(Process*, Eterm*, UWord*);
Eterm wrap_send_after_4(Process*, Eterm*, UWord*);

Eterm cancel_timer_1(Process*, Eterm*, UWord*);
Eterm wrap_cancel_timer_1(Process*, Eterm*, UWord*);

Eterm cancel_timer_2(Process*, Eterm*, UWord*);
Eterm wrap_cancel_timer_2(Process*, Eterm*, UWord*);

Eterm read_timer_1(Process*, Eterm*, UWord*);
Eterm wrap_read_timer_1(Process*, Eterm*, UWord*);

Eterm read_timer_2(Process*, Eterm*, UWord*);
Eterm wrap_read_timer_2(Process*, Eterm*, UWord*);

Eterm make_tuple_2(Process*, Eterm*, UWord*);
Eterm wrap_make_tuple_2(Process*, Eterm*, UWord*);

Eterm append_element_2(Process*, Eterm*, UWord*);
Eterm wrap_append_element_2(Process*, Eterm*, UWord*);

Eterm make_tuple_3(Process*, Eterm*, UWord*);
Eterm wrap_make_tuple_3(Process*, Eterm*, UWord*);

Eterm system_flag_2(Process*, Eterm*, UWord*);
Eterm wrap_system_flag_2(Process*, Eterm*, UWord*);

Eterm system_info_1(Process*, Eterm*, UWord*);
Eterm wrap_system_info_1(Process*, Eterm*, UWord*);

Eterm system_monitor_0(Process*, Eterm*, UWord*);
Eterm wrap_system_monitor_0(Process*, Eterm*, UWord*);

Eterm system_monitor_1(Process*, Eterm*, UWord*);
Eterm wrap_system_monitor_1(Process*, Eterm*, UWord*);

Eterm system_monitor_2(Process*, Eterm*, UWord*);
Eterm wrap_system_monitor_2(Process*, Eterm*, UWord*);

Eterm system_profile_2(Process*, Eterm*, UWord*);
Eterm wrap_system_profile_2(Process*, Eterm*, UWord*);

Eterm system_profile_0(Process*, Eterm*, UWord*);
Eterm wrap_system_profile_0(Process*, Eterm*, UWord*);

Eterm ref_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_ref_to_list_1(Process*, Eterm*, UWord*);

Eterm port_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_port_to_list_1(Process*, Eterm*, UWord*);

Eterm fun_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_fun_to_list_1(Process*, Eterm*, UWord*);

Eterm monitor_2(Process*, Eterm*, UWord*);
Eterm wrap_monitor_2(Process*, Eterm*, UWord*);

Eterm demonitor_1(Process*, Eterm*, UWord*);
Eterm wrap_demonitor_1(Process*, Eterm*, UWord*);

Eterm demonitor_2(Process*, Eterm*, UWord*);
Eterm wrap_demonitor_2(Process*, Eterm*, UWord*);

Eterm is_process_alive_1(Process*, Eterm*, UWord*);
Eterm wrap_is_process_alive_1(Process*, Eterm*, UWord*);

Eterm error_1(Process*, Eterm*, UWord*);
Eterm wrap_error_1(Process*, Eterm*, UWord*);

Eterm error_2(Process*, Eterm*, UWord*);
Eterm wrap_error_2(Process*, Eterm*, UWord*);

Eterm raise_3(Process*, Eterm*, UWord*);
Eterm wrap_raise_3(Process*, Eterm*, UWord*);

Eterm get_stacktrace_0(Process*, Eterm*, UWord*);
Eterm wrap_get_stacktrace_0(Process*, Eterm*, UWord*);

Eterm is_builtin_3(Process*, Eterm*, UWord*);
Eterm wrap_is_builtin_3(Process*, Eterm*, UWord*);

Eterm and_2(Process*, Eterm*, UWord*);
Eterm wrap_and_2(Process*, Eterm*, UWord*);

Eterm or_2(Process*, Eterm*, UWord*);
Eterm wrap_or_2(Process*, Eterm*, UWord*);

Eterm xor_2(Process*, Eterm*, UWord*);
Eterm wrap_xor_2(Process*, Eterm*, UWord*);

Eterm not_1(Process*, Eterm*, UWord*);
Eterm wrap_not_1(Process*, Eterm*, UWord*);

Eterm sgt_2(Process*, Eterm*, UWord*);
Eterm wrap_sgt_2(Process*, Eterm*, UWord*);

Eterm sge_2(Process*, Eterm*, UWord*);
Eterm wrap_sge_2(Process*, Eterm*, UWord*);

Eterm slt_2(Process*, Eterm*, UWord*);
Eterm wrap_slt_2(Process*, Eterm*, UWord*);

Eterm sle_2(Process*, Eterm*, UWord*);
Eterm wrap_sle_2(Process*, Eterm*, UWord*);

Eterm seq_2(Process*, Eterm*, UWord*);
Eterm wrap_seq_2(Process*, Eterm*, UWord*);

Eterm seqeq_2(Process*, Eterm*, UWord*);
Eterm wrap_seqeq_2(Process*, Eterm*, UWord*);

Eterm sneq_2(Process*, Eterm*, UWord*);
Eterm wrap_sneq_2(Process*, Eterm*, UWord*);

Eterm sneqeq_2(Process*, Eterm*, UWord*);
Eterm wrap_sneqeq_2(Process*, Eterm*, UWord*);

Eterm splus_2(Process*, Eterm*, UWord*);
Eterm wrap_splus_2(Process*, Eterm*, UWord*);

Eterm sminus_2(Process*, Eterm*, UWord*);
Eterm wrap_sminus_2(Process*, Eterm*, UWord*);

Eterm stimes_2(Process*, Eterm*, UWord*);
Eterm wrap_stimes_2(Process*, Eterm*, UWord*);

Eterm div_2(Process*, Eterm*, UWord*);
Eterm wrap_div_2(Process*, Eterm*, UWord*);

Eterm intdiv_2(Process*, Eterm*, UWord*);
Eterm wrap_intdiv_2(Process*, Eterm*, UWord*);

Eterm rem_2(Process*, Eterm*, UWord*);
Eterm wrap_rem_2(Process*, Eterm*, UWord*);

Eterm bor_2(Process*, Eterm*, UWord*);
Eterm wrap_bor_2(Process*, Eterm*, UWord*);

Eterm band_2(Process*, Eterm*, UWord*);
Eterm wrap_band_2(Process*, Eterm*, UWord*);

Eterm bxor_2(Process*, Eterm*, UWord*);
Eterm wrap_bxor_2(Process*, Eterm*, UWord*);

Eterm bsl_2(Process*, Eterm*, UWord*);
Eterm wrap_bsl_2(Process*, Eterm*, UWord*);

Eterm bsr_2(Process*, Eterm*, UWord*);
Eterm wrap_bsr_2(Process*, Eterm*, UWord*);

Eterm bnot_1(Process*, Eterm*, UWord*);
Eterm wrap_bnot_1(Process*, Eterm*, UWord*);

Eterm sminus_1(Process*, Eterm*, UWord*);
Eterm wrap_sminus_1(Process*, Eterm*, UWord*);

Eterm splus_1(Process*, Eterm*, UWord*);
Eterm wrap_splus_1(Process*, Eterm*, UWord*);

Eterm ebif_bang_2(Process*, Eterm*, UWord*);
Eterm wrap_ebif_bang_2(Process*, Eterm*, UWord*);

Eterm send_2(Process*, Eterm*, UWord*);
Eterm wrap_send_2(Process*, Eterm*, UWord*);

Eterm send_3(Process*, Eterm*, UWord*);
Eterm wrap_send_3(Process*, Eterm*, UWord*);

Eterm ebif_plusplus_2(Process*, Eterm*, UWord*);
Eterm wrap_ebif_plusplus_2(Process*, Eterm*, UWord*);

Eterm append_2(Process*, Eterm*, UWord*);
Eterm wrap_append_2(Process*, Eterm*, UWord*);

Eterm ebif_minusminus_2(Process*, Eterm*, UWord*);
Eterm wrap_ebif_minusminus_2(Process*, Eterm*, UWord*);

Eterm subtract_2(Process*, Eterm*, UWord*);
Eterm wrap_subtract_2(Process*, Eterm*, UWord*);

Eterm is_atom_1(Process*, Eterm*, UWord*);
Eterm wrap_is_atom_1(Process*, Eterm*, UWord*);

Eterm is_list_1(Process*, Eterm*, UWord*);
Eterm wrap_is_list_1(Process*, Eterm*, UWord*);

Eterm is_tuple_1(Process*, Eterm*, UWord*);
Eterm wrap_is_tuple_1(Process*, Eterm*, UWord*);

Eterm is_float_1(Process*, Eterm*, UWord*);
Eterm wrap_is_float_1(Process*, Eterm*, UWord*);

Eterm is_integer_1(Process*, Eterm*, UWord*);
Eterm wrap_is_integer_1(Process*, Eterm*, UWord*);

Eterm is_number_1(Process*, Eterm*, UWord*);
Eterm wrap_is_number_1(Process*, Eterm*, UWord*);

Eterm is_pid_1(Process*, Eterm*, UWord*);
Eterm wrap_is_pid_1(Process*, Eterm*, UWord*);

Eterm is_port_1(Process*, Eterm*, UWord*);
Eterm wrap_is_port_1(Process*, Eterm*, UWord*);

Eterm is_reference_1(Process*, Eterm*, UWord*);
Eterm wrap_is_reference_1(Process*, Eterm*, UWord*);

Eterm is_binary_1(Process*, Eterm*, UWord*);
Eterm wrap_is_binary_1(Process*, Eterm*, UWord*);

Eterm is_function_1(Process*, Eterm*, UWord*);
Eterm wrap_is_function_1(Process*, Eterm*, UWord*);

Eterm is_function_2(Process*, Eterm*, UWord*);
Eterm wrap_is_function_2(Process*, Eterm*, UWord*);

Eterm is_record_2(Process*, Eterm*, UWord*);
Eterm wrap_is_record_2(Process*, Eterm*, UWord*);

Eterm is_record_3(Process*, Eterm*, UWord*);
Eterm wrap_is_record_3(Process*, Eterm*, UWord*);

Eterm match_spec_test_3(Process*, Eterm*, UWord*);
Eterm wrap_match_spec_test_3(Process*, Eterm*, UWord*);

Eterm ets_internal_request_all_0(Process*, Eterm*, UWord*);
Eterm wrap_ets_internal_request_all_0(Process*, Eterm*, UWord*);

Eterm ets_new_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_new_2(Process*, Eterm*, UWord*);

Eterm ets_delete_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_delete_1(Process*, Eterm*, UWord*);

Eterm ets_delete_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_delete_2(Process*, Eterm*, UWord*);

Eterm ets_delete_all_objects_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_delete_all_objects_1(Process*, Eterm*, UWord*);

Eterm ets_delete_object_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_delete_object_2(Process*, Eterm*, UWord*);

Eterm ets_first_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_first_1(Process*, Eterm*, UWord*);

Eterm ets_is_compiled_ms_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_is_compiled_ms_1(Process*, Eterm*, UWord*);

Eterm ets_lookup_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_lookup_2(Process*, Eterm*, UWord*);

Eterm ets_lookup_element_3(Process*, Eterm*, UWord*);
Eterm wrap_ets_lookup_element_3(Process*, Eterm*, UWord*);

Eterm ets_info_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_info_1(Process*, Eterm*, UWord*);

Eterm ets_info_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_info_2(Process*, Eterm*, UWord*);

Eterm ets_last_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_last_1(Process*, Eterm*, UWord*);

Eterm ets_match_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_match_1(Process*, Eterm*, UWord*);

Eterm ets_match_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_match_2(Process*, Eterm*, UWord*);

Eterm ets_match_3(Process*, Eterm*, UWord*);
Eterm wrap_ets_match_3(Process*, Eterm*, UWord*);

Eterm ets_match_object_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_match_object_1(Process*, Eterm*, UWord*);

Eterm ets_match_object_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_match_object_2(Process*, Eterm*, UWord*);

Eterm ets_match_object_3(Process*, Eterm*, UWord*);
Eterm wrap_ets_match_object_3(Process*, Eterm*, UWord*);

Eterm ets_member_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_member_2(Process*, Eterm*, UWord*);

Eterm ets_next_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_next_2(Process*, Eterm*, UWord*);

Eterm ets_prev_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_prev_2(Process*, Eterm*, UWord*);

Eterm ets_insert_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_insert_2(Process*, Eterm*, UWord*);

Eterm ets_insert_new_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_insert_new_2(Process*, Eterm*, UWord*);

Eterm ets_rename_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_rename_2(Process*, Eterm*, UWord*);

Eterm ets_safe_fixtable_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_safe_fixtable_2(Process*, Eterm*, UWord*);

Eterm ets_slot_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_slot_2(Process*, Eterm*, UWord*);

Eterm ets_update_counter_3(Process*, Eterm*, UWord*);
Eterm wrap_ets_update_counter_3(Process*, Eterm*, UWord*);

Eterm ets_select_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_select_1(Process*, Eterm*, UWord*);

Eterm ets_select_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_select_2(Process*, Eterm*, UWord*);

Eterm ets_select_3(Process*, Eterm*, UWord*);
Eterm wrap_ets_select_3(Process*, Eterm*, UWord*);

Eterm ets_select_count_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_select_count_2(Process*, Eterm*, UWord*);

Eterm ets_select_reverse_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_select_reverse_1(Process*, Eterm*, UWord*);

Eterm ets_select_reverse_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_select_reverse_2(Process*, Eterm*, UWord*);

Eterm ets_select_reverse_3(Process*, Eterm*, UWord*);
Eterm wrap_ets_select_reverse_3(Process*, Eterm*, UWord*);

Eterm ets_select_delete_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_select_delete_2(Process*, Eterm*, UWord*);

Eterm ets_select_replace_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_select_replace_2(Process*, Eterm*, UWord*);

Eterm ets_match_spec_compile_1(Process*, Eterm*, UWord*);
Eterm wrap_ets_match_spec_compile_1(Process*, Eterm*, UWord*);

Eterm ets_match_spec_run_r_3(Process*, Eterm*, UWord*);
Eterm wrap_ets_match_spec_run_r_3(Process*, Eterm*, UWord*);

Eterm os_putenv_2(Process*, Eterm*, UWord*);
Eterm wrap_os_putenv_2(Process*, Eterm*, UWord*);

Eterm os_getenv_0(Process*, Eterm*, UWord*);
Eterm wrap_os_getenv_0(Process*, Eterm*, UWord*);

Eterm os_getenv_1(Process*, Eterm*, UWord*);
Eterm wrap_os_getenv_1(Process*, Eterm*, UWord*);

Eterm os_getpid_0(Process*, Eterm*, UWord*);
Eterm wrap_os_getpid_0(Process*, Eterm*, UWord*);

Eterm os_timestamp_0(Process*, Eterm*, UWord*);
Eterm wrap_os_timestamp_0(Process*, Eterm*, UWord*);

Eterm os_system_time_0(Process*, Eterm*, UWord*);
Eterm wrap_os_system_time_0(Process*, Eterm*, UWord*);

Eterm os_system_time_1(Process*, Eterm*, UWord*);
Eterm wrap_os_system_time_1(Process*, Eterm*, UWord*);

Eterm os_perf_counter_0(Process*, Eterm*, UWord*);
Eterm wrap_os_perf_counter_0(Process*, Eterm*, UWord*);

Eterm erl_ddll_try_load_3(Process*, Eterm*, UWord*);
Eterm wrap_erl_ddll_try_load_3(Process*, Eterm*, UWord*);

Eterm erl_ddll_try_unload_2(Process*, Eterm*, UWord*);
Eterm wrap_erl_ddll_try_unload_2(Process*, Eterm*, UWord*);

Eterm erl_ddll_loaded_drivers_0(Process*, Eterm*, UWord*);
Eterm wrap_erl_ddll_loaded_drivers_0(Process*, Eterm*, UWord*);

Eterm erl_ddll_info_2(Process*, Eterm*, UWord*);
Eterm wrap_erl_ddll_info_2(Process*, Eterm*, UWord*);

Eterm erl_ddll_format_error_int_1(Process*, Eterm*, UWord*);
Eterm wrap_erl_ddll_format_error_int_1(Process*, Eterm*, UWord*);

Eterm erl_ddll_monitor_2(Process*, Eterm*, UWord*);
Eterm wrap_erl_ddll_monitor_2(Process*, Eterm*, UWord*);

Eterm erl_ddll_demonitor_1(Process*, Eterm*, UWord*);
Eterm wrap_erl_ddll_demonitor_1(Process*, Eterm*, UWord*);

Eterm re_version_0(Process*, Eterm*, UWord*);
Eterm wrap_re_version_0(Process*, Eterm*, UWord*);

Eterm re_compile_1(Process*, Eterm*, UWord*);
Eterm wrap_re_compile_1(Process*, Eterm*, UWord*);

Eterm re_compile_2(Process*, Eterm*, UWord*);
Eterm wrap_re_compile_2(Process*, Eterm*, UWord*);

Eterm re_run_2(Process*, Eterm*, UWord*);
Eterm wrap_re_run_2(Process*, Eterm*, UWord*);

Eterm re_run_3(Process*, Eterm*, UWord*);
Eterm wrap_re_run_3(Process*, Eterm*, UWord*);

Eterm lists_member_2(Process*, Eterm*, UWord*);
Eterm wrap_lists_member_2(Process*, Eterm*, UWord*);

Eterm lists_reverse_2(Process*, Eterm*, UWord*);
Eterm wrap_lists_reverse_2(Process*, Eterm*, UWord*);

Eterm lists_keymember_3(Process*, Eterm*, UWord*);
Eterm wrap_lists_keymember_3(Process*, Eterm*, UWord*);

Eterm lists_keysearch_3(Process*, Eterm*, UWord*);
Eterm wrap_lists_keysearch_3(Process*, Eterm*, UWord*);

Eterm lists_keyfind_3(Process*, Eterm*, UWord*);
Eterm wrap_lists_keyfind_3(Process*, Eterm*, UWord*);

Eterm erts_debug_disassemble_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_disassemble_1(Process*, Eterm*, UWord*);

Eterm erts_debug_breakpoint_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_breakpoint_2(Process*, Eterm*, UWord*);

Eterm erts_debug_same_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_same_2(Process*, Eterm*, UWord*);

Eterm erts_debug_flat_size_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_flat_size_1(Process*, Eterm*, UWord*);

Eterm erts_debug_get_internal_state_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_get_internal_state_1(Process*, Eterm*, UWord*);

Eterm erts_debug_set_internal_state_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_set_internal_state_2(Process*, Eterm*, UWord*);

Eterm erts_debug_display_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_display_1(Process*, Eterm*, UWord*);

Eterm erts_debug_dist_ext_to_term_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_dist_ext_to_term_2(Process*, Eterm*, UWord*);

Eterm erts_debug_instructions_0(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_instructions_0(Process*, Eterm*, UWord*);

Eterm erts_debug_dirty_cpu_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_dirty_cpu_2(Process*, Eterm*, UWord*);
Eterm schedule_dirty_cpu_erts_debug_dirty_cpu_2(Process*, Eterm*, UWord*);

Eterm erts_debug_dirty_io_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_dirty_io_2(Process*, Eterm*, UWord*);
Eterm schedule_dirty_io_erts_debug_dirty_io_2(Process*, Eterm*, UWord*);

Eterm erts_debug_dirty_3(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_dirty_3(Process*, Eterm*, UWord*);

Eterm erts_debug_dump_monitors_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_dump_monitors_1(Process*, Eterm*, UWord*);

Eterm erts_debug_dump_links_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_dump_links_1(Process*, Eterm*, UWord*);

Eterm erts_debug_lock_counters_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_lock_counters_1(Process*, Eterm*, UWord*);

Eterm code_get_chunk_2(Process*, Eterm*, UWord*);
Eterm wrap_code_get_chunk_2(Process*, Eterm*, UWord*);

Eterm code_module_md5_1(Process*, Eterm*, UWord*);
Eterm wrap_code_module_md5_1(Process*, Eterm*, UWord*);

Eterm code_make_stub_module_3(Process*, Eterm*, UWord*);
Eterm wrap_code_make_stub_module_3(Process*, Eterm*, UWord*);

Eterm code_is_module_native_1(Process*, Eterm*, UWord*);
Eterm wrap_code_is_module_native_1(Process*, Eterm*, UWord*);

Eterm hibernate_3(Process*, Eterm*, UWord*);
Eterm wrap_hibernate_3(Process*, Eterm*, UWord*);

Eterm error_logger_warning_map_0(Process*, Eterm*, UWord*);
Eterm wrap_error_logger_warning_map_0(Process*, Eterm*, UWord*);

Eterm get_module_info_1(Process*, Eterm*, UWord*);
Eterm wrap_get_module_info_1(Process*, Eterm*, UWord*);

Eterm get_module_info_2(Process*, Eterm*, UWord*);
Eterm wrap_get_module_info_2(Process*, Eterm*, UWord*);

Eterm is_boolean_1(Process*, Eterm*, UWord*);
Eterm wrap_is_boolean_1(Process*, Eterm*, UWord*);

Eterm string_list_to_integer_1(Process*, Eterm*, UWord*);
Eterm wrap_string_list_to_integer_1(Process*, Eterm*, UWord*);

Eterm string_list_to_float_1(Process*, Eterm*, UWord*);
Eterm wrap_string_list_to_float_1(Process*, Eterm*, UWord*);

Eterm make_fun_3(Process*, Eterm*, UWord*);
Eterm wrap_make_fun_3(Process*, Eterm*, UWord*);

Eterm iolist_size_1(Process*, Eterm*, UWord*);
Eterm wrap_iolist_size_1(Process*, Eterm*, UWord*);

Eterm iolist_to_binary_1(Process*, Eterm*, UWord*);
Eterm wrap_iolist_to_binary_1(Process*, Eterm*, UWord*);

Eterm list_to_existing_atom_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_existing_atom_1(Process*, Eterm*, UWord*);

Eterm is_bitstring_1(Process*, Eterm*, UWord*);
Eterm wrap_is_bitstring_1(Process*, Eterm*, UWord*);

Eterm tuple_size_1(Process*, Eterm*, UWord*);
Eterm wrap_tuple_size_1(Process*, Eterm*, UWord*);

Eterm byte_size_1(Process*, Eterm*, UWord*);
Eterm wrap_byte_size_1(Process*, Eterm*, UWord*);
Eterm erts_gc_byte_size_1(Process* p, Eterm* reg, Uint live);

Eterm bit_size_1(Process*, Eterm*, UWord*);
Eterm wrap_bit_size_1(Process*, Eterm*, UWord*);
Eterm erts_gc_bit_size_1(Process* p, Eterm* reg, Uint live);

Eterm list_to_bitstring_1(Process*, Eterm*, UWord*);
Eterm wrap_list_to_bitstring_1(Process*, Eterm*, UWord*);

Eterm bitstring_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_bitstring_to_list_1(Process*, Eterm*, UWord*);

Eterm ets_update_element_3(Process*, Eterm*, UWord*);
Eterm wrap_ets_update_element_3(Process*, Eterm*, UWord*);

Eterm decode_packet_3(Process*, Eterm*, UWord*);
Eterm wrap_decode_packet_3(Process*, Eterm*, UWord*);

Eterm unicode_characters_to_binary_2(Process*, Eterm*, UWord*);
Eterm wrap_unicode_characters_to_binary_2(Process*, Eterm*, UWord*);

Eterm unicode_characters_to_list_2(Process*, Eterm*, UWord*);
Eterm wrap_unicode_characters_to_list_2(Process*, Eterm*, UWord*);

Eterm unicode_bin_is_7bit_1(Process*, Eterm*, UWord*);
Eterm wrap_unicode_bin_is_7bit_1(Process*, Eterm*, UWord*);

Eterm atom_to_binary_2(Process*, Eterm*, UWord*);
Eterm wrap_atom_to_binary_2(Process*, Eterm*, UWord*);

Eterm binary_to_atom_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_to_atom_2(Process*, Eterm*, UWord*);

Eterm binary_to_existing_atom_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_to_existing_atom_2(Process*, Eterm*, UWord*);

Eterm net_kernel_dflag_unicode_io_1(Process*, Eterm*, UWord*);
Eterm wrap_net_kernel_dflag_unicode_io_1(Process*, Eterm*, UWord*);

Eterm ets_give_away_3(Process*, Eterm*, UWord*);
Eterm wrap_ets_give_away_3(Process*, Eterm*, UWord*);

Eterm ets_setopts_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_setopts_2(Process*, Eterm*, UWord*);

Eterm load_nif_2(Process*, Eterm*, UWord*);
Eterm wrap_load_nif_2(Process*, Eterm*, UWord*);

Eterm call_on_load_function_1(Process*, Eterm*, UWord*);
Eterm wrap_call_on_load_function_1(Process*, Eterm*, UWord*);

Eterm finish_after_on_load_2(Process*, Eterm*, UWord*);
Eterm wrap_finish_after_on_load_2(Process*, Eterm*, UWord*);

Eterm binary_to_term_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_to_term_2(Process*, Eterm*, UWord*);

Eterm binary_part_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_part_2(Process*, Eterm*, UWord*);
Eterm erts_gc_binary_part_2(Process* p, Eterm* reg, Uint live);

Eterm binary_part_3(Process*, Eterm*, UWord*);
Eterm wrap_binary_part_3(Process*, Eterm*, UWord*);
Eterm erts_gc_binary_part_3(Process* p, Eterm* reg, Uint live);

Eterm binary_compile_pattern_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_compile_pattern_1(Process*, Eterm*, UWord*);

Eterm binary_match_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_match_2(Process*, Eterm*, UWord*);

Eterm binary_match_3(Process*, Eterm*, UWord*);
Eterm wrap_binary_match_3(Process*, Eterm*, UWord*);

Eterm binary_matches_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_matches_2(Process*, Eterm*, UWord*);

Eterm binary_matches_3(Process*, Eterm*, UWord*);
Eterm wrap_binary_matches_3(Process*, Eterm*, UWord*);

Eterm binary_longest_common_prefix_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_longest_common_prefix_1(Process*, Eterm*, UWord*);

Eterm binary_longest_common_suffix_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_longest_common_suffix_1(Process*, Eterm*, UWord*);

Eterm binary_first_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_first_1(Process*, Eterm*, UWord*);

Eterm binary_last_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_last_1(Process*, Eterm*, UWord*);

Eterm binary_at_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_at_2(Process*, Eterm*, UWord*);

Eterm binary_binary_part_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_binary_part_2(Process*, Eterm*, UWord*);

Eterm binary_binary_part_3(Process*, Eterm*, UWord*);
Eterm wrap_binary_binary_part_3(Process*, Eterm*, UWord*);

Eterm binary_bin_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_bin_to_list_1(Process*, Eterm*, UWord*);

Eterm binary_bin_to_list_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_bin_to_list_2(Process*, Eterm*, UWord*);

Eterm binary_bin_to_list_3(Process*, Eterm*, UWord*);
Eterm wrap_binary_bin_to_list_3(Process*, Eterm*, UWord*);

Eterm binary_list_to_bin_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_list_to_bin_1(Process*, Eterm*, UWord*);

Eterm binary_copy_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_copy_1(Process*, Eterm*, UWord*);

Eterm binary_copy_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_copy_2(Process*, Eterm*, UWord*);

Eterm binary_referenced_byte_size_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_referenced_byte_size_1(Process*, Eterm*, UWord*);

Eterm binary_encode_unsigned_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_encode_unsigned_1(Process*, Eterm*, UWord*);

Eterm binary_encode_unsigned_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_encode_unsigned_2(Process*, Eterm*, UWord*);

Eterm binary_decode_unsigned_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_decode_unsigned_1(Process*, Eterm*, UWord*);

Eterm binary_decode_unsigned_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_decode_unsigned_2(Process*, Eterm*, UWord*);

Eterm nif_error_1(Process*, Eterm*, UWord*);
Eterm wrap_nif_error_1(Process*, Eterm*, UWord*);

Eterm nif_error_2(Process*, Eterm*, UWord*);
Eterm wrap_nif_error_2(Process*, Eterm*, UWord*);

Eterm prim_file_internal_name2native_1(Process*, Eterm*, UWord*);
Eterm wrap_prim_file_internal_name2native_1(Process*, Eterm*, UWord*);

Eterm prim_file_internal_native2name_1(Process*, Eterm*, UWord*);
Eterm wrap_prim_file_internal_native2name_1(Process*, Eterm*, UWord*);

Eterm prim_file_internal_normalize_utf8_1(Process*, Eterm*, UWord*);
Eterm wrap_prim_file_internal_normalize_utf8_1(Process*, Eterm*, UWord*);

Eterm prim_file_is_translatable_1(Process*, Eterm*, UWord*);
Eterm wrap_prim_file_is_translatable_1(Process*, Eterm*, UWord*);

Eterm file_native_name_encoding_0(Process*, Eterm*, UWord*);
Eterm wrap_file_native_name_encoding_0(Process*, Eterm*, UWord*);

Eterm check_old_code_1(Process*, Eterm*, UWord*);
Eterm wrap_check_old_code_1(Process*, Eterm*, UWord*);

Eterm universaltime_to_posixtime_1(Process*, Eterm*, UWord*);
Eterm wrap_universaltime_to_posixtime_1(Process*, Eterm*, UWord*);

Eterm posixtime_to_universaltime_1(Process*, Eterm*, UWord*);
Eterm wrap_posixtime_to_universaltime_1(Process*, Eterm*, UWord*);

Eterm dt_put_tag_1(Process*, Eterm*, UWord*);
Eterm wrap_dt_put_tag_1(Process*, Eterm*, UWord*);

Eterm dt_get_tag_0(Process*, Eterm*, UWord*);
Eterm wrap_dt_get_tag_0(Process*, Eterm*, UWord*);

Eterm dt_get_tag_data_0(Process*, Eterm*, UWord*);
Eterm wrap_dt_get_tag_data_0(Process*, Eterm*, UWord*);

Eterm dt_spread_tag_1(Process*, Eterm*, UWord*);
Eterm wrap_dt_spread_tag_1(Process*, Eterm*, UWord*);

Eterm dt_restore_tag_1(Process*, Eterm*, UWord*);
Eterm wrap_dt_restore_tag_1(Process*, Eterm*, UWord*);

Eterm dt_prepend_vm_tag_data_1(Process*, Eterm*, UWord*);
Eterm wrap_dt_prepend_vm_tag_data_1(Process*, Eterm*, UWord*);

Eterm dt_append_vm_tag_data_1(Process*, Eterm*, UWord*);
Eterm wrap_dt_append_vm_tag_data_1(Process*, Eterm*, UWord*);

Eterm prepare_loading_2(Process*, Eterm*, UWord*);
Eterm wrap_prepare_loading_2(Process*, Eterm*, UWord*);

Eterm finish_loading_1(Process*, Eterm*, UWord*);
Eterm wrap_finish_loading_1(Process*, Eterm*, UWord*);

Eterm insert_element_3(Process*, Eterm*, UWord*);
Eterm wrap_insert_element_3(Process*, Eterm*, UWord*);

Eterm delete_element_2(Process*, Eterm*, UWord*);
Eterm wrap_delete_element_2(Process*, Eterm*, UWord*);

Eterm binary_to_integer_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_to_integer_1(Process*, Eterm*, UWord*);

Eterm binary_to_integer_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_to_integer_2(Process*, Eterm*, UWord*);

Eterm integer_to_binary_1(Process*, Eterm*, UWord*);
Eterm wrap_integer_to_binary_1(Process*, Eterm*, UWord*);

Eterm list_to_integer_2(Process*, Eterm*, UWord*);
Eterm wrap_list_to_integer_2(Process*, Eterm*, UWord*);

Eterm float_to_binary_1(Process*, Eterm*, UWord*);
Eterm wrap_float_to_binary_1(Process*, Eterm*, UWord*);

Eterm float_to_binary_2(Process*, Eterm*, UWord*);
Eterm wrap_float_to_binary_2(Process*, Eterm*, UWord*);

Eterm binary_to_float_1(Process*, Eterm*, UWord*);
Eterm wrap_binary_to_float_1(Process*, Eterm*, UWord*);

Eterm io_printable_range_0(Process*, Eterm*, UWord*);
Eterm wrap_io_printable_range_0(Process*, Eterm*, UWord*);

Eterm os_unsetenv_1(Process*, Eterm*, UWord*);
Eterm wrap_os_unsetenv_1(Process*, Eterm*, UWord*);

Eterm re_inspect_2(Process*, Eterm*, UWord*);
Eterm wrap_re_inspect_2(Process*, Eterm*, UWord*);

Eterm is_map_1(Process*, Eterm*, UWord*);
Eterm wrap_is_map_1(Process*, Eterm*, UWord*);

Eterm map_size_1(Process*, Eterm*, UWord*);
Eterm wrap_map_size_1(Process*, Eterm*, UWord*);
Eterm erts_gc_map_size_1(Process* p, Eterm* reg, Uint live);

Eterm maps_to_list_1(Process*, Eterm*, UWord*);
Eterm wrap_maps_to_list_1(Process*, Eterm*, UWord*);

Eterm maps_find_2(Process*, Eterm*, UWord*);
Eterm wrap_maps_find_2(Process*, Eterm*, UWord*);

Eterm maps_get_2(Process*, Eterm*, UWord*);
Eterm wrap_maps_get_2(Process*, Eterm*, UWord*);

Eterm maps_from_list_1(Process*, Eterm*, UWord*);
Eterm wrap_maps_from_list_1(Process*, Eterm*, UWord*);

Eterm maps_is_key_2(Process*, Eterm*, UWord*);
Eterm wrap_maps_is_key_2(Process*, Eterm*, UWord*);

Eterm maps_keys_1(Process*, Eterm*, UWord*);
Eterm wrap_maps_keys_1(Process*, Eterm*, UWord*);

Eterm maps_merge_2(Process*, Eterm*, UWord*);
Eterm wrap_maps_merge_2(Process*, Eterm*, UWord*);

Eterm maps_new_0(Process*, Eterm*, UWord*);
Eterm wrap_maps_new_0(Process*, Eterm*, UWord*);

Eterm maps_put_3(Process*, Eterm*, UWord*);
Eterm wrap_maps_put_3(Process*, Eterm*, UWord*);

Eterm maps_remove_2(Process*, Eterm*, UWord*);
Eterm wrap_maps_remove_2(Process*, Eterm*, UWord*);

Eterm maps_update_3(Process*, Eterm*, UWord*);
Eterm wrap_maps_update_3(Process*, Eterm*, UWord*);

Eterm maps_values_1(Process*, Eterm*, UWord*);
Eterm wrap_maps_values_1(Process*, Eterm*, UWord*);

Eterm erts_internal_cmp_term_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_cmp_term_2(Process*, Eterm*, UWord*);

Eterm ets_take_2(Process*, Eterm*, UWord*);
Eterm wrap_ets_take_2(Process*, Eterm*, UWord*);

Eterm fun_info_mfa_1(Process*, Eterm*, UWord*);
Eterm wrap_fun_info_mfa_1(Process*, Eterm*, UWord*);

Eterm get_keys_0(Process*, Eterm*, UWord*);
Eterm wrap_get_keys_0(Process*, Eterm*, UWord*);

Eterm ets_update_counter_4(Process*, Eterm*, UWord*);
Eterm wrap_ets_update_counter_4(Process*, Eterm*, UWord*);

Eterm erts_debug_map_info_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_map_info_1(Process*, Eterm*, UWord*);

Eterm erts_internal_is_process_executing_dirty_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_is_process_executing_dirty_1(Process*, Eterm*, UWord*);

Eterm erts_internal_check_dirty_process_code_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_check_dirty_process_code_2(Process*, Eterm*, UWord*);

Eterm erts_internal_purge_module_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_purge_module_2(Process*, Eterm*, UWord*);

Eterm binary_split_2(Process*, Eterm*, UWord*);
Eterm wrap_binary_split_2(Process*, Eterm*, UWord*);

Eterm binary_split_3(Process*, Eterm*, UWord*);
Eterm wrap_binary_split_3(Process*, Eterm*, UWord*);

Eterm erts_debug_size_shared_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_size_shared_1(Process*, Eterm*, UWord*);

Eterm erts_debug_copy_shared_1(Process*, Eterm*, UWord*);
Eterm wrap_erts_debug_copy_shared_1(Process*, Eterm*, UWord*);

Eterm has_prepared_code_on_load_1(Process*, Eterm*, UWord*);
Eterm wrap_has_prepared_code_on_load_1(Process*, Eterm*, UWord*);

Eterm maps_take_2(Process*, Eterm*, UWord*);
Eterm wrap_maps_take_2(Process*, Eterm*, UWord*);

Eterm floor_1(Process*, Eterm*, UWord*);
Eterm wrap_floor_1(Process*, Eterm*, UWord*);
Eterm erts_gc_floor_1(Process* p, Eterm* reg, Uint live);

Eterm ceil_1(Process*, Eterm*, UWord*);
Eterm wrap_ceil_1(Process*, Eterm*, UWord*);
Eterm erts_gc_ceil_1(Process* p, Eterm* reg, Uint live);

Eterm math_floor_1(Process*, Eterm*, UWord*);
Eterm wrap_math_floor_1(Process*, Eterm*, UWord*);

Eterm math_ceil_1(Process*, Eterm*, UWord*);
Eterm wrap_math_ceil_1(Process*, Eterm*, UWord*);

Eterm math_fmod_2(Process*, Eterm*, UWord*);
Eterm wrap_math_fmod_2(Process*, Eterm*, UWord*);

Eterm os_set_signal_2(Process*, Eterm*, UWord*);
Eterm wrap_os_set_signal_2(Process*, Eterm*, UWord*);

Eterm erts_internal_maps_to_list_2(Process*, Eterm*, UWord*);
Eterm wrap_erts_internal_maps_to_list_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_write_u8_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_write_u8_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_write_u32_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_write_u32_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_bytearray_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_bytearray_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_bytearray_sub_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_bytearray_sub_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_bytearray_update_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_bytearray_update_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_bitarray_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_bitarray_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_bitarray_sub_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_bitarray_sub_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_bitarray_update_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_bitarray_update_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_array_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_array_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_array_length_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_array_length_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_array_sub_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_array_sub_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_array_update_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_array_update_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_ref_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_ref_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_ref_get_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_ref_get_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_ref_set_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_ref_set_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_enter_code_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_enter_code_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_alloc_data_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_alloc_data_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_constants_size_0(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_constants_size_0(Process*, Eterm*, UWord*);

Eterm hipe_bifs_merge_term_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_merge_term_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_fun_to_address_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_fun_to_address_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_commit_patch_load_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_commit_patch_load_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_set_native_address_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_set_native_address_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_set_funinfo_native_address_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_set_funinfo_native_address_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_enter_sdesc_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_enter_sdesc_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_bif_address_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_bif_address_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_primop_address_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_primop_address_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_atom_to_word_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_atom_to_word_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_term_to_word_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_term_to_word_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_get_fe_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_get_fe_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_set_native_address_in_fe_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_set_native_address_in_fe_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_find_na_or_make_stub_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_find_na_or_make_stub_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_check_crc_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_check_crc_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_system_crc_0(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_system_crc_0(Process*, Eterm*, UWord*);

Eterm hipe_bifs_get_rts_param_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_get_rts_param_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_patch_insn_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_patch_insn_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_patch_call_3(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_patch_call_3(Process*, Eterm*, UWord*);

Eterm hipe_bifs_add_ref_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_add_ref_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_alloc_loader_state_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_alloc_loader_state_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_call_count_on_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_call_count_on_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_call_count_off_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_call_count_off_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_call_count_get_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_call_count_get_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_call_count_clear_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_call_count_clear_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_trap_count_get_0(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_trap_count_get_0(Process*, Eterm*, UWord*);

Eterm hipe_bifs_trap_count_clear_0(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_trap_count_clear_0(Process*, Eterm*, UWord*);

Eterm hipe_bifs_show_estack_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_show_estack_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_show_heap_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_show_heap_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_show_nstack_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_show_nstack_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_nstack_used_size_0(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_nstack_used_size_0(Process*, Eterm*, UWord*);

Eterm hipe_bifs_show_pcb_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_show_pcb_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_show_term_1(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_show_term_1(Process*, Eterm*, UWord*);

Eterm hipe_bifs_in_native_0(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_in_native_0(Process*, Eterm*, UWord*);

Eterm hipe_bifs_modeswitch_debug_on_0(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_modeswitch_debug_on_0(Process*, Eterm*, UWord*);

Eterm hipe_bifs_modeswitch_debug_off_0(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_modeswitch_debug_off_0(Process*, Eterm*, UWord*);

Eterm hipe_bifs_debug_native_called_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_debug_native_called_2(Process*, Eterm*, UWord*);

Eterm hipe_bifs_llvm_fix_pinned_regs_0(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_llvm_fix_pinned_regs_0(Process*, Eterm*, UWord*);

Eterm hipe_bifs_write_u64_2(Process*, Eterm*, UWord*);
Eterm wrap_hipe_bifs_write_u64_2(Process*, Eterm*, UWord*);


#include "hipe_nbif_impl.h"

#endif
